/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "BC-001",
    "stem": "A client recovering from a stroke has been cleared for a dysphagia diet. Which action by the nurse promotes safe oral intake?",
    "options": [
      "Offer thin liquids through a straw to encourage adequate hydration",
      "Position the client upright at 90 degrees with the chin tucked toward the chest during swallowing",
      "Encourage the client to talk during the meal to assess mental status",
      "Place food on the affected side of the mouth to stimulate sensation"
    ],
    "answer": 1,
    "rationale": "Upright positioning with a chin-tuck narrows the airway entrance and directs the bolus toward the esophagus, reducing aspiration risk. Thin liquids and straws increase aspiration in dysphagia, and food placed on the affected side tends to pocket and go unnoticed.",
    "why": [
      "Thin liquids move quickly and a straw delivers the bolus too fast, both increasing aspiration risk in dysphagia.",
      "Sitting fully upright with the chin tucked narrows the airway entrance and directs the bolus toward the esophagus.",
      "Talking during the meal opens the airway while swallowing and raises the chance of aspiration in this client.",
      "Food placed on the affected side pockets in the cheek unnoticed and can be aspirated later."
    ]
  },
  {
    "id": "BC-002",
    "stem": "Before administering an intermittent enteral feeding through a nasogastric tube, the nurse aspirates 320 mL of gastric residual. What is the nurse's best initial action?",
    "options": [
      "Hold the feeding, return the aspirate, and reassess the residual in 1 hour while monitoring for distention",
      "Discard the aspirate and administer the full feeding as scheduled",
      "Flush the tube with 60 mL of water and increase the feeding rate",
      "Remove the tube and notify the provider that it is obstructed"
    ],
    "answer": 0,
    "rationale": "A large residual suggests delayed gastric emptying and increased aspiration risk, so the feeding is held, the aspirate returned to preserve electrolytes and gastric contents, and the residual rechecked. Administering the feeding anyway compounds the risk, and a high residual does not mean the tube is obstructed.",
    "why": [
      "A 320 mL residual suggests delayed gastric emptying, so hold the feeding, return the aspirate to preserve electrolytes, and recheck.",
      "Discarding the aspirate wastes electrolytes and gastric acid, and feeding on top of a large residual compounds aspiration risk.",
      "Increasing the rate worsens an already delayed gastric emptying problem and further raises the risk of aspiration.",
      "Aspirating 320 mL proves the tube is patent rather than obstructed, so removing it is unnecessary and based on faulty reasoning."
    ]
  },
  {
    "id": "BC-003",
    "stem": "A client taking an opioid after orthopedic surgery reports no bowel movement for 3 days and abdominal fullness. Which nursing intervention should be implemented first?",
    "options": [
      "Administer a soapsuds enema",
      "Request an order for a bulk-forming laxative only",
      "Prepare the client for digital removal of stool",
      "Increase fluid intake, encourage ambulation, and give the prescribed stool softener with a stimulant laxative"
    ],
    "answer": 3,
    "rationale": "Opioid-induced constipation is managed first with the least invasive combination of hydration, activity, and a softener plus stimulant laxative. Bulk-forming agents alone can worsen opioid-related constipation, and enemas or manual disimpaction are reserved for when conservative measures fail.",
    "why": [
      "A soapsuds enema is invasive and irritating and is reserved for when conservative bowel measures have already failed.",
      "Bulk-forming laxatives used alone can worsen opioid-induced constipation by adding mass to an already slow-moving bowel.",
      "Digital removal of stool is a last resort for confirmed impaction, not a first intervention after three days.",
      "Hydration, ambulation, and a stool softener with a stimulant are the least invasive effective treatment for opioid-induced constipation."
    ]
  },
  {
    "id": "BC-004",
    "stem": "A client who had an indwelling urinary catheter removed 8 hours ago has not voided, reports suprapubic discomfort, and a bladder scan shows 480 mL. What should the nurse do first?",
    "options": [
      "Reinsert an indwelling catheter",
      "Encourage the client to drink two glasses of water and rescan in 2 hours",
      "Assist the client to a normal voiding position, provide privacy and warm water over the perineum, and if unsuccessful notify the provider for straight catheterization",
      "Apply a heating pad to the abdomen and document the finding"
    ],
    "answer": 2,
    "rationale": "Noninvasive measures that trigger the voiding reflex are attempted first, and intermittent straight catheterization is preferred over reinsertion of an indwelling catheter to reduce catheter-associated urinary tract infection risk. Adding more fluid to an already distended bladder delays relief and risks bladder injury.",
    "why": [
      "Reinserting an indwelling catheter is more invasive and carries higher infection risk than intermittent straight catheterization if drainage becomes necessary.",
      "Adding fluid to a bladder already holding 480 mL increases distention, risks bladder injury, and delays relief for two hours.",
      "Normal voiding position, privacy, and warm perineal water stimulate the voiding reflex first, with straight catheterization if that fails.",
      "A heating pad and documentation alone leave 480 mL of retained urine undrained and the suprapubic discomfort unrelieved."
    ]
  },
  {
    "id": "BC-005",
    "stem": "A nurse is teaching a client with left leg weakness how to use a cane. Which instruction is correct?",
    "options": [
      "Hold the cane in the right hand and advance the cane and the left leg together, then step with the right leg",
      "Hold the cane in the left hand and advance the cane with the left leg",
      "Hold the cane in the right hand and advance the right leg first",
      "Hold the cane with both hands in front of the body for maximum stability"
    ],
    "answer": 0,
    "rationale": "The cane is held on the stronger side and advanced with the weaker leg so the cane and the affected limb share the load and widen the base of support. Holding the cane on the weak side or advancing the strong leg first places full weight on the affected limb and increases fall risk.",
    "why": [
      "The cane goes in the stronger right hand and advances with the weak left leg so both share the load.",
      "Holding the cane in the left hand puts support on the same side as the weakness and narrows the base of support.",
      "Advancing the strong right leg first forces the weakened left leg to bear full body weight without cane support.",
      "A cane is a single-handed device; using both hands in front eliminates its function and destabilizes the gait."
    ]
  },
  {
    "id": "BC-006",
    "stem": "A bedbound client with limited mobility has nonblanchable erythema over the sacrum. Which intervention is the priority?",
    "options": [
      "Massage the reddened area to improve circulation",
      "Apply a moisture barrier ointment and continue the current turning schedule",
      "Reposition the client at least every 2 hours off the sacrum and use pressure-redistribution support surfaces",
      "Elevate the head of the bed to 60 degrees for comfort"
    ],
    "answer": 2,
    "rationale": "Nonblanchable erythema is a stage 1 pressure injury, and relieving pressure through frequent repositioning and support surfaces is the essential intervention to prevent progression. Massaging compromised tissue can cause further damage, and elevating the head of the bed above 30 degrees increases shear over the sacrum.",
    "why": [
      "Massaging tissue over a bony prominence that is already injured can drive deeper damage and is contraindicated in pressure injury.",
      "Barrier ointment treats moisture damage, and continuing the current schedule ignores that this schedule already failed to prevent injury.",
      "Nonblanchable erythema is a stage 1 pressure injury, so offloading with repositioning and redistribution surfaces prevents further progression.",
      "Elevating the head above 30 degrees increases shear and pressure across the sacrum, worsening the existing injury."
    ]
  },
  {
    "id": "BC-007",
    "stem": "A hospitalized client reports difficulty falling asleep and frequent awakenings. Which nursing measure should the nurse implement first?",
    "options": [
      "Request an order for a hypnotic medication at bedtime",
      "Offer a caffeinated beverage in the evening to normalize the schedule",
      "Encourage a long afternoon nap to make up for lost sleep",
      "Cluster nighttime care activities, dim lights, and reduce noise to allow uninterrupted sleep periods"
    ],
    "answer": 3,
    "rationale": "Nonpharmacologic sleep hygiene measures such as clustering care and controlling light and noise address the most common hospital causes of sleep disruption and carry no adverse effects. Hypnotics increase confusion and fall risk in hospitalized clients and should not be the first intervention, while daytime naps and caffeine further fragment nighttime sleep.",
    "why": [
      "Hypnotics increase confusion and fall risk in hospitalized clients and should not be the first sleep intervention attempted.",
      "Evening caffeine is a stimulant that lengthens sleep latency and further fragments this client's already disrupted sleep.",
      "A long afternoon nap reduces nighttime sleep drive and perpetuates the pattern of frequent nighttime awakenings.",
      "Clustering care, dimming lights, and reducing noise remove the most common hospital causes of disrupted sleep with no adverse effects."
    ]
  },
  {
    "id": "BC-008",
    "stem": "The nurse is assisting an unlicensed assistive personnel to transfer a client with right-sided hemiparesis from the bed to a wheelchair. Which action requires the nurse to intervene?",
    "options": [
      "Locking the wheelchair wheels before beginning the transfer",
      "Positioning the wheelchair on the client's right side and pulling the client up by the axillae",
      "Applying a gait belt around the client's waist",
      "Instructing the client to place the stronger hand on the wheelchair armrest"
    ],
    "answer": 1,
    "rationale": "The wheelchair should be placed on the client's stronger side, and lifting under the axillae risks brachial plexus injury and shoulder subluxation. Locking the wheels, using a gait belt, and having the client push with the unaffected arm are all correct, safe transfer techniques.",
    "why": [
      "Locking the wheelchair wheels before the transfer prevents the chair from rolling and is correct technique needing no intervention.",
      "The wheelchair belongs on the stronger left side, and pulling under the axillae risks brachial plexus injury and shoulder subluxation.",
      "A gait belt provides a secure handhold at the client's center of gravity and is recommended for assisted transfers.",
      "Having the client push with the stronger left hand on the armrest is safe and encourages active participation."
    ]
  },
  {
    "id": "BC-009",
    "stem": "A client with osteoarthritis of the knees asks about nonpharmacologic ways to reduce morning stiffness and pain. Which recommendation is most appropriate?",
    "options": [
      "Apply ice packs to the knees for 30 minutes each morning",
      "Rest the joints completely and avoid activity until the pain resolves",
      "Apply moist heat before activity and follow with gentle range-of-motion exercise",
      "Wrap the knees tightly with elastic bandages overnight"
    ],
    "answer": 2,
    "rationale": "Moist heat increases blood flow and tissue extensibility, relieving the stiffness of osteoarthritis and making subsequent gentle movement more effective. Cold is better suited to acute inflammatory flares, and complete inactivity leads to further stiffness, contracture, and muscle atrophy.",
    "why": [
      "Thirty minutes of ice each morning increases stiffness in osteoarthritis; cold is better suited to acute inflammatory flares.",
      "Complete rest until pain resolves leads to further stiffness, contracture, and muscle atrophy around the arthritic knees.",
      "Moist heat increases blood flow and tissue extensibility, easing morning stiffness so gentle range of motion becomes more effective.",
      "Tight elastic wraps worn overnight can impair circulation and do nothing to relieve osteoarthritic morning stiffness."
    ]
  },
  {
    "id": "BC-010",
    "stem": "The nurse is providing oral care for an unconscious client receiving oxygen by mask. Which action should the nurse take?",
    "options": [
      "Turn the client's head to the side and use suction while cleaning with a small amount of solution on a soft brush or swab",
      "Place the client supine and flat to allow full access to the mouth",
      "Use lemon-glycerin swabs every 2 hours to moisten the mucosa",
      "Omit oral care while the client is receiving nothing by mouth"
    ],
    "answer": 0,
    "rationale": "Side-lying positioning with suction available protects the airway of the unconscious client during oral care, which reduces oral bacterial load and ventilator- and hospital-associated pneumonia. Supine flat positioning invites aspiration, lemon-glycerin dries mucosa further, and NPO status makes oral care more important, not less.",
    "why": [
      "Side-lying positioning with suction available protects the unconscious client's airway while small amounts of solution clean the mouth safely.",
      "Lying supine and flat pools fluid at the back of the throat and invites aspiration in a client who cannot protect the airway.",
      "Lemon-glycerin swabs dry and irritate oral mucosa and are no longer recommended for oral care.",
      "Being NPO makes oral care more important, not optional, because bacteria and secretions still accumulate in the mouth."
    ]
  }
];

export default questions;
