/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "CV-001",
    "stem": "A client with chronic heart failure calls the clinic reporting a 4 lb weight gain over 2 days, new shortness of breath when lying flat, and swelling of both ankles. Which response by the nurse is most appropriate?",
    "options": [
      "You need to be evaluated today; these are signs your heart failure is worsening.",
      "Take an extra dose of your furosemide and call back next week.",
      "Increase your fluid intake to flush the extra sodium out of your body.",
      "This is a normal variation; weigh yourself again in 3 days."
    ],
    "answer": 0,
    "rationale": "A weight gain of more than 2 to 3 lb in 2 days with orthostatic dyspnea and edema signals fluid volume overload and decompensation requiring prompt evaluation. Self-adjusting diuretics without assessment is unsafe, and increasing fluid intake would worsen the congestion.",
    "why": [
      "Four pounds gained in two days with new orthopnea and bilateral ankle edema indicates fluid overload and decompensating heart failure needing same-day evaluation.",
      "Self-adjusting a diuretic without assessment risks hypokalemia and hypovolemia, and waiting a week allows the decompensation to progress toward pulmonary edema.",
      "Increasing fluids adds to the volume already overloading this client and would worsen both the orthopnea and the ankle edema.",
      "Rapid weight gain with orthopnea and edema is never a normal variation, and waiting three days delays treatment of worsening heart failure."
    ]
  },
  {
    "id": "CV-002",
    "stem": "A client with stable angina reports substernal chest pain rated 8 of 10 that began 10 minutes ago. Blood pressure is 138/84 mm Hg and heart rate 88/min. After the first sublingual nitroglycerin tablet, the pain is 6 of 10 and the blood pressure is 108/66 mm Hg. What should the nurse do next?",
    "options": [
      "Withhold further nitroglycerin because the blood pressure has fallen",
      "Administer sublingual morphine before repeating nitroglycerin",
      "Give a second nitroglycerin tablet in 5 minutes and recheck blood pressure",
      "Have the client ambulate to determine whether the pain is exertional"
    ],
    "answer": 2,
    "rationale": "Up to three sublingual nitroglycerin doses are given 5 minutes apart as long as the systolic blood pressure remains above 90 mm Hg, and this client has both residual pain and adequate pressure. Withholding the dose leaves ongoing myocardial ischemia untreated, and ambulation would increase myocardial oxygen demand during an anginal episode.",
    "why": [
      "A systolic pressure of 108 remains well above the 90 mm Hg threshold, so withholding the dose leaves ongoing myocardial ischemia untreated.",
      "Morphine is considered only after the full nitroglycerin sequence fails to relieve pain, and giving it now would mask ischemic symptoms.",
      "Up to three sublingual doses are given five minutes apart while systolic pressure stays above 90, and this client still has pain at 6 of 10.",
      "Exertion during an active anginal episode increases myocardial oxygen demand and can extend the ischemia; the diagnosis is already established."
    ]
  },
  {
    "id": "CV-003",
    "stem": "A client is admitted with new-onset atrial fibrillation with a ventricular rate of 156/min, blood pressure 88/54 mm Hg, and reports lightheadedness and chest pressure. Which prescription should the nurse question?",
    "options": [
      "Prepare the client for synchronized cardioversion",
      "Apply oxygen at 2 L/min by nasal cannula",
      "Obtain a stat 12-lead ECG and serum electrolytes",
      "Administer metoprolol 5 mg IV push now"
    ],
    "answer": 3,
    "rationale": "The client is hemodynamically unstable, and IV beta blockade would further lower an already low blood pressure; unstable atrial fibrillation with a rapid ventricular response is treated with synchronized cardioversion. Oxygen and diagnostic studies are appropriate supportive measures that do not compromise perfusion.",
    "why": [
      "Synchronized cardioversion is the indicated treatment for unstable atrial fibrillation with a rapid ventricular response, so this order should be carried out.",
      "Supplemental oxygen supports myocardial oxygenation during chest pressure and does not compromise perfusion, so this order needs no clarification.",
      "A stat 12-lead ECG with electrolytes guides therapy and identifies reversible causes without delaying care, so it is an appropriate order.",
      "IV metoprolol would further lower a blood pressure already at 88/54 in a hemodynamically unstable client, so this prescription must be questioned."
    ]
  },
  {
    "id": "CV-004",
    "stem": "A client taking digoxin for heart failure reports nausea, anorexia, and seeing yellow-green halos around lights. The apical pulse is 52/min. Which action should the nurse take first?",
    "options": [
      "Administer the scheduled digoxin dose and monitor the pulse",
      "Hold the digoxin and obtain a serum digoxin level and potassium",
      "Encourage the client to eat crackers before the dose to reduce nausea",
      "Give an antiemetic and reassess in 30 minutes"
    ],
    "answer": 1,
    "rationale": "Visual halos, gastrointestinal upset, and bradycardia below 60/min are classic digoxin toxicity, so the drug is held and a level with electrolytes is obtained since hypokalemia potentiates toxicity. Administering the dose would deepen the toxicity, and treating only the nausea masks a dangerous drug effect.",
    "why": [
      "Administering another dose to a client with halos, anorexia, and an apical rate of 52 would deepen the toxicity and risk severe bradydysrhythmias.",
      "Yellow-green halos, anorexia, nausea, and an apical pulse of 52 are classic digoxin toxicity, so the drug is held while level and potassium are checked.",
      "Eating crackers treats the nausea as simple stomach upset and ignores that it is a warning sign of digoxin toxicity.",
      "An antiemetic relieves one symptom while masking evidence of toxicity, and the bradycardia and visual disturbances would remain untreated."
    ]
  },
  {
    "id": "CV-005",
    "stem": "A nurse is teaching a client newly prescribed lisinopril for hypertension. Which client statement indicates a need for further teaching?",
    "options": [
      "I will rise slowly from bed to avoid getting dizzy.",
      "I will call my provider if I develop swelling of my lips or tongue.",
      "I will use a salt substitute on my food instead of table salt.",
      "A dry, persistent cough is something I should report to my provider."
    ],
    "answer": 2,
    "rationale": "Most salt substitutes are potassium chloride, and ACE inhibitors reduce potassium excretion, so their combined use risks hyperkalemia and dysrhythmias. The other statements correctly reflect orthostatic precautions, recognition of angioedema, and reporting the ACE inhibitor cough.",
    "why": [
      "Rising slowly is accurate teaching for the orthostatic hypotension that ACE inhibitors commonly cause, especially with early doses.",
      "Recognizing lip or tongue swelling as angioedema and calling the provider is exactly the right response to this rare, life-threatening reaction.",
      "This statement needs correction because salt substitutes are potassium chloride and lisinopril reduces potassium excretion, creating a risk of hyperkalemia and dysrhythmias.",
      "A persistent dry cough from bradykinin accumulation is a well-known ACE inhibitor effect that should be reported, so this statement is accurate."
    ]
  },
  {
    "id": "CV-006",
    "stem": "A postoperative client reports new unilateral calf pain, and the nurse notes the right calf is 4 cm larger than the left, warm, and reddened. Which action should the nurse take first?",
    "options": [
      "Notify the provider and maintain the client on bed rest with the leg supported",
      "Vigorously massage the calf to relieve the muscle cramp",
      "Apply sequential compression devices to both legs immediately",
      "Have the client ambulate to determine whether the pain resolves"
    ],
    "answer": 0,
    "rationale": "Unilateral calf swelling, warmth, and pain suggest deep vein thrombosis, and the client is kept at rest while the provider is notified and diagnostic ultrasound is arranged, to reduce the chance of clot dislodgement. Massage and ambulation before diagnosis can dislodge a thrombus and cause pulmonary embolism.",
    "why": [
      "Unilateral calf swelling, warmth, and pain suggest deep vein thrombosis, so rest with the leg supported limits clot movement while ultrasound is arranged.",
      "Massaging a suspected thrombus can dislodge it and cause a pulmonary embolism, so it is contraindicated with these findings.",
      "Sequential compression over an existing clot can propel it centrally, and these devices are intended for prevention rather than treatment.",
      "Ambulating to see whether the pain resolves both delays diagnosis and risks dislodging a clot into the pulmonary circulation."
    ]
  },
  {
    "id": "CV-007",
    "stem": "A nurse is teaching a client with peripheral arterial disease about self-care. Which instruction should the nurse include?",
    "options": [
      "Elevate your legs above heart level whenever you are sitting.",
      "Apply a heating pad to your feet at night to improve circulation.",
      "Wear knee-high compression stockings during the day.",
      "Inspect your feet daily and wear well-fitting shoes at all times."
    ],
    "answer": 3,
    "rationale": "Arterial insufficiency reduces perfusion and healing capacity, so daily foot inspection and protective footwear prevent unnoticed injury and ulceration. Elevating the legs and applying compression further reduce arterial inflow (appropriate for venous disease instead), and heating pads risk burns in a limb with impaired sensation and perfusion.",
    "why": [
      "Elevating the legs reduces arterial inflow to already ischemic tissue; elevation is appropriate for venous disease, not arterial insufficiency.",
      "Heating pads risk serious burns in a limb with impaired sensation and poor perfusion that cannot dissipate the heat.",
      "Compression stockings are a venous insufficiency measure and would further restrict arterial blood flow in peripheral arterial disease.",
      "Reduced arterial perfusion impairs healing, so daily foot inspection and well-fitting shoes keep small unnoticed injuries from progressing to ulcers."
    ]
  },
  {
    "id": "CV-008",
    "stem": "A client with hypertension has been taking metoprolol for 3 months and tells the nurse about plans to stop it because the blood pressure is now normal. What is the nurse's best response?",
    "options": [
      "That is reasonable; you can stop once two readings are under 120/80.",
      "Stopping this medication suddenly can cause rebound hypertension and chest pain, so it must be tapered by your provider.",
      "You can stop the metoprolol as long as you continue to exercise regularly.",
      "Cut the tablets in half yourself and stop after 2 days."
    ],
    "answer": 1,
    "rationale": "Abrupt beta blocker withdrawal causes rebound tachycardia, hypertension, and can precipitate angina or myocardial infarction from receptor upregulation, so any discontinuation is tapered under provider supervision. Normal readings reflect drug effectiveness rather than resolution of hypertension, so stopping on that basis is unsafe.",
    "why": [
      "Normal readings show the medication is working rather than that hypertension has resolved, so stopping on that basis invites rebound effects.",
      "Abrupt beta blocker withdrawal causes rebound tachycardia and hypertension from receptor upregulation and can precipitate angina or infarction, so tapering is provider directed.",
      "Regular exercise supports blood pressure control but offers no protection against the rebound sympathetic surge of abruptly stopping metoprolol.",
      "A self-designed two-day taper is far too rapid and is not a dosing decision the client should make without the provider."
    ]
  },
  {
    "id": "CV-009",
    "stem": "A client on long-term warfarin therapy is being taught about diet. Which client statement indicates correct understanding?",
    "options": [
      "I will keep my intake of green leafy vegetables about the same from week to week.",
      "I should completely eliminate all spinach, kale, and broccoli from my diet.",
      "I can take over-the-counter ibuprofen for my arthritis whenever I need it.",
      "I will double my dose on any day I eat a large salad."
    ],
    "answer": 0,
    "rationale": "Warfarin dosing is titrated to a client's usual vitamin K intake, so consistency rather than elimination keeps the INR stable. Eliminating all vitamin K foods causes wide INR swings if the client resumes them, ibuprofen adds bleeding risk, and clients never self-adjust warfarin doses.",
    "why": [
      "Warfarin is titrated to the client's usual vitamin K intake, so keeping green leafy vegetable consumption consistent week to week keeps the INR stable.",
      "Complete elimination is unnecessary and produces wide INR swings whenever the client later resumes eating those vegetables.",
      "Ibuprofen inhibits platelet function and irritates gastric mucosa, compounding warfarin's bleeding risk, so it should not be used freely.",
      "Clients never self-adjust warfarin doses, and doubling it after a salad would push the INR into a dangerous range."
    ]
  },
  {
    "id": "CV-010",
    "stem": "Twelve hours after coronary artery bypass surgery, a client has muffled heart sounds, blood pressure 84/70 mm Hg, jugular venous distention, and a sudden decrease in chest tube drainage from 100 mL/hr to 5 mL/hr. Which complication should the nurse suspect?",
    "options": [
      "Pulmonary embolism",
      "Hypovolemic shock from graft site bleeding",
      "Cardiac tamponade",
      "Acute graft occlusion with myocardial infarction"
    ],
    "answer": 2,
    "rationale": "Muffled heart sounds, hypotension with a narrowed pulse pressure, and jugular venous distention form Beck triad, and the abrupt drop in chest tube output suggests the tube has clotted while blood accumulates in the pericardium. Hypovolemic shock would present with flat neck veins rather than distention, which is the key distinguishing finding.",
    "why": [
      "Pulmonary embolism causes sudden dyspnea and hypoxemia rather than muffled heart sounds with an abrupt fall in chest tube drainage.",
      "Bleeding-related hypovolemia produces flat neck veins, whereas this client has jugular venous distention, which is the key distinguishing finding.",
      "Muffled heart sounds, hypotension with a narrow pulse pressure, and jugular distention form Beck triad, and the sudden drainage drop suggests a clotted chest tube.",
      "Acute graft occlusion produces ischemic ECG changes and chest pain rather than muffled sounds with distended neck veins and stopped drainage."
    ]
  }
];

export default questions;
