/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */

/** How many questions each topic actually has in the bank. */
export const BANK_COUNTS: Record<string, number> = {
  "basic-care": 10,
  "cardiovascular": 10,
  "dosage-and-labs": 10,
  "endocrine": 10,
  "fundamentals": 10,
  "gastrointestinal": 10,
  "health-promotion": 10,
  "maternity-newborn": 10,
  "med-surg": 10,
  "mental-health": 10,
  "neurological": 10,
  "pediatrics": 10,
  "pharmacology": 10,
  "prioritization-delegation": 10,
  "psychosocial": 10,
  "renal-genitourinary": 10,
  "respiratory": 10,
  "risk-reduction": 10,
  "safe-care": 20
};
