/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "DL-001",
    "stem": "A client is prescribed 1,000 mL of 0.9% sodium chloride to infuse over 8 hours by infusion pump. At what rate in mL/hr should the nurse set the pump?",
    "options": [
      "62 mL/hr",
      "100 mL/hr",
      "133 mL/hr",
      "125 mL/hr"
    ],
    "answer": 3,
    "rationale": "Total volume divided by total time equals 1,000 mL / 8 hr = 125 mL/hr. Selecting 133 mL/hr would reflect dividing by 7.5 hours and would deliver excess fluid, a risk for clients with cardiac or renal compromise.",
    "why": [
      "62 mL/hr is half the correct rate, the result of dividing 1,000 mL by 16 hours instead of 8.",
      "100 mL/hr comes from dividing 1,000 mL by 10 hours rather than the ordered 8 hours, underinfusing the client.",
      "133 mL/hr reflects dividing 1,000 mL by 7.5 hours and would deliver excess fluid to a client with cardiac or renal compromise.",
      "Total volume divided by total time gives 1,000 mL divided by 8 hours, which equals 125 mL/hr."
    ]
  },
  {
    "id": "DL-002",
    "stem": "The nurse must infuse 500 mL of lactated Ringer's over 4 hours using gravity tubing with a drop factor of 15 gtt/mL. How many drops per minute should the nurse regulate the infusion to deliver?",
    "options": [
      "21 gtt/min",
      "31 gtt/min",
      "42 gtt/min",
      "63 gtt/min"
    ],
    "answer": 1,
    "rationale": "(500 mL x 15 gtt/mL) / 240 min = 7,500 / 240 = 31.25, which rounds to 31 gtt/min. Choosing 63 gtt/min would double the intended rate, reflecting use of a 2-hour rather than 4-hour infusion time.",
    "why": [
      "21 gtt/min results from applying a 10 gtt/mL drop factor instead of the 15 gtt/mL tubing actually in use.",
      "500 mL times 15 gtt/mL divided by 240 minutes equals 7,500/240, or 31.25, which rounds to 31 gtt/min.",
      "42 gtt/min comes from using a 20 gtt/mL drop factor and would infuse the lactated Ringer's much too quickly.",
      "63 gtt/min doubles the correct rate by dividing over 120 minutes rather than the ordered 240 minutes."
    ]
  },
  {
    "id": "DL-003",
    "stem": "A client with heart failure who takes digoxin and furosemide has a serum potassium level of 2.8 mEq/L. The morning digoxin dose is due. Which action should the nurse take first?",
    "options": [
      "Withhold the digoxin and notify the provider about the potassium level",
      "Administer the digoxin and encourage the client to eat bananas and oranges",
      "Give the scheduled furosemide dose as ordered",
      "Recheck the potassium level with morning laboratory draws tomorrow"
    ],
    "answer": 0,
    "rationale": "Hypokalemia (normal 3.5 to 5.0 mEq/L) potentiates digoxin binding at the myocardium and precipitates toxicity and lethal dysrhythmias, so the dose is held and the provider notified. Giving furosemide would drive the potassium even lower, worsening the very problem that must be corrected.",
    "why": [
      "A potassium of 2.8 mEq/L potentiates digoxin binding at the myocardium, so the dose is held and the provider notified.",
      "Dietary potassium raises the level far too slowly, and giving digoxin now exposes the client to toxicity and lethal dysrhythmias.",
      "Furosemide wastes more potassium and would drive the level of 2.8 mEq/L even lower, worsening the underlying problem.",
      "Waiting until tomorrow leaves a critically low potassium untreated while the client receives a drug made dangerous by it."
    ]
  },
  {
    "id": "DL-004",
    "stem": "A 24 kg child is prescribed an antibiotic at 30 mg/kg/day divided every 8 hours. How many milligrams should the nurse administer per dose?",
    "options": [
      "80 mg",
      "180 mg",
      "240 mg",
      "720 mg"
    ],
    "answer": 2,
    "rationale": "30 mg/kg x 24 kg = 720 mg/day, and 720 mg divided by 3 doses = 240 mg per dose. Selecting 720 mg would give the entire daily amount in a single administration, a threefold overdose.",
    "why": [
      "80 mg results from dividing the 720 mg daily dose by 9 rather than by the three doses given every 8 hours.",
      "180 mg comes from dividing 720 mg by four doses, as though the drug were scheduled every 6 hours instead of every 8.",
      "30 mg/kg times 24 kg equals 720 mg per day, and 720 mg divided by three doses gives 240 mg per dose.",
      "720 mg is the entire daily amount given at once, a threefold overdose of the ordered every-8-hour dose."
    ]
  },
  {
    "id": "DL-005",
    "stem": "A client taking digoxin reports nausea and seeing yellow halos around lights. The apical pulse is 52/min and the serum digoxin level is 2.6 ng/mL. Which action should the nurse take?",
    "options": [
      "Withhold the dose, notify the provider, and monitor the client for dysrhythmias",
      "Administer the dose and recheck the apical pulse in 1 hour",
      "Give the dose with food to reduce the nausea",
      "Encourage the client to follow a potassium-restricted diet"
    ],
    "answer": 0,
    "rationale": "A level above the therapeutic range of 0.5 to 2.0 ng/mL with bradycardia, nausea, and visual halos indicates digoxin toxicity, so the drug is held and the provider notified while cardiac monitoring continues. Giving the dose with food does not reduce serum drug levels and would deepen the toxicity.",
    "why": [
      "A level of 2.6 ng/mL with a pulse of 52, nausea, and yellow halos indicates digoxin toxicity, so the dose is held.",
      "Giving digoxin with an apical pulse of 52 and a toxic serum level deepens the bradycardia and risks lethal dysrhythmias.",
      "Food does not lower a serum level of 2.6 ng/mL; this nausea reflects toxicity rather than simple gastric irritation.",
      "Restricting potassium is backwards, because hypokalemia worsens digoxin toxicity rather than relieving it."
    ]
  },
  {
    "id": "DL-006",
    "stem": "A client receiving warfarin for atrial fibrillation has an INR of 6.8 with no evidence of active bleeding. The next dose is due. Which action should the nurse take?",
    "options": [
      "Administer the dose as scheduled and document the INR",
      "Administer protamine sulfate as the antidote",
      "Increase dietary vitamin K immediately and give the dose",
      "Hold the warfarin, notify the provider, and anticipate an order for vitamin K (phytonadione)"
    ],
    "answer": 3,
    "rationale": "A therapeutic INR for atrial fibrillation is 2 to 3, so 6.8 carries a high hemorrhage risk; the dose is held, the provider notified, and vitamin K anticipated. Protamine sulfate reverses heparin, not warfarin, and giving it would leave the elevated INR untreated.",
    "why": [
      "Giving warfarin at an INR of 6.8 adds further anticoagulation and sharply increases the risk of spontaneous hemorrhage.",
      "Protamine sulfate reverses heparin, not warfarin, so giving it would leave the dangerously prolonged INR untreated.",
      "Dietary vitamin K acts far too slowly to correct an INR of 6.8, and giving the dose compounds the problem.",
      "With a target INR of 2 to 3, a value of 6.8 requires holding the dose, notifying the provider, and anticipating vitamin K."
    ]
  },
  {
    "id": "DL-007",
    "stem": "A client who weighs 176 lb is prescribed a medication at 0.5 mg/kg as a single dose. How many milligrams should the nurse administer?",
    "options": [
      "35 mg",
      "40 mg",
      "44 mg",
      "88 mg"
    ],
    "answer": 1,
    "rationale": "176 lb / 2.2 = 80 kg, and 80 kg x 0.5 mg/kg = 40 mg. Choosing 88 mg results from multiplying pounds by 0.5 without converting to kilograms, which would more than double the intended dose.",
    "why": [
      "35 mg results from using an assumed 70 kg weight instead of converting the client's actual 176 lb to kilograms.",
      "176 lb divided by 2.2 equals 80 kg, and 80 kg times 0.5 mg/kg equals a 40 mg dose.",
      "44 mg comes from dividing 176 by 2 instead of 2.2, yielding 88 kg and an excessive dose.",
      "88 mg results from multiplying pounds directly by 0.5 without converting to kilograms, more than doubling the intended dose."
    ]
  },
  {
    "id": "DL-008",
    "stem": "A client with small cell lung cancer has a serum sodium of 118 mEq/L and is increasingly confused and lethargic. Which action should the nurse take first?",
    "options": [
      "Encourage the client to drink at least 2 L of water daily",
      "Administer a 1,000 mL bolus of 0.9% sodium chloride over 15 minutes",
      "Initiate seizure precautions and notify the provider",
      "Recheck the sodium level with the morning laboratory draw"
    ],
    "answer": 2,
    "rationale": "Severe hyponatremia (normal 135 to 145 mEq/L) causes cerebral edema, and confusion signals impending seizures, so safety measures and provider notification come first. Encouraging free water would further dilute the sodium, and rapid uncontrolled saline correction risks osmotic demyelination.",
    "why": [
      "Encouraging 2 L of water daily further dilutes a sodium of 118 mEq/L and would deepen the cerebral edema.",
      "A 1,000 mL bolus over 15 minutes corrects sodium far too rapidly and risks osmotic demyelination syndrome.",
      "A sodium of 118 mEq/L with confusion signals cerebral edema and impending seizures, so precautions and provider notification come first.",
      "Waiting for morning labs leaves a client with critical hyponatremia and altered mental status unprotected from seizures."
    ]
  },
  {
    "id": "DL-009",
    "stem": "A client who received regular insulin at 0730 is diaphoretic, shaky, and anxious at 1000. The bedside glucose is 52 mg/dL. The client is alert and able to swallow. Which action should the nurse take first?",
    "options": [
      "Give 4 ounces of orange juice",
      "Administer 1 mg of glucagon intramuscularly",
      "Start an intravenous line and give 50% dextrose",
      "Recheck the glucose level in 15 minutes before intervening"
    ],
    "answer": 0,
    "rationale": "For a conscious client with an intact swallow, 15 g of a fast-acting oral carbohydrate such as 4 ounces of juice is the standard first treatment, followed by a repeat glucose in 15 minutes. Glucagon and IV dextrose are reserved for clients who are unconscious or unable to swallow safely, and delaying treatment allows neuroglycopenia to worsen.",
    "why": [
      "For an alert client who can swallow, 4 ounces of juice delivers about 15 g of fast-acting carbohydrate, the standard first treatment.",
      "Glucagon is reserved for hypoglycemic clients who are unconscious or unable to swallow, so it is unnecessarily invasive here.",
      "IV 50% dextrose is for clients who cannot take oral carbohydrate, and starting a line first delays needed treatment.",
      "Rechecking before treating delays correction of a glucose of 52 mg/dL and lets neuroglycopenic symptoms worsen."
    ]
  },
  {
    "id": "DL-010",
    "stem": "A client receiving chemotherapy has a platelet count of 18,000/mm3. Which intervention should the nurse implement?",
    "options": [
      "Encourage the client to brush with a firm-bristled toothbrush after every meal",
      "Administer the prescribed medication by intramuscular injection into the deltoid",
      "Institute bleeding precautions, avoid invasive procedures, and hold anticoagulants pending provider review",
      "Place the client in a private room and require all visitors to wear a mask"
    ],
    "answer": 2,
    "rationale": "A platelet count below 20,000/mm3 carries a high risk of spontaneous hemorrhage, so bleeding precautions and avoidance of punctures and anticoagulants are the priority. Masking visitors addresses neutropenia rather than thrombocytopenia, and firm brushing or IM injections would directly provoke bleeding.",
    "why": [
      "Firm-bristled brushing traumatizes the gums and provokes bleeding when the platelet count is only 18,000/mm3.",
      "Intramuscular injection punctures muscle and causes hematoma formation in severe thrombocytopenia, so oral or IV routes are preferred.",
      "A platelet count below 20,000/mm3 carries high risk of spontaneous hemorrhage, so bleeding precautions and avoiding punctures are the priority.",
      "A private room with masked visitors addresses neutropenia and infection risk, not the bleeding risk of thrombocytopenia."
    ]
  }
];

export default questions;
