/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "EN-001",
    "stem": "A 19-year-old client with type 1 diabetes arrives in the emergency department with a blood glucose of 486 mg/dL, arterial pH 7.18, bicarbonate 12 mEq/L, potassium 5.6 mEq/L, and Kussmaul respirations. Which action should the nurse take first?",
    "options": [
      "Administer subcutaneous insulin glargine as ordered",
      "Give 1 ampule of sodium bicarbonate IV push",
      "Begin an IV infusion of 0.9% sodium chloride at 15 mL/kg/hr",
      "Start an IV potassium chloride infusion at 20 mEq/hr"
    ],
    "answer": 2,
    "rationale": "Diabetic ketoacidosis causes profound osmotic diuresis, so isotonic fluid resuscitation is the first priority to restore circulating volume and tissue perfusion, consistent with the ABC/circulation framework. Long-acting subcutaneous insulin is inappropriate in DKA because absorption is unreliable in a volume-depleted client; regular insulin by continuous IV infusion is started after fluids are underway.",
    "why": [
      "Long-acting glargine absorbs unpredictably in a volume-depleted client and does not correct the deficit; DKA requires a regular insulin infusion after fluids.",
      "Bicarbonate is reserved for extreme acidemia near a pH of 6.9 and risks hypokalemia and paradoxical CNS acidosis without restoring perfusion.",
      "Osmotic diuresis has depleted intravascular volume, so isotonic saline restores perfusion first and begins lowering glucose before the insulin infusion starts.",
      "Potassium is already 5.6 mEq/L, so infusing it now could trigger lethal dysrhythmias; replacement waits until levels fall during insulin therapy."
    ]
  },
  {
    "id": "EN-002",
    "stem": "A client with type 2 diabetes receives NPH insulin at 0700 each morning and reports feeling shaky at work. At which time should the nurse teach the client that a hypoglycemic reaction is most likely to occur?",
    "options": [
      "Between 1100 and 1900, when NPH reaches its peak action",
      "Between 0715 and 0745, when NPH begins to peak",
      "Between 2200 and 2400, well after the evening meal",
      "Immediately after the injection, within 10 to 15 minutes"
    ],
    "answer": 0,
    "rationale": "NPH is an intermediate-acting insulin with an onset of about 1 to 2 hours and a peak of roughly 4 to 12 hours, placing peak risk in the late morning through early evening after a 0700 dose. The 10-to-15-minute window describes rapid-acting analogs such as lispro, not NPH, so that option reflects the wrong pharmacokinetic profile.",
    "why": [
      "NPH peaks roughly 4 to 12 hours after a 0700 dose, placing greatest hypoglycemia risk from late morning into early evening.",
      "NPH has not even reached onset by 15 to 45 minutes; its onset is about 1 to 2 hours, so peaking then is impossible.",
      "Late evening risk is lower after a morning NPH dose because the peak has already passed and the evening meal has been eaten.",
      "An effect within 10 to 15 minutes describes rapid-acting analogs such as lispro or aspart, not intermediate-acting NPH, so this timing is wrong."
    ]
  },
  {
    "id": "EN-003",
    "stem": "A client who is alert and oriented reports dizziness and diaphoresis; a fingerstick glucose is 52 mg/dL. Which action should the nurse take first?",
    "options": [
      "Administer 1 mg of glucagon intramuscularly",
      "Recheck the blood glucose in 30 minutes",
      "Give the client a peanut butter sandwich and whole milk",
      "Provide 15 g of a fast-acting carbohydrate such as 4 oz of juice"
    ],
    "answer": 3,
    "rationale": "For a conscious client with hypoglycemia, the rule of 15 applies: give 15 g of fast-acting carbohydrate, recheck in 15 minutes, and repeat as needed before adding a protein-containing snack. Glucagon is reserved for clients who are unconscious or unable to swallow safely, so giving it here is unnecessary and delays a simpler, safer intervention.",
    "why": [
      "Glucagon is reserved for clients who are unconscious or cannot swallow safely; this client is alert, so an injection is unnecessary and delays simpler treatment.",
      "Waiting 30 minutes leaves a symptomatic client hypoglycemic; the recheck happens 15 minutes after carbohydrate is given, not instead of giving it.",
      "Protein and fat slow glucose absorption, so this snack belongs after the glucose is corrected and only if the next meal is delayed.",
      "The rule of 15 applies to a conscious hypoglycemic client: give 15 grams of fast-acting carbohydrate, then recheck the glucose in 15 minutes."
    ]
  },
  {
    "id": "EN-004",
    "stem": "The nurse is caring for a client on the first postoperative day after a subtotal thyroidectomy. Which assessment finding requires immediate follow-up?",
    "options": [
      "Hoarseness and a weak voice when speaking",
      "Temperature 103.4 F, heart rate 148, and increasing agitation",
      "Complaints of a sore throat when swallowing liquids",
      "A small amount of serosanguineous drainage on the neck dressing"
    ],
    "answer": 1,
    "rationale": "Hyperthermia, extreme tachycardia, and agitation suggest thyroid storm, a life-threatening surge of thyroid hormone requiring immediate provider notification, cooling, beta-blockade, and antithyroid therapy. Hoarseness is common after thyroidectomy from airway manipulation or transient laryngeal nerve irritation and is monitored rather than treated emergently.",
    "why": [
      "Hoarseness and a weak voice are expected after airway manipulation and are usually transient; they are monitored rather than treated as an emergency.",
      "Hyperthermia, a heart rate of 148, and agitation signal thyroid storm, a life-threatening hormone surge needing cooling, beta-blockade, and antithyroid therapy.",
      "A sore throat with swallowing is expected after intubation and a neck incision, so it calls for comfort measures rather than immediate follow-up.",
      "A small amount of serosanguineous drainage is normal; only copious drainage or pooling behind the neck would suggest hemorrhage requiring urgent action."
    ]
  },
  {
    "id": "EN-005",
    "stem": "Eight hours after a total thyroidectomy, a client reports tingling around the mouth and in the fingertips, and the nurse elicits facial twitching when tapping over the facial nerve. Which action should the nurse anticipate?",
    "options": [
      "Administering IV calcium gluconate as ordered",
      "Encouraging the client to breathe into a paper bag",
      "Administering a dose of levothyroxine",
      "Applying an ice collar to the surgical site"
    ],
    "answer": 0,
    "rationale": "A positive Chvostek sign with perioral and digital paresthesias indicates hypocalcemia from inadvertent parathyroid injury or removal, and IV calcium gluconate is the treatment to prevent laryngospasm and tetany. Rebreathing into a bag treats respiratory alkalosis from hyperventilation and would not correct the underlying calcium deficit, delaying definitive therapy.",
    "why": [
      "A positive Chvostek sign with perioral and digital tingling indicates hypocalcemia from parathyroid injury, and IV calcium gluconate prevents laryngospasm and tetany.",
      "Rebreathing treats paresthesias caused by hyperventilation-induced respiratory alkalosis; here the serum calcium itself is low, so this would delay definitive replacement.",
      "Levothyroxine replaces thyroid hormone, which is not the deficiency producing these symptoms, and it takes days to act on an acute calcium problem.",
      "An ice collar eases incisional swelling and pain but has no effect on the calcium deficit causing the twitching and paresthesias."
    ]
  },
  {
    "id": "EN-006",
    "stem": "A client with Addison disease is admitted after two days of vomiting. Blood pressure is 78/44, heart rate 124, sodium 126 mEq/L, and potassium 5.9 mEq/L. Which prescription should the nurse implement first?",
    "options": [
      "Oral fludrocortisone 0.1 mg daily",
      "Sodium polystyrene sulfonate 15 g orally",
      "IV hydrocortisone with 0.9% sodium chloride infusion",
      "Regular insulin 10 units IV push"
    ],
    "answer": 2,
    "rationale": "Addisonian crisis is a shock state caused by cortisol and aldosterone deficiency, and IV glucocorticoid replacement with isotonic saline simultaneously treats the hypotension, hyponatremia, and hyperkalemia. An oral agent such as fludrocortisone acts too slowly and cannot be relied on in a vomiting, hypotensive client, so it does not address the immediate circulatory threat.",
    "why": [
      "Oral fludrocortisone cannot be absorbed reliably in a vomiting client and acts far too slowly to reverse shock-level hypotension in adrenal crisis.",
      "Sodium polystyrene sulfonate lowers potassium over hours and is oral, which is unsafe with active vomiting; hydrocortisone corrects the hyperkalemia at its source.",
      "IV hydrocortisone with isotonic saline replaces missing cortisol and volume, simultaneously reversing the hypotension, hyponatremia, and hyperkalemia of Addisonian crisis.",
      "Insulin shifts potassium intracellularly but is not indicated here; without glucose it risks hypoglycemia and ignores the cortisol deficiency driving the crisis."
    ]
  },
  {
    "id": "EN-007",
    "stem": "The nurse is teaching a client newly diagnosed with Cushing syndrome. Which client statement indicates correct understanding of self-care?",
    "options": [
      "I should add extra salt to my food to keep my blood pressure up",
      "I will report any fever or sore throat right away because infections may be masked",
      "Bruising easily means my platelet count is dangerously low",
      "I can stop my medication once my face returns to its normal shape"
    ],
    "answer": 1,
    "rationale": "Excess cortisol suppresses the inflammatory response, so classic signs of infection may be blunted and any fever or sore throat warrants prompt reporting; this reflects a safety and infection-prevention priority. Adding salt is incorrect because cortisol excess already promotes sodium and water retention with resulting hypertension and edema.",
    "why": [
      "Cortisol excess already causes sodium and water retention with hypertension and edema, so adding salt would worsen fluid overload rather than help.",
      "Excess cortisol blunts the inflammatory response and can mask infection, so any fever or sore throat must be reported promptly.",
      "Easy bruising in Cushing syndrome comes from cortisol-induced capillary fragility and thinned skin, not from thrombocytopenia, so this belief is factually inaccurate.",
      "Therapy is not stopped once moon facies improves; abruptly discontinuing steroid replacement after treatment can precipitate a life-threatening adrenal crisis."
    ]
  },
  {
    "id": "EN-008",
    "stem": "A client with small cell lung cancer has a serum sodium of 118 mEq/L, urine specific gravity of 1.032, and is increasingly lethargic. Which intervention should the nurse expect to implement?",
    "options": [
      "Encourage oral fluids to 3,000 mL per day",
      "Administer desmopressin intranasally",
      "Infuse 5% dextrose in water at 125 mL/hr",
      "Restrict fluids to approximately 800 to 1,000 mL per day"
    ],
    "answer": 3,
    "rationale": "The dilutional hyponatremia with concentrated urine is characteristic of SIADH, and fluid restriction is the cornerstone of treatment to raise serum sodium and prevent cerebral edema and seizures. Encouraging fluids would worsen the water retention and drop sodium further, increasing the risk of neurologic deterioration.",
    "why": [
      "Pushing 3,000 mL daily would deepen the dilutional hyponatremia and increase the risk of cerebral edema and seizures in this lethargic client.",
      "Desmopressin is synthetic ADH used for diabetes insipidus; giving it in SIADH adds to the excess antidiuretic hormone already causing water retention.",
      "Dextrose in water becomes free water once the dextrose is metabolized, so it would dilute serum sodium further and worsen the neurologic decline.",
      "Restricting intake to roughly 800 to 1,000 mL daily reverses the water retention of SIADH and gradually raises the serum sodium."
    ]
  },
  {
    "id": "EN-009",
    "stem": "A client is being monitored after transsphenoidal pituitary surgery. Which finding should the nurse report to the provider immediately?",
    "options": [
      "Urine output of 60 mL/hr with a specific gravity of 1.018",
      "Urine output of 380 mL/hr with a specific gravity of 1.002 and rising serum sodium",
      "Complaints of a mild frontal headache relieved by acetaminophen",
      "Nasal packing that is dry and intact with no drainage"
    ],
    "answer": 1,
    "rationale": "Massive dilute diuresis with a very low specific gravity and rising serum sodium indicates central diabetes insipidus from disrupted ADH secretion, which can rapidly cause hypovolemia and hypernatremia and requires desmopressin. A urine output of 60 mL/hr with a mid-range specific gravity is a normal expected finding and needs only continued monitoring.",
    "why": [
      "Sixty milliliters per hour with a specific gravity of 1.018 is normal output and concentration, requiring routine monitoring rather than immediate reporting.",
      "Massive dilute diuresis with a rising serum sodium indicates central diabetes insipidus after pituitary surgery, risking rapid hypovolemia and requiring desmopressin.",
      "A mild frontal headache relieved by acetaminophen is expected after this approach; severe headache with a stiff neck would instead suggest a leak.",
      "Dry, intact nasal packing is the desired finding; clear drainage or persistent postnasal drip would be the concerning sign of a CSF leak."
    ]
  },
  {
    "id": "EN-010",
    "stem": "An 82-year-old nursing home resident with type 2 diabetes has a blood glucose of 792 mg/dL, serum osmolality of 340 mOsm/kg, negative serum ketones, and is difficult to arouse. Which nursing action takes priority?",
    "options": [
      "Establishing IV access and initiating 0.9% sodium chloride as prescribed",
      "Obtaining a urine specimen for culture and sensitivity",
      "Teaching the family about sick-day management rules",
      "Administering the client's usual oral metformin dose"
    ],
    "answer": 0,
    "rationale": "Hyperglycemic hyperosmolar state produces extreme dehydration with fluid deficits that may exceed 8 to 10 L, so restoring intravascular volume is the priority intervention before other measures. Metformin is contraindicated in an acutely dehydrated, hyperosmolar client because of the risk of lactic acidosis and would not address the volume deficit.",
    "why": [
      "Hyperglycemic hyperosmolar state creates fluid deficits that can exceed 8 liters, so IV access and isotonic fluid resuscitation are the priority.",
      "A urine culture may identify the precipitating infection, but obtaining it does not treat the profound dehydration currently threatening tissue perfusion.",
      "Sick-day teaching helps prevent recurrence but is inappropriate while the resident is difficult to arouse and hemodynamically unstable from severe dehydration.",
      "Metformin is contraindicated in acute dehydration because of lactic acidosis risk, and an oral drug is unsafe in a barely arousable client."
    ]
  }
];

export default questions;
