/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "FN-001",
    "stem": "The nurse observes a nursing student preparing a sterile dressing change. Which action by the student requires the nurse to intervene?",
    "options": [
      "The student opens the outermost flap of the sterile package away from the body first",
      "The student turns away from the sterile field to answer a coworker's question and then resumes the procedure",
      "The student holds sterile supplies above waist level and in front of the body",
      "The student pours sterile solution into a basin without touching the container to the basin rim"
    ],
    "answer": 1,
    "rationale": "A sterile field is considered contaminated whenever it is out of the practitioner's direct line of vision, so turning away requires setting up a new field. The other three actions are correct technique: the far flap is opened first, sterility is maintained above waist level and within view, and the solution container must not contact the receptacle.",
    "why": [
      "Opening the outermost flap away from the body first is correct technique and avoids reaching across the sterile field.",
      "A sterile field is considered contaminated whenever it leaves the practitioner's direct line of vision, so a new field is required.",
      "Holding sterile supplies above waist level and in front of the body maintains sterility and requires no intervention.",
      "Pouring solution without touching the container to the basin rim prevents contamination of the container edge and is proper technique."
    ]
  },
  {
    "id": "FN-002",
    "stem": "The nurse assesses a sacral wound with full-thickness skin loss in which subcutaneous fat is visible. There is no slough or eschar obscuring the wound base, and no muscle, tendon, or bone is exposed. How should the nurse stage this pressure injury?",
    "options": [
      "Stage 1",
      "Stage 2",
      "Deep tissue pressure injury",
      "Stage 3"
    ],
    "answer": 3,
    "rationale": "Full-thickness loss with visible adipose tissue but no exposed muscle, tendon, or bone defines a stage 3 pressure injury. Stage 2 is partial thickness with a shiny or moist red-pink wound bed and no visible fat, so it would understage this wound and lead to an inadequate plan of care.",
    "why": [
      "Stage 1 describes intact skin with nonblanchable erythema, which badly understages a wound with full-thickness tissue loss.",
      "Stage 2 is partial thickness with a shiny, moist red-pink bed and no visible fat, so it does not fit exposed adipose tissue.",
      "Deep tissue pressure injury presents as intact or blistered skin with persistent deep purple discoloration, not an open wound with visible fat.",
      "Full-thickness loss with visible subcutaneous fat and no exposed muscle, tendon, or bone defines a stage 3 pressure injury."
    ]
  },
  {
    "id": "FN-003",
    "stem": "A client has a nasogastric tube whose placement was confirmed by x-ray on insertion yesterday. Before administering an intermittent tube feeding, which method should the nurse use to verify tube placement?",
    "options": [
      "Aspirate gastric contents and test the pH of the aspirate",
      "Inject 30 mL of air into the tube while auscultating over the epigastrium",
      "Place the end of the tube in a cup of water and observe for bubbling",
      "Ask the client to speak and listen for hoarseness"
    ],
    "answer": 0,
    "rationale": "Aspirating fluid and checking for an acidic pH (about 5.5 or less) is the recommended bedside verification method between x-ray confirmations. The air-bolus auscultation method is unreliable because the whooshing sound transmits even when the tube is in the lung or esophagus, creating a serious aspiration risk.",
    "why": [
      "Aspirating gastric contents and finding an acidic pH of about 5.5 or less is the recommended bedside check between x-rays.",
      "The air-bolus auscultation method is unreliable because the whooshing sound transmits even when the tube sits in the lung or esophagus.",
      "The water bubbling test is outdated and unsafe, risks aspiration of water, and does not confirm gastric placement.",
      "Many clients speak normally with a misplaced feeding tube, so voice quality cannot rule out tracheal or esophageal placement."
    ]
  },
  {
    "id": "FN-004",
    "stem": "The nurse is reviewing indwelling urinary catheter care performed by a new staff member. Which observation requires the nurse to intervene?",
    "options": [
      "The drainage bag is emptied every 8 hours using a separate graduated container for each client",
      "The catheter tubing is secured to the client's thigh",
      "The drainage bag is hung on the movable side rail of the bed",
      "Perineal care is performed with soap and water once daily and after bowel movements"
    ],
    "answer": 2,
    "rationale": "Hanging the bag on a movable side rail can raise it above bladder level and cause reflux of contaminated urine, and the bag may be dislodged when the rail moves; it must hang below the bladder on a fixed part of the frame and off the floor. The other actions correctly prevent catheter-associated urinary tract infection and traction on the urethra.",
    "why": [
      "Emptying every 8 hours using a separate graduated container for each client prevents cross-contamination and is correct practice.",
      "Securing the catheter tubing to the thigh prevents traction on the urethra and is a recommended catheter-care measure.",
      "A bag on a movable rail can rise above bladder level and cause reflux of contaminated urine or be dislodged when the rail moves.",
      "Daily perineal care with soap and water plus cleansing after bowel movements is the correct hygiene standard for indwelling catheters."
    ]
  },
  {
    "id": "FN-005",
    "stem": "The nurse obtains a blood pressure of 168/94 mm Hg in an obese client using a standard adult cuff that appears tight around the upper arm. Which action should the nurse take next?",
    "options": [
      "Report the elevated reading to the provider immediately",
      "Reassess the blood pressure with a large adult cuff, because a cuff that is too small produces a falsely high reading",
      "Document the reading and recheck it in 4 hours",
      "Repeat the measurement in the thigh using the same cuff"
    ],
    "answer": 1,
    "rationale": "An undersized cuff requires more pressure to occlude the artery and falsely elevates the reading, so the nurse must obtain accurate data with a correctly sized cuff before acting. Reporting or documenting an invalid measurement violates the assessment step of the nursing process and could lead to unnecessary treatment.",
    "why": [
      "Reporting a reading taken with an undersized cuff means acting on invalid data and could prompt unnecessary antihypertensive treatment.",
      "A cuff that is too small requires more pressure to occlude the artery and falsely elevates readings, so accurate data must come first.",
      "Documenting an invalid measurement and waiting four hours records inaccurate data and delays discovery of the true blood pressure.",
      "Reusing the same too-small cuff on the thigh repeats the sizing error, and thigh readings normally differ from arm readings anyway."
    ]
  },
  {
    "id": "FN-006",
    "stem": "A client with right-sided pneumonia has an oxygen saturation of 90% on 2 L/min by nasal cannula. Which position should the nurse use to best improve oxygenation?",
    "options": [
      "Left lateral position, with the unaffected lung dependent",
      "Right lateral position, with the affected lung dependent",
      "Prone with the head of the bed flat",
      "Trendelenburg position"
    ],
    "answer": 0,
    "rationale": "In unilateral lung disease, placing the good lung down directs gravity-dependent blood flow to well-ventilated alveoli and improves ventilation-perfusion matching. Lying on the affected side perfuses consolidated lung that cannot participate in gas exchange and worsens shunting and hypoxemia.",
    "why": [
      "Placing the unaffected left lung dependent directs gravity-dependent blood flow to well-ventilated alveoli and improves ventilation-perfusion matching.",
      "Lying on the affected right side perfuses consolidated lung that cannot exchange gas, worsening shunting and hypoxemia.",
      "Prone with the bed flat is a severe ARDS strategy, not routine unilateral pneumonia, and flat positioning limits diaphragmatic excursion.",
      "Trendelenburg pushes abdominal contents against the diaphragm, reducing lung expansion and lowering oxygenation further."
    ]
  },
  {
    "id": "FN-007",
    "stem": "A client refuses a scheduled dose of metoprolol, stating it makes him feel tired. Which action best reflects appropriate documentation and follow-up?",
    "options": [
      "Chart that the client was uncooperative and refused his medications",
      "Have a family member sign a refusal form before charting the event",
      "Hold the medication and document the omission at the end of the shift",
      "Document the refusal in the client's own words with the reason given, the teaching provided, and notification of the provider"
    ],
    "answer": 3,
    "rationale": "Documentation must be objective, timely, and factual, and the provider must be notified so the regimen can be reevaluated; quoting the client preserves accuracy. Labeling the client \"uncooperative\" is a subjective judgment, and delaying charting until the end of the shift breaks the requirement for contemporaneous documentation.",
    "why": [
      "Charting that the client was uncooperative is a subjective judgment rather than objective fact and is inappropriate documentation.",
      "A competent adult may refuse medication without a family signature, so this delays charting and disregards the client's autonomy.",
      "Holding the drug is correct, but charting at shift end violates contemporaneous documentation requirements and omits provider notification entirely.",
      "Quoting the client, recording the reason and teaching, and notifying the provider is objective, timely, and allows the regimen to be reevaluated."
    ]
  },
  {
    "id": "FN-008",
    "stem": "The nurse teaches a client how to collect a midstream clean-catch urine specimen for culture. Which statement indicates that the client understands the instructions?",
    "options": [
      "I will catch the very first part of my urine stream in the cup.",
      "I will cleanse myself by wiping from back to front before I start.",
      "I will begin urinating into the toilet, then move the cup into the stream to catch the middle portion.",
      "I can leave the covered cup on the bathroom counter until the nurse picks it up at the end of the shift."
    ],
    "answer": 2,
    "rationale": "Discarding the initial stream flushes urethral flora so the midstream portion reflects bladder urine, which is essential for an accurate culture. Collecting the first portion or wiping back to front introduces contaminating organisms, and specimens left at room temperature allow bacterial overgrowth and false results.",
    "why": [
      "The first portion of the stream carries urethral flora and would contaminate the culture with organisms not from the bladder.",
      "Wiping from back to front drags perineal and rectal bacteria toward the urethra and contaminates the specimen.",
      "Voiding first into the toilet flushes urethral flora so the midstream portion reflects true bladder urine for an accurate culture.",
      "Urine left at room temperature for hours allows bacterial overgrowth and falsely elevated colony counts, so it must be delivered or refrigerated promptly."
    ]
  },
  {
    "id": "FN-009",
    "stem": "A client is admitted with a 4-week history of cough, night sweats, and weight loss, and pulmonary tuberculosis is suspected. Which action should the nurse take before entering the client's room?",
    "options": [
      "Place the client in a negative-pressure airborne infection isolation room and don a fit-tested N95 respirator",
      "Apply a surgical mask and gown before entering the room",
      "Place the client in a private room and initiate contact precautions",
      "Wear gloves and a face shield only"
    ],
    "answer": 0,
    "rationale": "Tuberculosis is transmitted by droplet nuclei that remain suspended in air, so airborne precautions with a negative-pressure room and an N95 respirator are required. A surgical mask does not filter droplet nuclei and contact precautions address a different transmission route, leaving the nurse and other clients unprotected.",
    "why": [
      "Tuberculosis spreads by droplet nuclei that stay suspended in air, requiring a negative-pressure room and a fit-tested N95 respirator.",
      "A surgical mask does not filter droplet nuclei and a gown targets contact spread, leaving the nurse unprotected from airborne transmission.",
      "A plain private room lacks negative pressure, and contact precautions address a transmission route different from that of tuberculosis.",
      "Gloves and a face shield guard against splash and contact exposure but provide no respiratory filtration against airborne bacilli."
    ]
  },
  {
    "id": "FN-010",
    "stem": "The nurse must reposition a 90 kg (198 lb) client up in bed. Which action demonstrates correct body mechanics and safe client handling?",
    "options": [
      "Bending forward at the waist and pulling the client toward the head of the bed",
      "Keeping the feet close together to maintain a narrow base of support",
      "Raising the bed to waist level, widening the stance, and using a friction-reducing draw sheet with a second staff member",
      "Twisting at the waist while moving the client toward the bedside chair"
    ],
    "answer": 2,
    "rationale": "Working at waist height with a wide base of support, using leg muscles, and getting assistance with a friction-reducing device protects both the nurse and the client's skin. Bending at the waist or twisting the spine places shearing stress on the lumbar discs and is a leading cause of back injury in nursing.",
    "why": [
      "Bending forward at the waist and pulling loads the lumbar spine and is a leading cause of back injury among nurses.",
      "Keeping the feet close together narrows the base of support and reduces stability when moving a 90 kg client.",
      "Waist-height bed, a wide stance, and a friction-reducing draw sheet with a second staff member protect the nurse's back and the client's skin.",
      "Twisting at the waist while bearing weight places shearing stress on lumbar discs; the nurse should pivot the feet instead."
    ]
  }
];

export default questions;
