/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "GI-001",
    "stem": "A client with a history of esophageal varices vomits approximately 500 mL of bright red blood. Blood pressure is 86/48, heart rate 126, and skin is cool and clammy. Which action should the nurse take first?",
    "options": [
      "Obtain a stool specimen for occult blood testing",
      "Insert a nasogastric tube for gastric lavage",
      "Position the client supine with the legs elevated on pillows",
      "Establish large-bore IV access and begin the prescribed isotonic fluid bolus"
    ],
    "answer": 3,
    "rationale": "Active hematemesis with hypotension and tachycardia signals hypovolemic shock, and rapid volume replacement through large-bore IV access is the priority circulation intervention. Stool occult blood testing confirms bleeding that is already obvious and does nothing to restore perfusion, so it is a low priority in an unstable client.",
    "why": [
      "Occult blood testing confirms bleeding that is already obvious as hematemesis and does nothing to restore perfusion in a hypotensive client.",
      "Gastric lavage may be ordered later, but it is not the first action and can further traumatize fragile varices before volume is restored.",
      "Supine leg elevation gives only transient venous return and raises aspiration risk in a client actively vomiting blood, so it cannot replace fluid resuscitation.",
      "Hematemesis with hypotension and tachycardia signals hypovolemic shock, so large-bore access with isotonic fluid resuscitation addresses the circulation priority."
    ]
  },
  {
    "id": "GI-002",
    "stem": "A client with cirrhosis has an ammonia level of 92 mcg/dL, asterixis, and increasing confusion. The provider prescribes lactulose. Which finding indicates the medication is achieving its therapeutic effect?",
    "options": [
      "The client reports relief of abdominal fullness",
      "The client has two to three soft stools daily and is more oriented",
      "The client's abdominal girth decreases by 3 cm",
      "The client's serum albumin rises to 3.8 g/dL"
    ],
    "answer": 1,
    "rationale": "Lactulose acidifies the colon to trap ammonia and works as an osmotic laxative, so two to three soft stools per day with improving mentation shows effectiveness. A decrease in abdominal girth reflects diuretic response or paracentesis for ascites, not ammonia clearance, so it is not the intended endpoint for this drug.",
    "why": [
      "Relief of abdominal fullness is nonspecific comfort and does not demonstrate ammonia clearance or improvement in hepatic encephalopathy.",
      "Lactulose acidifies the colon to trap ammonia and acts osmotically, so two to three soft stools with clearing mentation confirm effectiveness.",
      "A decrease in abdominal girth reflects diuretic response or paracentesis for ascites rather than the ammonia-lowering action of lactulose.",
      "Serum albumin reflects hepatic synthetic function and improves slowly with nutrition; lactulose has no direct effect on the albumin level."
    ]
  },
  {
    "id": "GI-003",
    "stem": "A client is diagnosed with hepatitis A after a restaurant outbreak. Which statement by the client indicates correct understanding of transmission?",
    "options": [
      "I got this from sharing needles with someone",
      "My spouse needs testing because we shared razors",
      "I most likely picked this up from contaminated food or water",
      "This will probably become a lifelong chronic liver infection"
    ],
    "answer": 2,
    "rationale": "Hepatitis A is spread by the fecal-oral route through contaminated food, water, or hands, and meticulous handwashing is the key preventive measure. Needle sharing and shared razors transmit bloodborne hepatitis B and C, which is a different route and a different chronicity profile, since hepatitis A does not become chronic.",
    "why": [
      "Needle sharing transmits bloodborne hepatitis B and C, not hepatitis A, so this statement misidentifies the route in a foodborne outbreak.",
      "Shared razors transmit bloodborne hepatitis; household contacts of hepatitis A are protected by handwashing and postexposure vaccine or immune globulin instead.",
      "Hepatitis A spreads by the fecal-oral route through contaminated food, water, or hands, which fits this restaurant-associated outbreak exactly.",
      "Hepatitis A is a self-limiting acute illness that does not become chronic; hepatitis B and C carry the chronic carrier risk."
    ]
  },
  {
    "id": "GI-004",
    "stem": "A client admitted with acute pancreatitis reports severe epigastric pain radiating to the back, with a serum lipase of 1,120 units/L. Which nursing intervention is most appropriate?",
    "options": [
      "Maintain NPO status and assist the client into a side-lying position with knees flexed",
      "Provide a high-fat, high-calorie diet to meet metabolic demands",
      "Place the client flat in bed to reduce diaphragmatic irritation",
      "Apply heat to the abdomen for 20 minutes every hour"
    ],
    "answer": 0,
    "rationale": "Resting the gut with NPO status reduces pancreatic enzyme stimulation, and a knee-flexed side-lying or fetal position decreases tension on the inflamed pancreas and eases pain. A high-fat diet is the opposite of what is indicated because fat is the strongest stimulus for pancreatic secretion and will intensify pain.",
    "why": [
      "NPO status rests the pancreas by limiting enzyme stimulation, and a side-lying knee-flexed position reduces tension on the inflamed gland.",
      "Fat is the strongest stimulus for pancreatic enzyme secretion, so a high-fat diet would intensify autodigestion and severely worsen the epigastric pain.",
      "Lying flat increases pressure on the inflamed pancreas and typically worsens pain; a flexed or upright position provides considerably more relief.",
      "Heat increases blood flow and metabolic demand at an acutely inflamed site, so it is not indicated and may intensify pancreatic inflammation."
    ]
  },
  {
    "id": "GI-005",
    "stem": "A client recovering from an episode of acute cholecystitis is being discharged. Which meal selection indicates the client understands the recommended diet?",
    "options": [
      "Fried chicken, coleslaw with mayonnaise, and whole milk",
      "Baked cod, steamed rice, green beans, and skim milk",
      "Cheeseburger with french fries and a chocolate milkshake",
      "Sausage omelet with buttered toast and cream-based soup"
    ],
    "answer": 1,
    "rationale": "A low-fat meal minimizes cholecystokinin release and gallbladder contraction, which reduces the biliary colic that follows fatty meals. The fried chicken selection is high in fat and would trigger gallbladder stimulation and pain, so it demonstrates a misunderstanding of the dietary restriction.",
    "why": [
      "Fried chicken, mayonnaise-based slaw, and whole milk are high in fat and would trigger gallbladder contraction with recurrent biliary colic.",
      "Baked fish, rice, vegetables, and skim milk are low in fat, minimizing cholecystokinin release and the pain that follows fatty meals.",
      "A cheeseburger, fries, and a milkshake are among the highest-fat selections available and would predictably provoke a painful biliary attack.",
      "Sausage, buttered toast, and cream-based soup are all high in fat, so this choice shows the dietary restriction was not understood."
    ]
  },
  {
    "id": "GI-006",
    "stem": "A client with a known duodenal ulcer suddenly develops severe, unrelenting abdominal pain; the abdomen is rigid and board-like, and bowel sounds are absent. Which action should the nurse take?",
    "options": [
      "Administer the prescribed antacid and reassess in 1 hour",
      "Offer small sips of milk to coat the gastric lining",
      "Assist the client to ambulate to relieve trapped gas",
      "Keep the client NPO, notify the provider immediately, and prepare for emergency surgery"
    ],
    "answer": 3,
    "rationale": "A rigid board-like abdomen with absent bowel sounds after ulcer disease indicates perforation with peritonitis, a surgical emergency requiring immediate provider notification and NPO status. Giving an antacid or milk delays definitive care and introduces oral intake into an abdomen that will likely require urgent operative repair.",
    "why": [
      "An antacid cannot treat perforation, and reassessing in an hour delays surgical care while peritonitis and sepsis rapidly progress.",
      "Milk gives oral intake to a client who will likely need emergency surgery and only briefly buffers acid before stimulating rebound secretion.",
      "This pain is peritoneal irritation from perforation rather than trapped gas, and ambulating a client with an acute abdomen delays needed surgery.",
      "Board-like rigidity with absent bowel sounds indicates perforation with peritonitis, a surgical emergency requiring NPO status and immediate provider notification."
    ]
  },
  {
    "id": "GI-007",
    "stem": "A client with ulcerative colitis reports 14 bloody stools per day, a temperature of 101.8 F, heart rate 118, and marked abdominal distention with tenderness. Which complication should the nurse suspect?",
    "options": [
      "Toxic megacolon",
      "Irritable bowel syndrome flare",
      "Lactose intolerance",
      "Hemorrhoidal bleeding"
    ],
    "answer": 0,
    "rationale": "Fever, tachycardia, abdominal distention, and profuse bloody diarrhea in ulcerative colitis point to toxic megacolon, which risks perforation and sepsis and requires urgent evaluation. Irritable bowel syndrome does not produce fever, systemic toxicity, or bloody stools, so it cannot account for this presentation.",
    "why": [
      "Fever, tachycardia, distention, and profuse bloody diarrhea in ulcerative colitis indicate toxic megacolon, which risks perforation and sepsis.",
      "Irritable bowel syndrome causes cramping and altered stool patterns but never fever, systemic toxicity, or grossly bloody stools like these.",
      "Lactose intolerance produces bloating, gas, and osmotic diarrhea after dairy intake, not fever, tachycardia, and fourteen bloody stools daily.",
      "Hemorrhoids can add bright red blood on the stool surface but cannot explain fever, tachycardia, and marked abdominal distention with tenderness."
    ]
  },
  {
    "id": "GI-008",
    "stem": "A client with a small bowel obstruction has a nasogastric tube connected to low intermittent suction. The nurse notes the client has no drainage for 2 hours and reports increasing nausea. Which action should the nurse take first?",
    "options": [
      "Advance the tube 5 cm and resecure it",
      "Administer the prescribed antiemetic",
      "Assess the tube for kinks and verify placement and suction settings",
      "Remove the tube and notify the provider"
    ],
    "answer": 2,
    "rationale": "Assessment precedes intervention in the nursing process, so the nurse first checks for mechanical causes such as kinking, disconnection, or an incorrect suction setting before doing anything else. Advancing or removing the tube without assessment risks misplacement or loss of a needed decompression route while the actual problem may be a simple kink.",
    "why": [
      "Advancing the tube blindly before assessment risks coiling or misplacement and may not resolve a simple kink or an incorrect suction setting.",
      "An antiemetic masks the nausea produced by a nonfunctioning tube, treating the symptom while gastric and intestinal contents continue to accumulate.",
      "Assessment precedes intervention, so checking for kinks, verifying placement, and confirming suction settings identifies the most likely mechanical cause first.",
      "Removing the tube eliminates needed decompression in bowel obstruction and is premature when the cause may be a correctable kink or setting."
    ]
  },
  {
    "id": "GI-009",
    "stem": "The nurse is teaching a client with a new sigmoid colostomy about pouch care. Which statement by the client indicates correct understanding?",
    "options": [
      "I should cut the barrier opening about one-eighth inch larger than my stoma",
      "A dusky purple stoma is normal for the first few weeks",
      "I should empty the pouch only when it is completely full",
      "I will irrigate the stoma daily with hot tap water"
    ],
    "answer": 0,
    "rationale": "Sizing the barrier about one-eighth inch larger than the stoma protects peristomal skin from effluent while avoiding pressure on the stoma itself. A dusky or purple stoma indicates impaired circulation and must be reported immediately, so accepting it as normal is a dangerous misconception.",
    "why": [
      "Cutting the barrier about one-eighth inch larger than the stoma shields peristomal skin from effluent without constricting the stoma itself.",
      "A dusky purple stoma signals impaired circulation and must be reported immediately; a healthy stoma remains pink or beefy red and moist.",
      "Waiting until the pouch is completely full strains the seal and causes leaks, so it is emptied when one-third to one-half full.",
      "Sigmoid colostomy irrigation uses lukewarm water when prescribed; hot tap water can burn the delicate stomal mucosa, making this statement unsafe."
    ]
  },
  {
    "id": "GI-010",
    "stem": "A client with gastroesophageal reflux disease reports nighttime heartburn and a sour taste on waking. Which instruction should the nurse provide?",
    "options": [
      "Lie down for 30 minutes after eating to aid digestion",
      "Avoid eating within 3 hours of bedtime and elevate the head of the bed 6 to 8 inches",
      "Drink a cup of peppermint tea before bed to relax the stomach",
      "Sleep flat with two pillows under the knees"
    ],
    "answer": 1,
    "rationale": "Avoiding late meals and using gravity by elevating the head of the bed reduces nocturnal reflux of gastric contents into the esophagus. Peppermint relaxes the lower esophageal sphincter and actually worsens reflux, so recommending it would increase the client's symptoms.",
    "why": [
      "Lying down after eating lets gastric contents move against a weakened sphincter; clients should remain upright two to three hours after meals.",
      "Avoiding food within three hours of bedtime and elevating the head of the bed uses gravity to prevent nocturnal reflux.",
      "Peppermint relaxes the lower esophageal sphincter and increases reflux, so a bedtime cup would intensify this client's nighttime heartburn.",
      "Pillows under the knees do not raise the esophagus above the stomach, so lying flat still permits gastric contents to reflux."
    ]
  }
];

export default questions;
