/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "HP-001",
    "stem": "A parent brings a healthy 2-month-old infant to the clinic. Which immunizations should the nurse anticipate administering at this visit?",
    "options": [
      "Rotavirus, DTaP, Haemophilus influenzae type b, pneumococcal conjugate, and inactivated poliovirus",
      "Measles-mumps-rubella and varicella",
      "Tetanus-diphtheria booster and meningococcal conjugate",
      "Human papillomavirus series and hepatitis A"
    ],
    "answer": 0,
    "rationale": "At 2 months the recommended schedule includes rotavirus, DTaP, Hib, pneumococcal conjugate, and IPV, along with the second hepatitis B dose. MMR and varicella are live vaccines not given until 12 to 15 months, and Td, meningococcal, and HPV are adolescent vaccines.",
    "why": [
      "The two-month schedule includes rotavirus, DTaP, Hib, pneumococcal conjugate, and inactivated poliovirus, along with the second hepatitis B dose.",
      "MMR and varicella are live vaccines withheld until 12 to 15 months, when maternal antibody has waned enough for response.",
      "Td boosters and meningococcal conjugate vaccine are adolescent immunizations and have no place in a two-month-old's schedule.",
      "HPV vaccination begins in adolescence and hepatitis A at 12 months, so neither is due at this two-month visit."
    ]
  },
  {
    "id": "HP-002",
    "stem": "The nurse is assessing a 12-month-old at a well-child visit. Which finding should prompt further developmental evaluation?",
    "options": [
      "Says two or three words besides mama and dada",
      "Pulls to a stand and cruises along furniture",
      "Uses a crude pincer grasp to pick up small pieces of cereal",
      "Has not yet developed head control when pulled to sitting"
    ],
    "answer": 3,
    "rationale": "Head control is normally achieved by about 4 months, so its absence at 12 months is a significant red flag requiring referral. Speaking a few words, cruising, and a pincer grasp are all expected 12-month milestones and need no further workup.",
    "why": [
      "Saying two or three words besides mama and dada is an expected 12-month language milestone requiring no further evaluation.",
      "Pulling to a stand and cruising along furniture are normal gross motor achievements for a 12-month-old.",
      "A crude pincer grasp for picking up cereal is precisely the fine motor skill expected at 12 months.",
      "Head control normally appears by about four months, so its absence at 12 months is a major red flag warranting referral."
    ]
  },
  {
    "id": "HP-003",
    "stem": "A client at 28 weeks' gestation asks about her upcoming prenatal testing. Which screening should the nurse tell her to expect at this visit?",
    "options": [
      "Group B streptococcus vaginal and rectal culture",
      "One-hour 50-gram glucose challenge test and repeat hemoglobin",
      "Nuchal translucency ultrasound",
      "Amniocentesis for fetal lung maturity"
    ],
    "answer": 1,
    "rationale": "Gestational diabetes screening with the 50-gram glucose challenge and a repeat hemoglobin are standard between 24 and 28 weeks. Group B streptococcus culture is done at 36 to 37 weeks and nuchal translucency is a first-trimester screen, so neither belongs at 28 weeks.",
    "why": [
      "Group B streptococcus culture is collected at 36 to 37 weeks to guide intrapartum prophylaxis, so it is not due now.",
      "The one-hour 50-gram glucose challenge and a repeat hemoglobin are routinely performed between 24 and 28 weeks' gestation.",
      "Nuchal translucency ultrasound is a first-trimester screen done around 11 to 14 weeks and cannot be performed at 28 weeks.",
      "Amniocentesis for fetal lung maturity is used only when preterm delivery is being considered, never as routine prenatal screening."
    ]
  },
  {
    "id": "HP-004",
    "stem": "On the third postpartum day after a vaginal birth, the nurse assesses a client's lochia. Which finding should the nurse report to the provider?",
    "options": [
      "Pinkish-brown discharge with a fleshy odor",
      "Small clots noted on the perineal pad on rising in the morning",
      "Saturation of one perineal pad within 15 minutes with bright red blood",
      "A firm fundus located two fingerbreadths below the umbilicus"
    ],
    "answer": 2,
    "rationale": "Saturating a pad in 15 minutes with bright red bleeding indicates postpartum hemorrhage and requires immediate provider notification and fundal assessment. Lochia serosa, small clots after lying down, and an involuting firm fundus are all expected findings on postpartum day 3.",
    "why": [
      "Pinkish-brown lochia serosa with a fleshy odor is the expected discharge on the third postpartum day.",
      "Small clots on the pad after lying still overnight reflect normal pooling and do not alone indicate hemorrhage.",
      "Saturating a perineal pad within 15 minutes with bright red blood signals postpartum hemorrhage requiring immediate fundal assessment and provider notification.",
      "A firm fundus two fingerbreadths below the umbilicus demonstrates normal involution on postpartum day three."
    ]
  },
  {
    "id": "HP-005",
    "stem": "A 52-year-old client with no family history of cancer asks the nurse which routine screenings are recommended. Which response is most accurate?",
    "options": [
      "\"Colorectal cancer screening should start at age 65 for average-risk adults.\"",
      "\"You should have a prostate-specific antigen test every 6 months starting now.\"",
      "\"Annual chest x-rays are recommended for all adults over 50.\"",
      "\"Average-risk adults should begin colorectal cancer screening at age 45, and mammography is recommended for women in your age group.\""
    ],
    "answer": 3,
    "rationale": "Current guidelines lower the start of average-risk colorectal cancer screening to age 45, and mammography is recommended for women in the 40s to 50s age range. Routine annual chest x-rays are not a recommended screening test, and semiannual PSA testing is not the standard for average-risk clients.",
    "why": [
      "Average-risk colorectal screening now begins at 45, so telling this 52-year-old to wait until 65 dangerously delays detection.",
      "Semiannual PSA testing is not the standard for average-risk clients; prostate screening is a shared decision made no more often than annually.",
      "Routine annual chest x-rays are not a recommended screening test and expose clients to radiation without proven benefit.",
      "Average-risk colorectal cancer screening starts at age 45, and mammography is recommended for women in this client's age group."
    ]
  },
  {
    "id": "HP-006",
    "stem": "The nurse is teaching a group of older adults about normal age-related changes. Which statement by a participant indicates a finding that is NOT a normal part of aging and requires follow-up?",
    "options": [
      "\"I have become confused and disoriented over the past two days.\"",
      "\"It takes me longer to fall asleep than it used to.\"",
      "\"I need reading glasses for small print now.\"",
      "\"My skin seems drier and less elastic than when I was younger.\""
    ],
    "answer": 0,
    "rationale": "Acute confusion over days suggests delirium from an underlying cause such as infection, dehydration, or medication and always warrants prompt evaluation. Longer sleep latency, presbyopia, and decreased skin turgor and moisture are expected physiologic changes of aging.",
    "why": [
      "Confusion and disorientation developing over two days suggest delirium from infection, dehydration, or medication and require prompt evaluation.",
      "Taking longer to fall asleep is a well-documented normal change in the aging sleep cycle and needs no workup.",
      "Needing reading glasses for small print reflects presbyopia, the expected age-related loss of lens accommodation.",
      "Drier, less elastic skin results from normal age-related declines in sebum production and dermal collagen."
    ]
  },
  {
    "id": "HP-007",
    "stem": "A school nurse is screening adolescents for idiopathic scoliosis. Which assessment technique is correct?",
    "options": [
      "Measure the standing height and compare it with growth charts",
      "Have the student stand on one leg while the nurse palpates the hips",
      "Ask the student to bend forward at the waist with arms hanging and observe for rib hump and shoulder asymmetry",
      "Have the student walk on the toes and heels while the nurse observes gait"
    ],
    "answer": 2,
    "rationale": "The Adams forward bend test reveals the rib prominence and asymmetry of the shoulders, scapulae, and waist that characterize scoliosis. Height measurement and gait testing do not detect lateral spinal curvature and are not the recognized screening technique.",
    "why": [
      "Comparing standing height with growth charts screens for growth disorders and cannot reveal lateral curvature of the spine.",
      "Single-leg stance with hip palpation assesses hip stability and leg length, not the spinal rotation that defines scoliosis.",
      "The Adams forward bend test exposes the rib hump and shoulder, scapular, and waist asymmetry characteristic of idiopathic scoliosis.",
      "Toe and heel walking evaluates neurologic function and gait, which is unrelated to screening for scoliosis."
    ]
  },
  {
    "id": "HP-008",
    "stem": "A 49-year-old client reports hot flashes, irregular menses, and vaginal dryness. Which self-care measure should the nurse recommend?",
    "options": [
      "Increase caffeine intake to combat fatigue",
      "Dress in layers, use a water-soluble lubricant, and perform weight-bearing exercise with adequate calcium and vitamin D",
      "Discontinue all contraception immediately since pregnancy is no longer possible",
      "Restrict fluids in the evening to reduce night sweats"
    ],
    "answer": 1,
    "rationale": "Perimenopausal self-care emphasizes layered clothing for vasomotor symptoms, water-soluble lubricants for atrophic changes, and weight-bearing exercise with calcium and vitamin D for bone health. Caffeine tends to worsen hot flashes, and ovulation may still occur during perimenopause so contraception is still needed.",
    "why": [
      "Caffeine is a vasomotor trigger that typically worsens hot flashes and further disrupts sleep during perimenopause.",
      "Layered clothing, water-soluble lubricant, and weight-bearing exercise with calcium and vitamin D address vasomotor, atrophic, and bone changes together.",
      "Ovulation can still occur irregularly during perimenopause, so stopping contraception now risks an unintended pregnancy.",
      "Restricting evening fluids does not affect vasomotor night sweats and can leave this client dehydrated."
    ]
  },
  {
    "id": "HP-009",
    "stem": "A new parent asks the nurse about safe sleep for a healthy 3-week-old newborn. Which statement indicates the teaching was effective?",
    "options": [
      "\"I will place my baby on the back to sleep on a firm mattress with no blankets, bumper pads, or stuffed toys.\"",
      "\"I will put my baby to sleep on the stomach so she doesn't choke if she spits up.\"",
      "\"I will let my baby sleep in bed with us so I can nurse more easily at night.\"",
      "\"I will prop my baby on her side with a rolled blanket behind her back.\""
    ],
    "answer": 0,
    "rationale": "Supine positioning on a firm, bare sleep surface in the parents' room but not in their bed is the evidence-based standard for reducing sudden infant death syndrome. Prone and side positioning and bed sharing with soft bedding all significantly increase SIDS and suffocation risk.",
    "why": [
      "Supine sleep on a firm, bare surface without blankets, bumper pads, or toys is the evidence-based standard for reducing SIDS.",
      "Prone positioning markedly raises SIDS risk, and healthy infants protect their own airway when spitting up on the back.",
      "Bed sharing with adults and soft bedding significantly increases suffocation and SIDS risk; room sharing without bed sharing is advised.",
      "Side positioning is unstable and the infant can roll prone, and the rolled blanket itself is a suffocation hazard."
    ]
  },
  {
    "id": "HP-010",
    "stem": "A client with a body mass index of 31 kg/m2 and a sedentary job tells the nurse, \"I want to get healthier but I have no time to exercise.\" Which response by the nurse best supports lifestyle change?",
    "options": [
      "\"You should join a gym and work out for an hour each day.\"",
      "\"If you don't lose weight now, you will likely develop diabetes.\"",
      "\"Let's look at your week together and find two or three realistic 10-minute activity blocks to start with.\"",
      "\"Most people in your situation are unable to change without medication.\""
    ],
    "answer": 2,
    "rationale": "Collaborating with the client to set small, achievable goals reflects health promotion principles and increases self-efficacy and adherence. Prescriptive demands and fear-based warnings tend to increase resistance and do not address the barrier the client actually identified.",
    "why": [
      "Prescribing an hour of daily gym time ignores the exact barrier the client named and sets an unrealistic starting goal.",
      "A fear-based warning about diabetes tends to increase defensiveness and still does not solve the client's time problem.",
      "Collaboratively finding two or three realistic ten-minute activity blocks addresses the stated barrier and builds the self-efficacy that sustains change.",
      "Telling the client that most people cannot change without medication is inaccurate and undermines motivation and confidence."
    ]
  }
];

export default questions;
