/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

/* One dynamic import per topic so a visitor downloads the set they clicked
   and not the other nineteen. */
export const BANK_LOADERS: Record<string, () => Promise<BankQuestion[]>> = {
  "basic-care": () => import("./basic-care").then((m) => m.default),
  "cardiovascular": () => import("./cardiovascular").then((m) => m.default),
  "dosage-and-labs": () => import("./dosage-and-labs").then((m) => m.default),
  "endocrine": () => import("./endocrine").then((m) => m.default),
  "fundamentals": () => import("./fundamentals").then((m) => m.default),
  "gastrointestinal": () => import("./gastrointestinal").then((m) => m.default),
  "health-promotion": () => import("./health-promotion").then((m) => m.default),
  "maternity-newborn": () => import("./maternity-newborn").then((m) => m.default),
  "med-surg": () => import("./med-surg").then((m) => m.default),
  "mental-health": () => import("./mental-health").then((m) => m.default),
  "neurological": () => import("./neurological").then((m) => m.default),
  "pediatrics": () => import("./pediatrics").then((m) => m.default),
  "pharmacology": () => import("./pharmacology").then((m) => m.default),
  "prioritization-delegation": () => import("./prioritization-delegation").then((m) => m.default),
  "psychosocial": () => import("./psychosocial").then((m) => m.default),
  "renal-genitourinary": () => import("./renal-genitourinary").then((m) => m.default),
  "respiratory": () => import("./respiratory").then((m) => m.default),
  "risk-reduction": () => import("./risk-reduction").then((m) => m.default),
  "safe-care": () => import("./safe-care").then((m) => m.default),
};
