/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "MN-001",
    "stem": "A client at 34 weeks gestation presents with a blood pressure of 164/108, 3+ proteinuria, a severe headache, and epigastric pain. Which nursing action takes priority?",
    "options": [
      "Obtain a 24-hour urine collection for total protein",
      "Initiate seizure precautions and prepare to administer magnesium sulfate as prescribed",
      "Encourage ambulation to promote circulation",
      "Schedule a follow-up prenatal visit in one week"
    ],
    "answer": 1,
    "rationale": "Headache and epigastric pain with severe-range hypertension indicate preeclampsia with severe features and imminent risk of eclamptic seizure, so magnesium sulfate prophylaxis and seizure precautions protect both client and fetus. A 24-hour urine collection may confirm the diagnosis but takes a full day and does nothing to prevent the immediate threat of seizure.",
    "why": [
      "A 24-hour collection takes a full day and only confirms proteinuria already documented, doing nothing to prevent an imminent eclamptic seizure.",
      "Severe-range hypertension with headache and epigastric pain signals impending eclampsia, so seizure precautions and magnesium sulfate protect mother and fetus.",
      "Ambulation adds stimulation and injury risk in a client who could seize at any moment; a quiet, low-stimulation environment is required.",
      "Waiting a week for follow-up ignores a hypertensive emergency that demands immediate treatment and likely delivery planning at 34 weeks."
    ]
  },
  {
    "id": "MN-002",
    "stem": "During labor, the nurse observes fetal heart rate decelerations that begin after the peak of each contraction and return to baseline after the contraction ends. Which action should the nurse take first?",
    "options": [
      "Increase the oxytocin infusion rate to shorten labor",
      "Prepare the client for immediate cesarean birth",
      "Reposition the client to a left lateral position",
      "Document the reassuring fetal heart rate pattern"
    ],
    "answer": 2,
    "rationale": "Late decelerations indicate uteroplacental insufficiency, and left lateral repositioning relieves aortocaval compression to improve placental perfusion as the first corrective measure, followed by stopping oxytocin, giving oxygen, and increasing IV fluids. Increasing oxytocin would intensify contractions and further reduce placental blood flow, worsening fetal hypoxia.",
    "why": [
      "Increasing oxytocin intensifies contractions and further reduces placental perfusion, so the infusion is stopped rather than titrated up with late decelerations.",
      "Cesarean birth may follow if intrauterine resuscitation fails, but noninvasive corrective measures such as repositioning are attempted first.",
      "Late decelerations reflect uteroplacental insufficiency, and left lateral positioning relieves aortocaval compression to improve placental blood flow immediately.",
      "This pattern is not reassuring, since decelerations beginning after the peak and recovering late indicate hypoxia requiring intervention rather than documentation alone."
    ]
  },
  {
    "id": "MN-003",
    "stem": "Immediately after spontaneous rupture of membranes, the nurse sees a loop of umbilical cord protruding from the vagina and the fetal heart rate drops to 78 beats per minute. Which action should the nurse take first?",
    "options": [
      "Apply a gloved hand to lift the presenting part off the cord and call for help",
      "Attempt to gently replace the cord into the vagina",
      "Place the client in high Fowler position",
      "Obtain a set of maternal vital signs"
    ],
    "answer": 0,
    "rationale": "Manually elevating the presenting part relieves cord compression and restores fetal oxygenation while the team prepares for emergency cesarean birth, and the nurse maintains this position continuously. Attempting to replace the cord causes vasospasm and further compromises fetal circulation, so it is contraindicated.",
    "why": [
      "Manually lifting the presenting part off the cord restores fetal oxygenation and is held continuously until emergency cesarean birth is accomplished.",
      "Handling or replacing the cord causes vasospasm that worsens fetal hypoxia, so the cord is never pushed back into the vagina.",
      "High Fowler position increases pressure of the presenting part against the cord; knee-chest or Trendelenburg positioning relieves compression instead.",
      "Maternal vital signs are needed before surgery, but obtaining them first leaves the cord compressed while the fetal heart rate remains at 78."
    ]
  },
  {
    "id": "MN-004",
    "stem": "A client receiving a magnesium sulfate infusion for preeclampsia has a respiratory rate of 10, absent deep tendon reflexes, and urine output of 20 mL/hr. Which action should the nurse take?",
    "options": [
      "Increase the infusion rate to achieve a therapeutic level",
      "Administer an additional loading dose",
      "Continue the infusion and reassess in 1 hour",
      "Stop the infusion and prepare to administer calcium gluconate"
    ],
    "answer": 3,
    "rationale": "Respiratory depression, loss of reflexes, and oliguria are signs of magnesium toxicity, so the infusion is stopped immediately and calcium gluconate, the antidote, is given to prevent respiratory and cardiac arrest. Continuing or increasing the infusion would allow serum magnesium to rise further and could be fatal.",
    "why": [
      "Increasing the rate would drive serum magnesium higher in a client already showing toxicity, risking respiratory arrest and cardiac collapse.",
      "A second loading dose adds magnesium to a client whose reflexes are already absent, compounding the toxicity instead of reversing it.",
      "Waiting an hour with a respiratory rate of 10 and absent reflexes allows toxicity to progress toward respiratory and cardiac arrest.",
      "Respiratory depression, absent reflexes, and oliguria indicate magnesium toxicity, so the infusion is stopped and calcium gluconate, the antidote, is given."
    ]
  },
  {
    "id": "MN-005",
    "stem": "Thirty minutes after a vaginal birth, a client saturates a perineal pad in 10 minutes. The fundus is boggy and located above the umbilicus and displaced to the right. Which action should the nurse take first?",
    "options": [
      "Administer methylergonovine intramuscularly",
      "Massage the fundus until firm and then assist the client to empty the bladder",
      "Begin a rapid infusion of lactated Ringer solution",
      "Notify the provider and prepare for surgical exploration"
    ],
    "answer": 1,
    "rationale": "A boggy, elevated, and right-deviated fundus indicates uterine atony with bladder distention, and fundal massage plus bladder emptying are the immediate independent nursing actions that restore uterine tone and control bleeding. Methylergonovine may be needed next but is a dependent intervention and is contraindicated in hypertensive clients, so massage comes first.",
    "why": [
      "Methylergonovine may be needed if bleeding continues, but it is a dependent order and is contraindicated in hypertension, so massage comes first.",
      "A boggy, elevated, right-deviated fundus indicates atony with bladder distention, so massage plus emptying the bladder restores uterine tone immediately.",
      "Rapid fluid infusion supports circulating volume but does not stop the bleeding; the uterus must contract to compress the placental site vessels.",
      "Surgical exploration is reserved for retained fragments or lacerations after simpler measures fail, and this cause is correctable at the bedside."
    ]
  },
  {
    "id": "MN-006",
    "stem": "A first-time mother who is breastfeeding reports sore, cracked nipples on day 3 postpartum. Which teaching should the nurse provide?",
    "options": [
      "Ensure the infant latches with a wide mouth taking in the nipple and much of the areola",
      "Limit each feeding to 5 minutes per breast until soreness resolves",
      "Wash the nipples with soap before and after each feeding",
      "Offer formula supplementation to allow the nipples to heal for 48 hours"
    ],
    "answer": 0,
    "rationale": "Most nipple trauma results from shallow latch, so correcting the latch so the infant takes in the areola rather than just the nipple resolves the pain and protects the milk supply. Soap removes the protective secretions of the Montgomery glands and further dries and cracks the skin, worsening the problem.",
    "why": [
      "Most nipple trauma results from a shallow latch, so a wide-mouth latch that includes much of the areola relieves pain and protects supply.",
      "Shortening feedings does not correct the shallow latch causing the damage and risks engorgement, plugged ducts, and a declining milk supply.",
      "Soap strips the protective lubricating secretions of the Montgomery glands, drying the skin further and worsening the cracking and pain.",
      "Formula supplementation reduces breast stimulation and milk supply and may cause nipple confusion without correcting the underlying latch problem."
    ]
  },
  {
    "id": "MN-007",
    "stem": "At 1 minute of life a newborn has a heart rate of 128, a weak slow cry, some flexion of the extremities, a grimace with suctioning, and a pink body with blue hands and feet. What Apgar score should the nurse assign?",
    "options": [
      "5",
      "9",
      "6",
      "8"
    ],
    "answer": 2,
    "rationale": "Heart rate above 100 scores 2, weak cry scores 1, some flexion scores 1, grimace scores 1, and acrocyanosis scores 1, for a total of 6, which indicates moderate difficulty requiring stimulation and close monitoring. A score of 9 would require nearly all parameters to be optimal, which does not match the weak respiratory effort and limited tone described.",
    "why": [
      "Five is one point too low, because a heart rate above 100 earns the full two points that this total undercounts.",
      "Nine would require a vigorous cry, active flexion, and completely pink color, none of which match this newborn's weak cry and acrocyanosis.",
      "Heart rate 2, weak cry 1, some flexion 1, grimace 1, and acrocyanosis 1 total 6, indicating moderate difficulty needing stimulation.",
      "Eight overestimates this newborn, since the weak cry, partial flexion, and grimace each earn only one point rather than two."
    ]
  },
  {
    "id": "MN-008",
    "stem": "A client who is Rh negative gives birth to an Rh positive newborn, and the direct Coombs test on the newborn is negative. Which action should the nurse anticipate?",
    "options": [
      "No further intervention is needed because the newborn is Rh positive",
      "Administering Rho(D) immune globulin to the newborn",
      "Preparing the newborn for an exchange transfusion",
      "Administering Rho(D) immune globulin to the mother within 72 hours of birth"
    ],
    "answer": 3,
    "rationale": "An Rh negative mother who delivers an Rh positive infant receives Rho(D) immune globulin within 72 hours to prevent maternal antibody formation that would endanger future pregnancies. The immune globulin is never given to the newborn, and an exchange transfusion is unnecessary because the negative Coombs test shows the infant is not currently sensitized.",
    "why": [
      "It is precisely because the newborn is Rh positive that prophylaxis is needed; doing nothing risks maternal sensitization that endangers future pregnancies.",
      "Rho(D) immune globulin is given to the Rh negative mother and never to the newborn, so this reflects a misunderstanding of the therapy.",
      "Exchange transfusion treats severe hemolytic disease, but the negative direct Coombs test shows the newborn's cells are not coated with maternal antibody.",
      "The Rh negative mother receives Rho(D) immune globulin within 72 hours of birth to prevent antibody formation that would threaten later pregnancies."
    ]
  },
  {
    "id": "MN-009",
    "stem": "A newborn whose mother had poorly controlled gestational diabetes is macrosomic and, at 1 hour of age, is jittery and diaphoretic with a weak cry. Which action should the nurse take first?",
    "options": [
      "Obtain a heel-stick blood glucose level",
      "Place the newborn under a radiant warmer and recheck in 30 minutes",
      "Swaddle the newborn and place him in the bassinet to rest",
      "Notify the provider to order a septic workup"
    ],
    "answer": 0,
    "rationale": "Infants of diabetic mothers develop hyperinsulinemia in utero and are at high risk for hypoglycemia, and jitteriness with a weak cry demands immediate glucose measurement so treatment can begin. Simply swaddling and allowing the infant to rest delays detection of a condition that can rapidly cause seizures and neurologic injury.",
    "why": [
      "Jitteriness, diaphoresis, and a weak cry in a macrosomic infant of a diabetic mother demand an immediate heel-stick glucose measurement.",
      "A radiant warmer addresses cold stress, and waiting 30 minutes delays detection of hypoglycemia that can rapidly cause seizures and neurologic injury.",
      "Swaddling and letting the infant rest treats these findings as normal newborn behavior and postpones recognition of a dangerous glucose deficit.",
      "Sepsis can mimic these signs, but a glucose check is faster and noninvasive and addresses the far more likely cause here."
    ]
  },
  {
    "id": "MN-010",
    "stem": "Ten minutes after an epidural is placed, a laboring client's blood pressure falls from 118/72 to 82/46 and the fetal heart rate baseline drops to 100 beats per minute. Which action should the nurse take first?",
    "options": [
      "Administer the prescribed dose of ephedrine",
      "Place the client in a semi-Fowler position and encourage slow breathing",
      "Turn the client to the left side and increase the IV fluid infusion rate",
      "Prepare the client for an immediate cesarean birth"
    ],
    "answer": 2,
    "rationale": "Sympathetic blockade from the epidural causes vasodilation and hypotension, and lateral positioning with an IV fluid bolus is the first-line nursing intervention to restore maternal blood pressure and placental perfusion. Ephedrine is an appropriate follow-up if positioning and fluids fail, but it is a dependent intervention that should not precede the immediate noninvasive measures.",
    "why": [
      "Ephedrine is an appropriate rescue if positioning and fluids fail, but it is a dependent order that should not precede noninvasive first-line measures.",
      "Semi-Fowler position does not relieve aortocaval compression, and slow breathing does nothing for the sympathetic blockade causing this vasodilation and hypotension.",
      "Lateral positioning relieves aortocaval compression while an IV fluid bolus counters epidural-induced vasodilation, restoring maternal pressure and placental perfusion.",
      "Cesarean birth is premature, since epidural-induced hypotension usually responds quickly to repositioning and fluids with recovery of the fetal heart rate."
    ]
  }
];

export default questions;
