/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "MS-001",
    "stem": "A client with chronic kidney disease who missed two dialysis sessions has a serum potassium of 7.2 mEq/L. The cardiac monitor shows peaked T waves and a widening QRS complex. Which prescription should the nurse implement first?",
    "options": [
      "Sodium polystyrene sulfonate 30 g orally",
      "Regular insulin 10 units with 50% dextrose IV",
      "Furosemide 40 mg IV push",
      "Calcium gluconate 1 g IV over 3 minutes"
    ],
    "answer": 3,
    "rationale": "With ECG changes from severe hyperkalemia, IV calcium gluconate is given first because it immediately stabilizes the myocardial cell membrane and protects against lethal dysrhythmias. Insulin with dextrose shifts potassium intracellularly and sodium polystyrene removes it from the body, but both act too slowly to prevent imminent cardiac arrest.",
    "why": [
      "The resin does remove potassium from the body, but it works over hours and cannot protect a heart already showing a widening QRS.",
      "Insulin with dextrose shifts potassium into cells within about twenty minutes, an appropriate next step but too slow to be given first.",
      "Diuresis requires functioning kidneys, and this client with chronic kidney disease and missed dialysis has little capacity to excrete the potassium load.",
      "IV calcium gluconate immediately stabilizes the myocardial cell membrane against the peaked T waves and widening QRS while slower potassium-lowering therapies take effect."
    ]
  },
  {
    "id": "MS-002",
    "stem": "A client admitted with diabetic ketoacidosis has a glucose of 620 mg/dL, pH 7.12, bicarbonate 10 mEq/L, and potassium 5.8 mEq/L, and is receiving an IV insulin infusion and normal saline. Two hours later the glucose is 260 mg/dL. Which action should the nurse anticipate?",
    "options": [
      "Stopping the insulin infusion immediately",
      "Adding dextrose to the IV fluids while continuing the insulin infusion",
      "Administering a 50 mL ampule of 50% dextrose IV push",
      "Beginning a potassium-restricted diet"
    ],
    "answer": 1,
    "rationale": "When the glucose approaches 250 mg/dL in DKA, dextrose is added to the IV fluids so the insulin infusion can continue to close the anion gap and clear ketones without causing hypoglycemia. Stopping the insulin prematurely allows ketogenesis and acidosis to persist even though the glucose has normalized.",
    "why": [
      "Stopping insulin when the glucose falls halts correction of the acidosis, allowing ketogenesis and the anion gap to persist despite a normal sugar.",
      "Adding dextrose once glucose nears 250 lets the insulin infusion keep clearing ketones and closing the anion gap without causing hypoglycemia.",
      "A 50% dextrose ampule treats symptomatic hypoglycemia; at 260 mg/dL it would cause a sharp rebound in glucose and serum osmolality.",
      "Insulin therapy drives potassium into cells, so this client will soon need potassium replacement rather than a restricted intake."
    ]
  },
  {
    "id": "MS-003",
    "stem": "A client with Addison disease is admitted with nausea, vomiting, blood pressure 82/48 mm Hg, heart rate 124/min, sodium 126 mEq/L, potassium 5.9 mEq/L, and glucose 54 mg/dL after abruptly stopping hydrocortisone. What is the nurse's priority intervention?",
    "options": [
      "Administer IV hydrocortisone and 0.9% sodium chloride with dextrose as prescribed",
      "Restrict fluids to correct the hyponatremia",
      "Place the client on strict bed rest and recheck vital signs in 1 hour",
      "Administer a potassium-binding resin before other treatments"
    ],
    "answer": 0,
    "rationale": "Addisonian crisis is a life-threatening deficiency of cortisol and aldosterone producing hypovolemic shock, hyponatremia, hyperkalemia, and hypoglycemia; IV glucocorticoid replacement with saline and dextrose corrects all of these simultaneously. Fluid restriction would deepen the hypovolemia because the hyponatremia here is dilutional to volume loss, not fluid overload.",
    "why": [
      "IV hydrocortisone with saline and dextrose replaces the missing cortisol while simultaneously correcting the hypovolemia, hyponatremia, hyperkalemia, and hypoglycemia of addisonian crisis.",
      "The hyponatremia here reflects aldosterone deficiency and volume loss, so restricting fluids would deepen the shock rather than correct the sodium.",
      "A blood pressure of 82/48 with a heart rate of 124 is shock; waiting an hour without treatment risks cardiovascular collapse.",
      "The hyperkalemia results from aldosterone deficiency and resolves with steroid and fluid replacement, so a resin treats the effect rather than the cause."
    ]
  },
  {
    "id": "MS-004",
    "stem": "A client with a head injury has a urine output of 900 mL/hr for 3 hours, urine specific gravity of 1.002, and serum sodium of 158 mEq/L. Which condition should the nurse suspect, and what is the priority action?",
    "options": [
      "SIADH; restrict fluids to 800 mL per day",
      "Acute kidney injury; prepare for emergent dialysis",
      "Diabetes insipidus; replace fluids and prepare to administer desmopressin",
      "Hyperglycemic hyperosmolar state; begin an insulin infusion"
    ],
    "answer": 2,
    "rationale": "Massive dilute urine output with dilute specific gravity and hypernatremia after head injury indicates central diabetes insipidus from deficient antidiuretic hormone, treated with fluid replacement and desmopressin. SIADH is the opposite picture, producing concentrated urine and hyponatremia, so fluid restriction would rapidly worsen this client's hypovolemia.",
    "why": [
      "SIADH produces concentrated urine and hyponatremia, the opposite of these findings, and fluid restriction would rapidly worsen this client's hypovolemia.",
      "Acute kidney injury characteristically causes oliguria with a rising creatinine, not 900 mL per hour of maximally dilute urine.",
      "Massive dilute urine with a specific gravity of 1.002 and sodium of 158 after head injury indicates central diabetes insipidus needing fluids and desmopressin.",
      "Hyperglycemic hyperosmolar state involves extreme hyperglycemia with an osmotic diuresis; no elevated glucose is reported and insulin cannot replace absent antidiuretic hormone."
    ]
  },
  {
    "id": "MS-005",
    "stem": "A client with severe sepsis has these arterial blood gases on room air: pH 7.28, PaCO2 30 mm Hg, HCO3 14 mEq/L, PaO2 88 mm Hg. How should the nurse interpret these results?",
    "options": [
      "Respiratory acidosis with metabolic compensation",
      "Metabolic acidosis with partial respiratory compensation",
      "Respiratory alkalosis, uncompensated",
      "Metabolic alkalosis with respiratory compensation"
    ],
    "answer": 1,
    "rationale": "The low pH with a low bicarbonate identifies a metabolic acidosis, and the low PaCO2 shows the lungs are hyperventilating to compensate, though the pH remains abnormal so compensation is only partial. Respiratory acidosis would require an elevated PaCO2, which is not present here.",
    "why": [
      "Respiratory acidosis requires an elevated PaCO2, but this client's PaCO2 of 30 mm Hg is low, which rules that interpretation out.",
      "The low pH with a bicarbonate of 14 identifies metabolic acidosis, and the PaCO2 of 30 shows respiratory compensation that remains partial since the pH is still acidotic.",
      "Respiratory alkalosis would raise the pH above 7.45; this pH of 7.28 is acidotic, so the low PaCO2 is compensation rather than the primary disorder.",
      "Metabolic alkalosis requires an elevated pH and elevated bicarbonate, but both of those values are low here."
    ]
  },
  {
    "id": "MS-006",
    "stem": "A trauma client has a blood pressure of 84/60 mm Hg, heart rate 132/min, respirations 30/min, cool clammy skin, urine output 15 mL/hr, and a hemoglobin of 6.8 g/dL. Which intervention should the nurse implement first?",
    "options": [
      "Insert an indwelling urinary catheter to track output",
      "Obtain a 12-lead ECG to evaluate the tachycardia",
      "Place the client in reverse Trendelenburg position",
      "Infuse warmed isotonic crystalloid rapidly through large-bore IV access"
    ],
    "answer": 3,
    "rationale": "These findings represent hypovolemic shock from hemorrhage, and restoring circulating volume through large-bore access while blood products are obtained directly addresses the C in the ABCs. Catheter placement and an ECG provide data but do not treat the failing perfusion, and reverse Trendelenburg would further reduce venous return.",
    "why": [
      "An indwelling catheter improves measurement of output but is a monitoring step that does nothing to restore the failing perfusion.",
      "The tachycardia is an expected compensatory response to hemorrhage, and obtaining an ECG delays the volume resuscitation this client urgently needs.",
      "Reverse Trendelenburg lowers the legs and further reduces venous return, worsening preload in a client already in hypovolemic shock.",
      "Rapid warmed isotonic crystalloid through large-bore access restores circulating volume while blood is obtained, directly treating the hemorrhagic shock in the ABC framework."
    ]
  },
  {
    "id": "MS-007",
    "stem": "A client with a T3 spinal cord injury suddenly reports a pounding headache, and the nurse finds a blood pressure of 210/112 mm Hg, heart rate 48/min, flushing above the injury level, and profuse sweating. What should the nurse do first?",
    "options": [
      "Place the client in a sitting position and check for a distended bladder or kinked catheter",
      "Administer the prescribed nifedipine sublingually",
      "Lay the client flat and elevate the legs",
      "Notify the rapid response team and obtain a stat CT of the head"
    ],
    "answer": 0,
    "rationale": "Autonomic dysreflexia is treated first by sitting the client upright to lower blood pressure orthostatically and removing the noxious stimulus, most often bladder distention or a kinked catheter. Lying the client flat raises cerebral blood pressure and increases stroke risk, and antihypertensives are given only if the stimulus removal does not resolve the crisis.",
    "why": [
      "Sitting the client upright lowers blood pressure orthostatically while checking the bladder and catheter removes the noxious stimulus driving the dysreflexia.",
      "Antihypertensives are reserved for pressures that stay dangerously high after the noxious stimulus is removed, so drug therapy is not the first step.",
      "Lying flat with the legs elevated raises cerebral pressure further in a client already at 210/112, increasing the risk of stroke or seizure.",
      "A head CT investigates a complication that has not yet occurred and delays the simple positioning and bladder check that usually resolve the crisis."
    ]
  },
  {
    "id": "MS-008",
    "stem": "A client 24 hours after a craniotomy has a Glasgow Coma Scale that has fallen from 14 to 10, blood pressure 168/62 mm Hg, heart rate 52/min, and irregular respirations. Which nursing action is most appropriate?",
    "options": [
      "Suction the client deeply every hour to clear secretions",
      "Cluster all nursing care activities to allow longer rest periods",
      "Elevate the head of the bed 30 degrees with the head midline and notify the provider",
      "Administer a 1,000 mL normal saline bolus to improve cerebral perfusion"
    ],
    "answer": 2,
    "rationale": "Widening pulse pressure, bradycardia, and irregular respirations are the Cushing triad of rising intracranial pressure; head elevation with neutral neck alignment promotes venous drainage while the provider is urgently notified. Deep suctioning and fluid boluses both raise intracranial pressure, and clustering care causes cumulative ICP spikes rather than preventing them.",
    "why": [
      "Deep hourly suctioning provokes coughing and sharp spikes in intracranial pressure, which is harmful in a client already showing Cushing triad.",
      "Clustering activities stacks stimulation together and produces cumulative intracranial pressure elevations; care should instead be spaced with rest between interventions.",
      "Bradycardia, widened pulse pressure, and irregular respirations are Cushing triad, so head elevation with midline alignment promotes venous drainage while the provider is notified.",
      "A 1,000 mL bolus increases cerebral edema and intracranial pressure, and this hypertensive client has no volume deficit to correct."
    ]
  },
  {
    "id": "MS-009",
    "stem": "A client with chronic alcohol use is admitted with magnesium 1.1 mg/dL, potassium 3.1 mEq/L, and calcium 7.8 mg/dL, and the monitor shows frequent premature ventricular contractions. Which action should the nurse take first?",
    "options": [
      "Encourage a diet high in green leafy vegetables and nuts",
      "Administer the prescribed oral potassium supplement",
      "Place the client on seizure precautions and reassess in 4 hours",
      "Prepare to administer IV magnesium sulfate with continuous cardiac monitoring"
    ],
    "answer": 3,
    "rationale": "Hypomagnesemia causes refractory hypokalemia and hypocalcemia and predisposes to ventricular dysrhythmias including torsades de pointes, so IV magnesium replacement with cardiac monitoring is the priority. Giving potassium alone will not correct the deficit because the kidneys continue to waste potassium until magnesium is replaced, and dietary teaching does not address an acute dysrhythmia.",
    "why": [
      "Dietary teaching is appropriate for long-term repletion but does nothing about the ventricular ectopy occurring on the monitor right now.",
      "Potassium will not correct until the magnesium is replaced, because renal potassium wasting continues as long as hypomagnesemia persists.",
      "Seizure precautions are a reasonable safety measure, but waiting four hours ignores PVCs that can deteriorate into torsades de pointes.",
      "IV magnesium with cardiac monitoring treats the deficit driving the PVCs as well as the refractory hypokalemia and hypocalcemia of chronic alcohol use."
    ]
  },
  {
    "id": "MS-010",
    "stem": "A client weighing 80 kg has deep partial-thickness and full-thickness burns over 40% of the total body surface area. Using the Parkland formula (4 mL x kg x %TBSA), how much lactated Ringer solution should the nurse plan to infuse during the first 8 hours after the burn?",
    "options": [
      "3,200 mL",
      "6,400 mL",
      "12,800 mL",
      "1,600 mL"
    ],
    "answer": 1,
    "rationale": "The 24-hour total is 4 mL x 80 kg x 40 = 12,800 mL, and half of that (6,400 mL) is delivered in the first 8 hours calculated from the time of injury, not the time of admission. The 12,800 mL option is the full 24-hour volume and infusing it in 8 hours would cause dangerous fluid overload.",
    "why": [
      "This equals only one quarter of the 24-hour requirement and would badly under-resuscitate a client with 40 percent burns during the critical first hours.",
      "Parkland gives 4 mL times 80 kg times 40 percent, or 12,800 mL over 24 hours, and half of that, 6,400 mL, infuses in the first eight hours.",
      "This is the entire 24-hour volume; delivering it within eight hours would cause pulmonary edema and dangerous fluid overload.",
      "This figure falls far below the calculated requirement and would leave the client in worsening hypovolemic burn shock."
    ]
  }
];

export default questions;
