/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "MH-001",
    "stem": "A client admitted for major depressive disorder has begun giving away personal belongings and tells the nurse, \"Everyone would be better off soon; I won't be a burden much longer.\" Which action should the nurse take first?",
    "options": [
      "Reassure the client that symptoms improve once the antidepressant takes effect",
      "Document the statement and continue with unit rounds",
      "Ask the client directly whether he is thinking of killing himself and whether he has a plan",
      "Notify the client's family that he is feeling hopeless"
    ],
    "answer": 2,
    "rationale": "Asking directly about suicidal ideation, plan, and means is the assessment step that determines the level of risk and precautions needed; direct questioning does not increase risk. Offering reassurance closes communication and leaves the immediate physical safety threat, the highest Maslow priority, unassessed.",
    "why": [
      "Reassurance about antidepressant onset closes communication and leaves the immediate risk of self-harm, the highest safety priority, unassessed.",
      "Documenting and continuing rounds leaves a client showing classic suicide warning signs unassessed and unmonitored.",
      "Asking directly about ideation, plan, and means determines lethality and the precautions needed; direct questioning does not increase risk.",
      "Calling the family may follow later, but it neither measures lethality nor secures the client's immediate physical safety."
    ]
  },
  {
    "id": "MH-002",
    "stem": "A client who takes lithium for bipolar disorder reports vomiting and diarrhea for 2 days and now has a coarse hand tremor and an unsteady gait. The serum lithium level is 2.1 mEq/L. Which action should the nurse take first?",
    "options": [
      "Hold the next dose and notify the provider immediately",
      "Encourage a low-sodium diet and increased fluid intake",
      "Administer the dose with food to reduce the nausea",
      "Document the findings and reassess the client in 4 hours"
    ],
    "answer": 0,
    "rationale": "A level above 1.5 mEq/L with vomiting, coarse tremor, and ataxia indicates lithium toxicity, so the drug is withheld and the provider notified before any further dose is given. Restricting sodium is dangerous because low sodium increases lithium reabsorption and would raise the level further.",
    "why": [
      "A level of 2.1 mEq/L with coarse tremor and ataxia indicates lithium toxicity, so the dose is held and the provider notified.",
      "Restricting sodium increases renal reabsorption of lithium and would push an already toxic level higher, making this advice dangerous.",
      "Administering another dose during toxicity compounds the problem, and food will not lower a serum level of 2.1 mEq/L.",
      "Waiting four hours lets toxicity progress toward seizures, dysrhythmias, and renal failure while the drug continues to accumulate."
    ]
  },
  {
    "id": "MH-003",
    "stem": "A client admitted 12 hours after his last alcoholic drink has a blood pressure of 168/98 mm Hg, heart rate 112/min, diaphoresis, generalized tremors, and a CIWA-Ar score of 18. Which intervention is the priority?",
    "options": [
      "Provide a quiet, dimly lit room and reorient the client frequently",
      "Encourage oral fluids and a high-calorie diet",
      "Apply soft wrist restraints to prevent injury",
      "Administer the prescribed PRN lorazepam"
    ],
    "answer": 3,
    "rationale": "A CIWA-Ar score above 8 to 10 with autonomic hyperactivity calls for benzodiazepine treatment, which prevents progression to withdrawal seizures and delirium tremens, a physiologic emergency. Environmental measures are supportive and appropriate but will not stop escalating withdrawal, and restraints are a last resort that would increase agitation and injury risk.",
    "why": [
      "A quiet room and reorientation are appropriate supportive measures but will not halt autonomic hyperactivity or prevent withdrawal seizures.",
      "Fluids and calories are needed in alcohol withdrawal, yet they address neither the CIWA-Ar score of 18 nor the seizure risk.",
      "Restraints are a last resort that increase agitation and injury risk and do nothing to treat the underlying withdrawal physiology.",
      "A CIWA-Ar of 18 with tachycardia, hypertension, and tremor requires benzodiazepine therapy to prevent seizures and delirium tremens."
    ]
  },
  {
    "id": "MH-004",
    "stem": "A client receiving haloperidol develops a temperature of 39.8 C (103.6 F), lead-pipe muscle rigidity, blood pressure 158/94 mm Hg, confusion, and an elevated creatine kinase level. Which action should the nurse take?",
    "options": [
      "Administer the prescribed benztropine for extrapyramidal symptoms",
      "Withhold the haloperidol and notify the provider immediately",
      "Encourage ambulation in the hallway to reduce muscle stiffness",
      "Recheck the temperature in 1 hour and reassess"
    ],
    "answer": 1,
    "rationale": "Hyperthermia, rigidity, autonomic instability, altered mental status, and elevated CK indicate neuroleptic malignant syndrome, a life-threatening reaction requiring immediate discontinuation of the antipsychotic and urgent medical management. Benztropine treats acute dystonia and pseudoparkinsonism but does nothing for NMS and would delay definitive treatment.",
    "why": [
      "Benztropine treats acute dystonia and pseudoparkinsonism; it has no effect on neuroleptic malignant syndrome and would delay definitive treatment.",
      "Fever, lead-pipe rigidity, autonomic instability, confusion, and elevated CK indicate neuroleptic malignant syndrome, so the antipsychotic is stopped immediately.",
      "Ambulating a client with hyperthermia and rigidity increases muscle breakdown and risks collapse; this rigidity does not respond to activity.",
      "Rechecking in an hour delays treatment of a condition with substantial mortality that deteriorates rapidly."
    ]
  },
  {
    "id": "MH-005",
    "stem": "A client with anorexia nervosa (BMI 15) is on day 3 of nutritional rehabilitation. Which laboratory value should the nurse report to the provider first?",
    "options": [
      "Serum phosphorus 1.4 mg/dL",
      "Serum sodium 137 mEq/L",
      "Hemoglobin 11.4 g/dL",
      "Weight gain of 0.4 kg (0.9 lb) since yesterday"
    ],
    "answer": 0,
    "rationale": "Hypophosphatemia is the hallmark of refeeding syndrome and can precipitate cardiac failure, respiratory failure, and dysrhythmias, making it the priority report. The sodium level is normal, mild anemia is expected in malnutrition, and modest weight gain is a desired treatment outcome rather than a complication.",
    "why": [
      "Hypophosphatemia of 1.4 mg/dL on day three of refeeding signals refeeding syndrome, which can cause cardiac and respiratory failure.",
      "A sodium of 137 mEq/L falls within the normal range of 135 to 145 and is not a refeeding concern.",
      "A hemoglobin of 11.4 g/dL reflects the mild anemia commonly seen in malnutrition and does not require urgent reporting.",
      "Gaining 0.4 kg in one day is a desired outcome of nutritional rehabilitation rather than a complication to report."
    ]
  },
  {
    "id": "MH-006",
    "stem": "A client with schizophrenia refuses his dinner tray and tells the nurse, \"The voices are telling me the food has been poisoned.\" Which response by the nurse is most therapeutic?",
    "options": [
      "There is nothing wrong with your food; I ate the same meal myself.",
      "Why would anyone on this unit want to poison your food?",
      "I don't hear the voices, but I can see this is frightening for you. What are the voices telling you?",
      "If you don't eat, we will have to consider tube feeding."
    ],
    "answer": 2,
    "rationale": "Presenting reality without arguing, acknowledging the client's feelings, and assessing the content of command hallucinations builds trust and identifies safety risks. Directly denying the belief or demanding an explanation with \"why\" challenges the delusion, increases defensiveness, and shuts down communication.",
    "why": [
      "Denying the client's experience and offering personal proof argues against the delusion, increasing defensiveness instead of building trust.",
      "A why question demands that the client justify a delusional belief he cannot explain, which shuts down communication.",
      "Presenting reality gently, validating the fear, and exploring hallucination content builds trust and screens for dangerous command hallucinations.",
      "Threatening tube feeding is coercive, reinforces the client's paranoia about the staff, and damages the therapeutic relationship."
    ]
  },
  {
    "id": "MH-007",
    "stem": "A client who started sertraline 5 days ago also takes tramadol and an herbal St. John's wort supplement. The nurse notes agitation, diaphoresis, hyperreflexia, ankle clonus, and a temperature of 38.6 C (101.5 F). Which action should the nurse take first?",
    "options": [
      "Encourage rest and decrease environmental stimulation",
      "Administer the PRN acetaminophen for the fever",
      "Obtain a urine drug screen",
      "Withhold the next dose of sertraline and notify the provider immediately"
    ],
    "answer": 3,
    "rationale": "Agitation, hyperreflexia, clonus, and hyperthermia in a client on multiple serotonergic agents indicate serotonin syndrome, which requires immediate discontinuation of the offending drugs and medical management. Giving acetaminophen treats a symptom while the underlying serotonergic excess continues to progress toward seizures and cardiovascular collapse.",
    "why": [
      "Rest and reduced stimulation are comfort measures that do nothing about the serotonergic excess causing clonus and hyperthermia.",
      "Acetaminophen treats one symptom while serotonin syndrome continues to progress toward seizures and cardiovascular collapse.",
      "A urine drug screen delays treatment when the cause is already evident from the sertraline, tramadol, and St. John's wort combination.",
      "Clonus, hyperreflexia, diaphoresis, and fever on three serotonergic agents indicate serotonin syndrome, requiring immediate drug discontinuation and medical management."
    ]
  },
  {
    "id": "MH-008",
    "stem": "A client in an acute manic episode paces the hallway continuously, has not completed a meal in 2 days, and has lost 3 kg (6.6 lb). Which intervention is most appropriate?",
    "options": [
      "Serve all meals in the dining room with the other clients",
      "Offer high-calorie finger foods and fluids the client can carry while walking",
      "Insist that the client remain seated for 30 minutes at each meal",
      "Restrict unit privileges until the client finishes a full meal"
    ],
    "answer": 1,
    "rationale": "Portable, high-calorie finger foods meet the physiologic need for nutrition without requiring the hyperactive client to sit still, which he cannot yet do. Insisting the client sit through a meal or using privileges as leverage sets up a power struggle and does not correct the immediate nutritional deficit.",
    "why": [
      "The dining room is highly stimulating and requires sitting still, which this manic client cannot do, so intake stays poor.",
      "Portable high-calorie finger foods and fluids meet the urgent nutritional need without requiring the hyperactive client to sit still.",
      "Insisting on 30 seated minutes is unrealistic during acute mania and produces a power struggle instead of calories.",
      "Withholding privileges as leverage is punitive, damages the therapeutic relationship, and leaves the 3 kg weight loss uncorrected."
    ]
  },
  {
    "id": "MH-009",
    "stem": "A veteran with PTSD suddenly begins shouting and crouching behind a chair in the day room after a fire alarm test, appearing unaware of his surroundings. Which action should the nurse take first?",
    "options": [
      "Speak calmly, orient the client to the present time and place, and guide him to a quieter area",
      "Ask the client to describe the traumatic combat event in detail",
      "Place the client in seclusion until he becomes calm",
      "Administer the PRN antipsychotic immediately"
    ],
    "answer": 0,
    "rationale": "During a flashback the client needs grounding: a calm voice, reorientation to the present, and reduced stimuli restore safety by the least restrictive means. Exploring trauma details during the dissociative episode intensifies the flashback, and seclusion is reserved for imminent danger after less restrictive measures fail.",
    "why": [
      "Grounding with a calm voice, reorientation to the present, and reduced stimuli ends the flashback by the least restrictive means.",
      "Asking for combat details during a dissociative flashback intensifies re-experiencing; trauma processing belongs in planned therapy sessions.",
      "Seclusion is reserved for imminent danger after less restrictive measures fail, and confinement would deepen this veteran's terror.",
      "Medication may be considered later, but chemical restraint before attempting grounding is not the least restrictive intervention."
    ]
  },
  {
    "id": "MH-010",
    "stem": "A client in the clinic waiting room becomes acutely short of breath with a heart rate of 124/min, chest tightness, and trembling, saying, \"I'm going to die.\" Which action should the nurse take first?",
    "options": [
      "Provide detailed instruction on diaphragmatic breathing technique",
      "Leave the client alone in a room to reduce stimulation",
      "Stay with the client and give brief, calm, simple directions to breathe slowly with the nurse",
      "Explore childhood experiences that may have triggered the attack"
    ],
    "answer": 2,
    "rationale": "During a panic attack perceptual field is severely narrowed, so remaining present and giving short, simple, repetitive directions is the intervention the client can actually follow. Leaving the client alone increases terror and injury risk, and detailed teaching or insight-oriented exploration cannot be processed until anxiety decreases to a moderate level.",
    "why": [
      "Detailed breathing instruction cannot be absorbed during panic, when the perceptual field is severely narrowed.",
      "Leaving a panicking client alone increases terror and injury risk; the nurse's calm presence is itself the intervention.",
      "Staying present with brief, calm, repeated directions matches the narrowed perceptual field of panic and helps slow the breathing.",
      "Insight-oriented exploration of childhood requires no more than moderate anxiety and is useless while the client believes death is imminent."
    ]
  }
];

export default questions;
