/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "NE-001",
    "stem": "A client arrives 90 minutes after the sudden onset of right-sided weakness and expressive aphasia. Which finding in the history should the nurse report before thrombolytic therapy is considered?",
    "options": [
      "Blood pressure of 158/88 mm Hg on arrival",
      "A gastrointestinal bleed requiring transfusion three weeks ago",
      "A history of atrial fibrillation treated with rate control",
      "A blood glucose of 132 mg/dL"
    ],
    "answer": 1,
    "rationale": "Recent active internal bleeding within the previous 21 days is an absolute contraindication to alteplase because thrombolysis could produce catastrophic hemorrhage, making this a critical safety report. A blood pressure of 158/88 is below the 185/110 threshold that would require treatment before thrombolysis, so it is not disqualifying.",
    "why": [
      "A pressure of 158/88 is below the 185/110 threshold that must be treated before alteplase, so it does not disqualify this client.",
      "Active internal bleeding requiring transfusion within the past 21 days is an absolute contraindication to alteplase because of catastrophic hemorrhage risk.",
      "Atrial fibrillation is a common source of embolic stroke rather than a contraindication; anticoagulant use, not rate control, would raise bleeding concern.",
      "A glucose of 132 mg/dL is normal; only marked hypoglycemia or hyperglycemia would mimic stroke and change the thrombolytic decision."
    ]
  },
  {
    "id": "NE-002",
    "stem": "A client with a traumatic brain injury has these serial vital signs: blood pressure rising from 124/76 to 178/62, heart rate falling from 88 to 48, and respirations becoming irregular. Which conclusion should the nurse draw?",
    "options": [
      "The client is developing hypovolemic shock",
      "The client is responding appropriately to mannitol therapy",
      "The client is experiencing an anxiety reaction to the ICU environment",
      "The client is showing Cushing triad, indicating dangerously increased intracranial pressure"
    ],
    "answer": 3,
    "rationale": "Widening pulse pressure, bradycardia, and irregular respirations form Cushing triad, a late and ominous sign of increased intracranial pressure and impending herniation that requires immediate provider notification. Hypovolemic shock would instead produce hypotension with tachycardia and a narrowed pulse pressure, the opposite pattern.",
    "why": [
      "Hypovolemic shock produces hypotension, tachycardia, and a narrowed pulse pressure, which is the opposite of the widening pressure and bradycardia seen here.",
      "Effective mannitol therapy would lower intracranial pressure and stabilize vital signs, so this deteriorating pattern reflects failure rather than therapeutic response.",
      "Anxiety raises heart rate and blood pressure together; it does not cause bradycardia with irregular respirations in a client with brain injury.",
      "Widening pulse pressure, bradycardia, and irregular respirations form Cushing triad, a late sign of intracranial hypertension and impending herniation."
    ]
  },
  {
    "id": "NE-003",
    "stem": "The nurse enters a room and finds a client having a generalized tonic-clonic seizure in bed. Which action should the nurse take first?",
    "options": [
      "Turn the client to the side and protect the head",
      "Insert a padded tongue blade between the teeth",
      "Restrain the client's arms to prevent injury",
      "Draw a stat serum phenytoin level"
    ],
    "answer": 0,
    "rationale": "Side-lying positioning maintains a patent airway and allows secretions to drain, addressing airway and breathing priorities while padding protects the head from trauma. Inserting anything into the mouth or restraining the limbs during a seizure can cause dental, oral, or musculoskeletal injury and is contraindicated.",
    "why": [
      "Side-lying positioning keeps the airway patent and lets secretions drain, while protecting the head prevents trauma during the convulsive movements.",
      "Forcing anything between clenched teeth can fracture teeth, lacerate the mouth, or obstruct the airway, and is contraindicated during an active seizure.",
      "Restraining the limbs during tonic-clonic activity can cause fractures and soft tissue injury; the nurse guides the client away from hazards instead.",
      "A phenytoin level helps assess dosing after the event, but drawing laboratory studies never takes precedence over protecting the airway during a seizure."
    ]
  },
  {
    "id": "NE-004",
    "stem": "A client with a T4 spinal cord injury suddenly reports a pounding headache; blood pressure is 210/112, and the nurse notes flushing above the level of injury and gooseflesh below it. After placing the client in high Fowler position, which action should the nurse take next?",
    "options": [
      "Administer an as-needed dose of oral acetaminophen",
      "Apply oxygen at 4 L/min by nasal cannula",
      "Assess for a kinked urinary catheter or bladder distention",
      "Perform passive range-of-motion exercises to the lower extremities"
    ],
    "answer": 2,
    "rationale": "Autonomic dysreflexia is triggered by a noxious stimulus below the injury level, and bladder distention or an obstructed catheter is the most common cause, so removing the stimulus resolves the hypertensive crisis. Giving acetaminophen treats a symptom while leaving the trigger in place, allowing blood pressure to remain at stroke-level values.",
    "why": [
      "Acetaminophen treats the headache symptom while the noxious trigger continues driving stroke-level hypertension, so the dysreflexic crisis would simply persist.",
      "Oxygen may be added for comfort, but hypoxia is not the problem and the blood pressure will not fall until the stimulus is removed.",
      "Bladder distention or a kinked catheter is the most common trigger below the injury, and removing it resolves the hypertensive crisis.",
      "Passive range of motion adds more stimulation below the level of injury and could intensify the sympathetic surge rather than relieve it."
    ]
  },
  {
    "id": "NE-005",
    "stem": "A college student is admitted with suspected bacterial meningitis after presenting with fever, nuchal rigidity, and photophobia. Which nursing action is most important during the first 24 hours?",
    "options": [
      "Position the client supine with the neck flexed for comfort",
      "Keep the room brightly lit for frequent neurologic assessment",
      "Encourage ambulation in the hallway every 4 hours",
      "Maintain droplet precautions until 24 hours of effective antibiotics have been given"
    ],
    "answer": 3,
    "rationale": "Neisseria meningitidis is transmitted by respiratory droplets, so droplet precautions protect other clients and staff until the client has received 24 hours of appropriate antibiotic therapy. Bright lighting worsens photophobia and increases discomfort and stimulation, so a darkened, quiet room is preferred.",
    "why": [
      "Neck flexion stretches inflamed meninges and increases pain, so the client is positioned with the head of the bed elevated and neck neutral.",
      "Bright lighting aggravates photophobia and adds stimulation; a darkened, quiet room is preferred while neurologic checks are still performed as scheduled.",
      "Hallway ambulation every four hours increases stimulation and energy demand during acute meningitis, when quiet rest with minimal stimuli is indicated.",
      "Meningococcal meningitis spreads by respiratory droplets, so droplet precautions protect others until 24 hours of effective antibiotic therapy are complete."
    ]
  },
  {
    "id": "NE-006",
    "stem": "A client with myasthenia gravis takes pyridostigmine. Which statement by the client indicates a need for further teaching?",
    "options": [
      "I will schedule my most demanding activities for the morning",
      "If I miss a dose it is fine to skip it and take the next one later in the day",
      "I will take my medication about 30 minutes before meals",
      "I will call my provider if I develop new difficulty swallowing"
    ],
    "answer": 1,
    "rationale": "Anticholinesterase medication must be taken on an exact schedule because missed or delayed doses can precipitate myasthenic crisis with respiratory failure, so casually skipping a dose reflects unsafe understanding. Taking the drug 30 minutes before meals is correct because it maximizes chewing and swallowing strength and reduces aspiration risk.",
    "why": [
      "Scheduling demanding activities in the morning is correct, because muscle strength is greatest early and fatigue accumulates as the day progresses.",
      "Skipping or delaying anticholinesterase doses can precipitate myasthenic crisis with respiratory failure, so this statement reveals unsafe understanding needing correction.",
      "Taking pyridostigmine about 30 minutes before meals is accurate, since peak strength then improves chewing and swallowing and lowers aspiration risk.",
      "Reporting new difficulty swallowing is appropriate, because bulbar weakness signals worsening disease and threatens the airway, so this reflects correct understanding."
    ]
  },
  {
    "id": "NE-007",
    "stem": "The nurse is planning care for a client with Parkinson disease who has a shuffling gait, bradykinesia, and difficulty initiating movement. Which intervention should the nurse include?",
    "options": [
      "Instruct the client to walk with the feet close together for balance",
      "Discourage exercise to conserve limited energy",
      "Teach the client to consciously lift the toes and swing the arms while walking",
      "Provide all meals as pureed textures regardless of swallowing ability"
    ],
    "answer": 2,
    "rationale": "Deliberately lifting the toes, using a wide base, and swinging the arms counteracts the festinating shuffling gait and reduces fall risk, supporting both mobility and safety. Narrowing the base of support would decrease stability and increase falls, and routine puree without a swallow evaluation is unnecessarily restrictive.",
    "why": [
      "A narrow base of support reduces stability in a client with bradykinesia and festination, increasing rather than decreasing the risk of falls.",
      "Exercise preserves range of motion, balance, and function in Parkinson disease, so discouraging it accelerates rigidity, contractures, and overall deconditioning.",
      "Consciously lifting the toes and swinging the arms interrupts the shuffling festinating gait, lengthening stride and improving balance and safety.",
      "Pureed textures should follow a swallowing evaluation; applying them to everyone is unnecessarily restrictive and can reduce appetite and nutritional intake."
    ]
  },
  {
    "id": "NE-008",
    "stem": "A client with relapsing-remitting multiple sclerosis asks how to reduce the risk of an exacerbation. Which response by the nurse is most accurate?",
    "options": [
      "Avoid overheating, including hot baths and strenuous activity in hot weather",
      "Limit fluid intake to less than 1,000 mL per day",
      "Remain on strict bed rest whenever symptoms are present",
      "Take a hot bath before bed to loosen spastic muscles"
    ],
    "answer": 0,
    "rationale": "Elevated core temperature slows conduction in demyelinated fibers and commonly triggers a temporary worsening of symptoms, so heat avoidance is standard teaching. Hot baths are specifically discouraged for this reason, and prolonged bed rest promotes deconditioning, contractures, and pressure injury rather than protecting the client.",
    "why": [
      "Elevated core temperature slows conduction in demyelinated fibers, so avoiding hot baths and heat exposure prevents transient worsening of symptoms.",
      "Fluid restriction has no role in multiple sclerosis and promotes constipation and urinary tract infection, both of which can aggravate symptoms.",
      "Strict bed rest causes deconditioning, contractures, and pressure injury; balanced activity with planned rest periods is recommended even during exacerbations.",
      "A hot bath raises core temperature and typically intensifies weakness and fatigue, so it is specifically discouraged despite its appeal for spasticity."
    ]
  },
  {
    "id": "NE-009",
    "stem": "A client with a closed head injury opens the eyes to painful stimuli, makes incomprehensible sounds, and withdraws from pain. What Glasgow Coma Scale score should the nurse document?",
    "options": [
      "6",
      "12",
      "10",
      "8"
    ],
    "answer": 3,
    "rationale": "Eye opening to pain scores 2, incomprehensible sounds score 2, and withdrawal from pain scores 4, for a total of 8, which is the threshold at which intubation for airway protection is generally considered. A score of 6 would underestimate the motor response, since withdrawal is scored higher than abnormal flexion or extension.",
    "why": [
      "Six would require a lower motor score such as abnormal flexion, but withdrawal from pain scores four, making this total too low.",
      "Twelve overestimates this client, since eye opening to pain and incomprehensible sounds each earn only two points rather than higher responses.",
      "Ten is too high, because reaching that total would require confused or oriented speech instead of the incomprehensible sounds documented here.",
      "Eye opening to pain scores 2, incomprehensible sounds 2, and withdrawal 4, totaling 8, the threshold for considering intubation."
    ]
  },
  {
    "id": "NE-010",
    "stem": "A client admitted after a fall has clear fluid draining from the right nostril that forms a yellow ring around a central blood stain on the linen. Which nursing action is appropriate?",
    "options": [
      "Pack the nostril firmly with sterile gauze",
      "Insert a small-bore nasogastric tube to decompress the stomach",
      "Allow the drainage to flow freely onto a sterile pad and notify the provider",
      "Have the client blow the nose to clear the drainage"
    ],
    "answer": 2,
    "rationale": "A halo sign suggests cerebrospinal fluid rhinorrhea from a basilar skull fracture; drainage should be collected on a loose sterile dressing without obstruction, and the provider notified because of meningitis risk. Packing the nose or passing a nasogastric tube risks forcing organisms intracranially or passing the tube through the fracture into the brain.",
    "why": [
      "Packing the nostril obstructs cerebrospinal fluid drainage and can force organisms upward through the fracture line, sharply raising the risk of meningitis.",
      "A nasogastric tube can pass through the basilar skull fracture into the cranial vault, so oral placement is required if decompression is needed.",
      "The halo sign suggests cerebrospinal fluid rhinorrhea, so drainage flows freely onto a sterile pad and the provider is notified for meningitis risk.",
      "Blowing the nose raises intracranial and sinus pressure and can force bacteria into the cranial cavity, so it is specifically prohibited."
    ]
  }
];

export default questions;
