/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "PD-001",
    "stem": "A 3-year-old arrives in the emergency department sitting forward in a tripod position, drooling, with a muffled voice, inspiratory stridor, and a temperature of 39.4 C (102.9 F). Which action should the nurse take first?",
    "options": [
      "Use a tongue blade to visualize the posterior pharynx",
      "Keep the child upright in the parent's arms and notify the provider immediately while preparing for emergency airway management",
      "Obtain a throat culture and send it to the laboratory",
      "Place the child supine and start a peripheral IV for antibiotics"
    ],
    "answer": 1,
    "rationale": "Drooling, muffled voice, stridor, and tripod positioning suggest epiglottitis, a true airway emergency; keeping the child calm and upright prevents complete obstruction while skilled airway support is mobilized (ABCs). Inspecting the pharynx with a tongue blade or forcing the child supine can trigger laryngospasm and total occlusion, so those actions are contraindicated.",
    "why": [
      "Depressing the tongue in suspected epiglottitis can provoke laryngospasm and complete airway obstruction, so this action is contraindicated.",
      "Keeping the child calm and upright preserves the marginal airway while skilled personnel prepare for emergency intubation, addressing airway first.",
      "A throat culture requires pharyngeal manipulation and delays airway management; cultures are obtained only after the airway is secured.",
      "Supine positioning lets the swollen epiglottis occlude the airway, and an IV start increases crying and obstruction before the airway is protected."
    ]
  },
  {
    "id": "PD-002",
    "stem": "A 4-month-old with respiratory syncytial virus bronchiolitis has a respiratory rate of 68/min, nasal flaring, thick nasal secretions, and an oxygen saturation of 88% on room air. Which action should the nurse take first?",
    "options": [
      "Offer the ordered oral fluids to help thin secretions",
      "Place the infant prone to improve oxygenation",
      "Suction the nares with a bulb syringe and apply supplemental oxygen",
      "Obtain a nasopharyngeal swab for RSV testing"
    ],
    "answer": 2,
    "rationale": "Infants are obligate nose breathers, so clearing the nares and correcting hypoxemia addresses airway and breathing first under the ABC framework. Offering oral fluids to a tachypneic infant with a rate of 68/min risks aspiration and does nothing for the immediate hypoxemia.",
    "why": [
      "Oral fluids in an infant breathing 68 times per minute risk aspiration and do nothing for the current hypoxemia.",
      "Prone positioning is not an established bronchiolitis intervention, raises sudden death risk in infants, and leaves the obstructed nares uncleared.",
      "Infants are obligate nose breathers, so bulb suctioning plus supplemental oxygen relieves the obstruction and corrects the 88% saturation immediately.",
      "An RSV swab confirms the diagnosis but is diagnostic rather than therapeutic, and collecting it leaves the hypoxemia untreated."
    ]
  },
  {
    "id": "PD-003",
    "stem": "A parent whose 18-month-old had a first simple febrile seizure is being discharged. Which statement by the parent indicates that teaching has been effective?",
    "options": [
      "If another seizure occurs, I will turn my child on his side and time how long it lasts.",
      "I will place a padded tongue blade in his mouth to protect his tongue.",
      "Giving ibuprofen at the first sign of fever will prevent all future seizures.",
      "My child will need to take antiseizure medication every day for life."
    ],
    "answer": 0,
    "rationale": "Side-lying positioning protects the airway from aspiration and timing the event guides treatment decisions, which is the core of safe home seizure management. Placing anything in the mouth is unsafe and can cause oral trauma or obstruction, and antipyretics have not been shown to prevent recurrent febrile seizures.",
    "why": [
      "Side-lying protects the airway from aspiration during a seizure, and timing the event guides decisions about emergency treatment.",
      "Nothing should be placed in the mouth during a seizure; a tongue blade can break teeth, lacerate tissue, or obstruct the airway.",
      "Antipyretics improve comfort but have never been shown to prevent recurrence of febrile seizures, so this statement is factually inaccurate.",
      "Simple febrile seizures are benign and self-limited, so daily lifelong antiseizure medication is not indicated and reflects a misunderstanding."
    ]
  },
  {
    "id": "PD-004",
    "stem": "A 12-month-old is scheduled for MMR and varicella vaccines at a well-child visit. The child has clear rhinorrhea, an occasional cough, and a temperature of 37.6 C (99.7 F). Which action should the nurse take?",
    "options": [
      "Withhold both vaccines until the child has been symptom free for 2 weeks",
      "Administer the varicella vaccine only",
      "Notify the provider to obtain an order deferring immunizations for 1 month",
      "Administer both vaccines as scheduled, because a mild upper respiratory infection is not a contraindication"
    ],
    "answer": 3,
    "rationale": "Mild illness with or without low-grade fever is not a contraindication to immunization, and deferring doses creates missed opportunities for protection. Withholding the vaccines would delay immunity unnecessarily; only moderate to severe acute illness or a true anaphylactic reaction to a component warrants postponement.",
    "why": [
      "No two-week symptom-free rule exists, and this delay would create repeated missed opportunities to immunize this child.",
      "Splitting the visit is unnecessary because neither live vaccine is contraindicated by clear rhinorrhea and a temperature of 37.6 C.",
      "Deferring a month delays protection without benefit, and no provider order is needed because mild illness is not a contraindication.",
      "Mild upper respiratory illness with low-grade fever is not a contraindication, so both live vaccines are given as scheduled."
    ]
  },
  {
    "id": "PD-005",
    "stem": "The nurse is teaching the parents of a 4-year-old with cystic fibrosis about pancreatic enzyme replacement. Which instruction should the nurse include?",
    "options": [
      "Give the enzymes once daily at bedtime",
      "Mix the enzyme beads in hot milk so they dissolve completely",
      "Give the enzyme capsules with every meal and snack, sprinkling the beads on applesauce if the child cannot swallow the capsule",
      "Hold the enzymes on days the child has loose stools"
    ],
    "answer": 2,
    "rationale": "Enzymes must be given with all meals and snacks to allow fat and protein absorption, and the beads may be sprinkled on a small amount of an acidic food such as applesauce. Holding enzymes when stools are loose worsens steatorrhea and malabsorption, since loose fatty stools usually signal an inadequate rather than an excessive enzyme dose.",
    "why": [
      "Once-daily bedtime dosing leaves every meal uncovered, so fat and protein pass unabsorbed and steatorrhea and poor growth continue.",
      "Heat destroys the enteric coating on the enzyme beads and milk is alkaline; beads belong on a small amount of acidic food.",
      "Enzymes must accompany every meal and snack, and the beads may be sprinkled on applesauce when the child cannot swallow capsules.",
      "Loose fatty stools usually indicate too little enzyme rather than too much, so holding doses worsens malabsorption and weight loss."
    ]
  },
  {
    "id": "PD-006",
    "stem": "A 4-year-old with Kawasaki disease is receiving IV immunoglobulin and high-dose aspirin. Which assessment finding requires immediate follow-up by the nurse?",
    "options": [
      "Bilateral basilar crackles and a new S3 gallop",
      "Red, cracked lips and a strawberry tongue",
      "Peeling skin on the palms and soles",
      "Irritability and bilateral conjunctival redness without drainage"
    ],
    "answer": 0,
    "rationale": "Crackles with a new gallop suggest myocarditis or fluid overload from the IVIG infusion and represent a cardiovascular emergency requiring immediate intervention (ABCs). Cracked lips, strawberry tongue, desquamation, irritability, and nonexudative conjunctivitis are all expected features of Kawasaki disease and do not require urgent action.",
    "why": [
      "Crackles with a new S3 gallop suggest myocarditis or IVIG-related fluid overload, a cardiovascular emergency under the ABC framework.",
      "Red cracked lips and strawberry tongue are classic expected findings in Kawasaki disease and call for comfort measures, not urgent intervention.",
      "Desquamation of the palms and soles is an expected subacute-phase feature of Kawasaki disease rather than an emergency.",
      "Irritability and nonexudative conjunctival redness are hallmark Kawasaki findings; they are distressing but not immediately dangerous."
    ]
  },
  {
    "id": "PD-007",
    "stem": "During a 9-month well-child visit, which finding should the nurse report to the provider for further developmental evaluation?",
    "options": [
      "The infant cries when the parent leaves the examination room",
      "The infant bangs two blocks together",
      "The infant says mama without referring to a specific person",
      "The infant is unable to sit without support"
    ],
    "answer": 3,
    "rationale": "Independent sitting is expected by about 8 months, so its absence at 9 months is a gross motor red flag warranting evaluation. Separation anxiety, banging objects together, and nonspecific babbling of mama are all normal 9-month findings and require only reassurance.",
    "why": [
      "Separation anxiety peaks near 9 months, so crying when the parent leaves reflects normal attachment rather than a developmental delay.",
      "Banging two blocks together is an age-appropriate fine motor milestone for a 9-month-old and needs no referral.",
      "Nonspecific babbling of mama is normal at 9 months; specific use of the word is not expected until closer to 12 months.",
      "Independent sitting is expected by about 8 months, so its absence at 9 months is a gross motor red flag requiring evaluation."
    ]
  },
  {
    "id": "PD-008",
    "stem": "A 6-month-old with tetralogy of Fallot suddenly becomes deeply cyanotic and irritable while crying during a diaper change. Which action should the nurse take first?",
    "options": [
      "Administer oxygen by face mask and start an IV line",
      "Place the infant in a knee-chest position",
      "Give the scheduled dose of digoxin",
      "Lay the infant flat and stimulate crying to expand the lungs"
    ],
    "answer": 1,
    "rationale": "The knee-chest position increases systemic vascular resistance and decreases right-to-left shunting, which is the immediate treatment for a hypercyanotic tet spell and can be done instantly at the bedside. Oxygen and IV access follow, but starting an IV first prolongs crying and worsens the shunt.",
    "why": [
      "Oxygen and IV access are appropriate but come after positioning; starting an IV first prolongs crying and worsens the right-to-left shunt.",
      "The knee-chest position raises systemic vascular resistance, decreasing right-to-left shunting and relieving the hypercyanotic tet spell immediately.",
      "Digoxin does not relieve the infundibular spasm of a tet spell, and giving a scheduled dose delays the positioning the infant needs.",
      "Lying flat lowers systemic vascular resistance and stimulating crying increases the shunt, deepening the cyanosis rather than relieving it."
    ]
  },
  {
    "id": "PD-009",
    "stem": "The nurse reviews home safety with the parent of a 2-year-old. Which statement by the parent requires further teaching?",
    "options": [
      "I keep all cleaning products in a locked cabinet.",
      "My toddler rides in a rear-facing car seat in the back seat.",
      "I let my 2-year-old eat popcorn and whole grapes while watching television.",
      "I set the water heater temperature at 49 C (120 F)."
    ],
    "answer": 2,
    "rationale": "Popcorn and whole grapes are leading choking hazards for children under 4, and eating while distracted increases aspiration risk, so this statement shows a knowledge deficit. Locked chemicals, rear-facing restraint, and a water heater at 49 C (120 F) are all correct toddler safety measures.",
    "why": [
      "Locking cleaning products away is correct poison prevention for a toddler and shows appropriate understanding.",
      "Rear-facing restraint in the back seat is the recommended standard for a 2-year-old, so no further teaching is needed.",
      "Popcorn and whole grapes are leading choking hazards under age 4, and eating while distracted by television increases aspiration risk.",
      "A water heater set at 49 C (120 F) prevents scald burns and reflects correct home safety practice."
    ]
  },
  {
    "id": "PD-010",
    "stem": "An 18 kg child is prescribed amoxicillin 45 mg/kg/day divided every 12 hours. The pharmacy sends a labeled syringe containing 500 mg for the next dose. Which action should the nurse take?",
    "options": [
      "Hold the dose and clarify the order with the provider, because the calculated safe dose is 405 mg every 12 hours",
      "Give the 500 mg dose because it is within 20% of the calculated dose",
      "Administer half of the 500 mg dose and document the change",
      "Administer the dose as sent and monitor the child for adverse effects"
    ],
    "answer": 0,
    "rationale": "45 mg/kg x 18 kg = 810 mg/day, divided by 2 doses = 405 mg per dose, so the 500 mg syringe exceeds the prescribed dose and must be clarified before administration. Adjusting or splitting the dose independently is outside the nurse's scope and giving an unverified dose violates safe medication administration.",
    "why": [
      "45 mg/kg x 18 kg equals 810 mg daily, or 405 mg every 12 hours, so the 500 mg syringe exceeds the order.",
      "No twenty percent tolerance rule exists in safe medication administration; a dose that does not match the order must be verified, not rationalized.",
      "Splitting the syringe to 250 mg underdoses the child, and independently altering a prescribed dose exceeds the nurse's scope.",
      "Knowingly giving a discrepant dose and watching for adverse effects exposes the child to harm instead of preventing it."
    ]
  }
];

export default questions;
