/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "PH-001",
    "stem": "A client with a pulmonary embolism is receiving a continuous IV heparin infusion at 1,200 units/hr. The 0600 aPTT result is 110 seconds (control 30 seconds), and the nurse notes bleeding around the peripheral IV site. What should the nurse do first?",
    "options": [
      "Administer protamine sulfate 25 mg IV push",
      "Stop the heparin infusion and notify the provider",
      "Apply a pressure dressing to the IV site and recheck in 1 hour",
      "Decrease the infusion rate by half and repeat the aPTT in 6 hours"
    ],
    "answer": 1,
    "rationale": "An aPTT more than 2.5 times control with active bleeding indicates excessive anticoagulation, so the nurse stops the ongoing source of harm and notifies the provider for new orders. Protamine sulfate is the antidote but requires a provider order and is not the first independent nursing action; simply dressing the site allows the heparin to keep circulating.",
    "why": [
      "Protamine is the correct antidote but requires a provider order, and giving it before stopping the infusion leaves heparin still flowing in.",
      "Stopping the infusion immediately halts further anticoagulation, and provider notification secures new orders when the aPTT is nearly four times control with active bleeding.",
      "A pressure dressing treats the visible oozing while systemic heparin keeps circulating unchecked, and waiting an hour delays correction of dangerous over-anticoagulation.",
      "Halving the rate still delivers heparin to an already over-anticoagulated bleeding client, and rechecking the aPTT in six hours is far too long a delay."
    ]
  },
  {
    "id": "PH-002",
    "stem": "Fifteen minutes into a vancomycin 1 g IV infusion running over 30 minutes, a client reports itching and the nurse observes flushing of the face, neck, and upper chest with a blood pressure of 92/54 mm Hg. Which action is the priority?",
    "options": [
      "Document the finding as an expected response to vancomycin",
      "Administer the next dose in a more dilute solution",
      "Obtain a set of blood cultures before continuing",
      "Stop the infusion and notify the provider"
    ],
    "answer": 3,
    "rationale": "Flushing, pruritus, and hypotension during rapid vancomycin infusion indicate vancomycin infusion reaction (red man syndrome), a histamine-mediated response managed by stopping the infusion, giving an antihistamine, and restarting at a slower rate. Documenting it as expected ignores the hypotension, which is a circulatory (ABC) problem requiring immediate intervention.",
    "why": [
      "Flushing may be common with vancomycin, but a blood pressure of 92/54 is a circulatory problem that cannot be charted as expected and ignored.",
      "Diluting future doses does help prevent recurrence, but it does nothing about the reaction happening right now during the infusion in progress.",
      "Blood cultures address suspected infection, not a histamine-mediated infusion reaction, and drawing them while the drug keeps infusing prolongs the hypotension.",
      "Flushing, pruritus, and hypotension during rapid vancomycin infusion indicate an infusion reaction; stopping the drug removes the histamine trigger while the provider orders antihistamines."
    ]
  },
  {
    "id": "PH-003",
    "stem": "Twenty minutes after a unit of packed red blood cells is started, a client has a temperature increase from 37.0 C to 38.6 C, chills, low back pain, and dark red-brown urine. What is the nurse's first action?",
    "options": [
      "Stop the transfusion and keep the line open with 0.9% sodium chloride using new tubing",
      "Slow the transfusion to 50 mL/hr and administer acetaminophen",
      "Obtain a urine specimen for hemoglobin before taking further action",
      "Administer diphenhydramine 25 mg IV and continue the transfusion"
    ],
    "answer": 0,
    "rationale": "Fever, chills, flank pain, and hemoglobinuria signal an acute hemolytic transfusion reaction; stopping the blood immediately while maintaining IV access with normal saline through new tubing prevents further hemolysis and supports renal perfusion. Slowing the rate or premedicating still exposes the client to incompatible cells and can be fatal.",
    "why": [
      "Fever, chills, flank pain, and hemoglobinuria signal acute hemolysis, so stopping the blood halts further destruction while new saline tubing preserves access and renal perfusion.",
      "Slowing the rate still infuses incompatible red cells, and acetaminophen is appropriate for a simple febrile reaction rather than this hemolytic emergency.",
      "The urine specimen is part of the workup, but obtaining it first lets incompatible cells keep infusing during a potentially fatal reaction.",
      "Antihistamines treat mild allergic reactions; continuing this transfusion exposes the client to more incompatible cells and can cause acute renal failure or death."
    ]
  },
  {
    "id": "PH-004",
    "stem": "A client receiving total parenteral nutrition through a tunneled central catheter is scheduled for a procedure, and the next TPN bag is unavailable from the pharmacy. Which nursing action is most appropriate?",
    "options": [
      "Flush the catheter with heparin and cap the lumen until TPN arrives",
      "Hang 0.9% sodium chloride at the same rate as the TPN",
      "Hang 10% dextrose in water at the ordered TPN rate and monitor glucose",
      "Reduce the current bag rate by half so it lasts until the new bag arrives"
    ],
    "answer": 2,
    "rationale": "Abrupt cessation of concentrated dextrose can cause rebound hypoglycemia because endogenous insulin remains elevated, so a 10% dextrose infusion is hung at the same rate as a bridge while glucose is monitored. Normal saline provides no glucose, and deliberately slowing or diluting the prescribed TPN alters the ordered nutrition and does not prevent hypoglycemia.",
    "why": [
      "Capping the line abruptly ends the concentrated dextrose infusion while endogenous insulin remains elevated, setting this client up for rebound hypoglycemia.",
      "Saline maintains line patency but supplies no glucose at all, so the client's still-circulating insulin can drive the blood sugar down sharply.",
      "Hanging 10% dextrose at the same rate bridges the gap and prevents rebound hypoglycemia from persistently elevated endogenous insulin while glucose is monitored.",
      "Deliberately halving the prescribed rate alters the ordered nutrition without a new order and still tapers glucose delivery downward, risking hypoglycemia."
    ]
  },
  {
    "id": "PH-005",
    "stem": "While a nurse is changing the injection cap on a client's subclavian central line, the client suddenly becomes dyspneic, tachycardic, and reports chest pain, and a churning murmur is auscultated. Which action should the nurse take first?",
    "options": [
      "Elevate the head of the bed to high Fowler position",
      "Obtain a stat chest x-ray to confirm catheter placement",
      "Start a 500 mL normal saline bolus through a peripheral line",
      "Clamp the catheter and place the client in left lateral Trendelenburg position"
    ],
    "answer": 3,
    "rationale": "These findings indicate air embolism; clamping the catheter stops further air entry and left lateral Trendelenburg traps air in the right ventricular apex away from the pulmonary outflow tract while oxygen is applied. Raising the head of the bed increases air entrainment risk, and imaging delays a life-threatening circulatory emergency.",
    "why": [
      "Raising the head of the bed increases air entrainment at the subclavian site rather than trapping the air that has already entered.",
      "A chest x-ray may confirm catheter position later, but imaging first delays the clamping and positioning that keep the air bolus out of the pulmonary outflow tract.",
      "Fluid does not displace intracardiac air, and volume loading through a peripheral line wastes critical minutes during a rapidly fatal circulatory emergency.",
      "Clamping stops further air entry, and left lateral Trendelenburg traps the air bolus in the right ventricular apex away from the pulmonary outflow tract."
    ]
  },
  {
    "id": "PH-006",
    "stem": "A postoperative client using morphine patient-controlled analgesia has a respiratory rate of 7 breaths/min, oxygen saturation of 86% on room air, and is difficult to arouse. Which action should the nurse take first?",
    "options": [
      "Stop the PCA, stimulate the client, and apply oxygen",
      "Administer naloxone 0.4 mg IV push immediately",
      "Reduce the PCA basal rate and continue to monitor",
      "Place the client in a side-lying position and obtain an ABG"
    ],
    "answer": 0,
    "rationale": "Airway and breathing come first: stopping the opioid source, arousing the client, and delivering oxygen can reverse mild opioid-induced respiratory depression within seconds and is fully within nursing scope. Naloxone is indicated if the client does not respond, but giving it before basic airway and oxygenation measures also risks abrupt reversal with severe pain and hemodynamic instability.",
    "why": [
      "Stopping the opioid source, stimulating the client, and applying oxygen address airway and breathing at once and lie fully within independent nursing scope.",
      "Naloxone is warranted if stimulation and oxygen fail, but giving it first risks abrupt reversal with severe postoperative pain and hemodynamic instability.",
      "Reducing the basal rate keeps opioid infusing into a client already breathing seven times a minute at 86 percent saturation; the PCA must stop entirely.",
      "An arterial blood gas only documents hypercapnia already evident from the respiratory rate and saturation, delaying oxygen and discontinuation of the opioid."
    ]
  },
  {
    "id": "PH-007",
    "stem": "A provider prescribes dopamine 5 mcg/kg/min for a client weighing 70 kg. The pharmacy supplies dopamine 400 mg in 250 mL of D5W. At what rate in mL/hr should the nurse set the infusion pump?",
    "options": [
      "9.8 mL/hr",
      "12.5 mL/hr",
      "13.1 mL/hr",
      "21 mL/hr"
    ],
    "answer": 2,
    "rationale": "The dose is 5 mcg/kg/min x 70 kg = 350 mcg/min, or 21,000 mcg/hr (21 mg/hr); the concentration is 400 mg/250 mL = 1.6 mg/mL, so 21 mg/hr divided by 1.6 mg/mL equals approximately 13.1 mL/hr. The 21 mL/hr option mistakenly treats mg/hr as mL/hr and would deliver a significantly excessive vasopressor dose.",
    "why": [
      "This figure comes from an error converting micrograms per minute to milligrams per hour and would deliver far less dopamine than the prescribed 5 mcg/kg/min.",
      "This rate reflects a weight or rounding error; 21 mg/hr against a concentration of 1.6 mg/mL does not compute to 12.5 mL/hr.",
      "5 mcg/kg/min times 70 kg equals 21 mg/hr, and dividing by the 1.6 mg/mL concentration gives approximately 13.1 mL/hr.",
      "This mistakenly treats the calculated 21 mg/hr dose as milliliters per hour, delivering roughly 60 percent more vasopressor than the provider prescribed."
    ]
  },
  {
    "id": "PH-008",
    "stem": "A client in status epilepticus is prescribed IV phenytoin 1 g loading dose. Which nursing action is essential during administration?",
    "options": [
      "Mix the phenytoin in 250 mL of 5% dextrose in water",
      "Infuse at a rate no faster than 50 mg/min with cardiac monitoring",
      "Administer through the same line as the maintenance dextrose infusion",
      "Push the dose over 2 minutes to achieve a rapid therapeutic level"
    ],
    "answer": 1,
    "rationale": "Phenytoin must be infused no faster than 50 mg/min with continuous cardiac and blood pressure monitoring because rapid administration causes hypotension, bradycardia, and asystole. Phenytoin precipitates in dextrose solutions and must be diluted and flushed with normal saline only, so dextrose-based options are unsafe.",
    "why": [
      "Phenytoin precipitates in dextrose solutions, so mixing it in D5W risks crystal formation, line occlusion, and an unreliable loading dose during status epilepticus.",
      "Limiting the rate to 50 mg/min with continuous cardiac monitoring prevents the hypotension, bradycardia, and asystole that rapid phenytoin administration causes.",
      "Running phenytoin through a line already carrying dextrose causes precipitation at the Y-site; normal saline is the only compatible flush and diluent.",
      "Pushing a 1 gram load over two minutes vastly exceeds 50 mg/min and can produce profound hypotension and cardiac arrest."
    ]
  },
  {
    "id": "PH-009",
    "stem": "A client with a serum potassium of 2.8 mEq/L has a prescription for potassium chloride 40 mEq IV. Which action by the nurse indicates safe practice?",
    "options": [
      "Administering the dose as an IV push over 5 minutes for rapid correction",
      "Adding the potassium to the existing bag already hanging at the bedside",
      "Withholding the dose until the client's urine output is documented as absent",
      "Diluting the dose and infusing it on a pump at no more than 10 mEq/hr through a patent line"
    ],
    "answer": 3,
    "rationale": "Potassium chloride is always diluted and infused by pump at a controlled rate, generally 10 mEq/hr on a general unit, because rapid delivery causes fatal dysrhythmias; IV push potassium is never acceptable. Adequate urine output should be verified before administration, so withholding for absent output is partially correct but the option as written describes confirming anuria rather than the safe administration technique.",
    "why": [
      "Intravenous push potassium is never acceptable at any rate, because the sudden myocardial concentration causes fatal dysrhythmias and cardiac arrest.",
      "Adding potassium to a bag already hanging prevents adequate mixing and can deliver a concentrated bolus, and it bypasses pharmacy preparation and labeling.",
      "Urine output should indeed be verified before giving potassium, but this option describes documented anuria, which is a reason to hold rather than a safe administration technique.",
      "Diluted potassium infused by pump at no more than 10 mEq/hr through a patent line corrects the level of 2.8 without provoking dysrhythmias."
    ]
  },
  {
    "id": "PH-010",
    "stem": "A nurse is teaching a client newly diagnosed with type 1 diabetes to mix NPH and regular insulin in one syringe. Which client statement indicates correct understanding?",
    "options": [
      "I inject air into the NPH vial first, then air into the regular vial, and draw up the regular insulin first.",
      "I draw up the cloudy NPH insulin first so it does not contaminate the clear regular insulin.",
      "I should shake both vials vigorously to make sure the insulin is completely mixed.",
      "I can mix my insulin glargine with the regular insulin the same way to save an injection."
    ],
    "answer": 0,
    "rationale": "Air is injected into the longer-acting cloudy NPH vial first, then into the regular vial, and the clear regular (short-acting) insulin is withdrawn first to prevent contaminating the regular vial with NPH. Drawing NPH first would introduce intermediate-acting insulin into the regular vial and alter its onset; glargine is never mixed with any other insulin.",
    "why": [
      "Air is injected into the cloudy NPH vial first, then the regular vial, and clear regular insulin is withdrawn first to keep NPH out of it.",
      "Drawing the NPH first contaminates the regular vial with intermediate-acting insulin, unpredictably delaying the onset of every subsequent short-acting dose.",
      "Vigorous shaking creates foam and bubbles that make accurate dosing impossible; NPH is gently rolled between the palms to resuspend it.",
      "Insulin glargine is never mixed with any other insulin, because altering its pH disrupts the slow precipitation that gives it a flat basal action."
    ]
  }
];

export default questions;
