/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "PR-001",
    "stem": "After receiving change-of-shift report on a medical unit, which client should the nurse assess first?",
    "options": [
      "A client 2 days postoperative with a temperature of 38.1 C (100.6 F)",
      "A client with a fractured hip who rates pain 7 on a 0 to 10 scale",
      "A client with COPD whose respiratory rate is 30/min, who is using accessory muscles and speaking in two-word sentences",
      "A client scheduled for discharge who needs teaching about warfarin"
    ],
    "answer": 2,
    "rationale": "Accessory muscle use with two-word dyspnea signals impending respiratory failure, which takes priority under the ABCs. Pain and a low-grade postoperative fever are important but neither is immediately life threatening, and discharge teaching can be scheduled after unstable clients are stabilized.",
    "why": [
      "A temperature of 38.1 C on postoperative day two is common, warrants assessment, but is not an immediate threat to life.",
      "Pain rated 7 deserves prompt treatment, yet pain is not immediately life threatening and can be addressed after the airway problem.",
      "Accessory muscle use with two-word dyspnea and a rate of 30/min signals impending respiratory failure, the priority under the ABCs.",
      "Warfarin discharge teaching matters but can be scheduled once unstable clients have been assessed and stabilized."
    ]
  },
  {
    "id": "PR-002",
    "stem": "The charge nurse is assigning tasks on a busy surgical unit. Which task is appropriate to delegate to unlicensed assistive personnel (UAP)?",
    "options": [
      "Assisting a stable postoperative client to ambulate in the hallway with a walker",
      "Reinforcing discharge teaching about a low-sodium diet",
      "Assessing a client's surgical incision for drainage and approximation",
      "Administering an oral pain medication to a client who is due"
    ],
    "answer": 0,
    "rationale": "Ambulating a stable client with an established plan is a standardized, predictable task within the UAP scope. Assessment, teaching, and medication administration require nursing judgment or licensure and cannot be delegated to UAP under the five rights of delegation.",
    "why": [
      "Ambulating a stable postoperative client with an established walker plan is a standardized, predictable task within the UAP scope.",
      "Reinforcing dietary teaching still requires nursing judgment about the client's understanding and cannot be delegated to unlicensed personnel.",
      "Assessing an incision for drainage and approximation is an assessment step reserved for the licensed nurse.",
      "Administering oral pain medication requires licensure, so UAP may not give it regardless of how stable the client is."
    ]
  },
  {
    "id": "PR-003",
    "stem": "A charge nurse is making assignments for a licensed practical nurse (LPN/LVN) on a medical-surgical unit. Which assignment is within the LPN's scope of practice?",
    "options": [
      "Developing the individualized plan of care for a newly admitted client",
      "Administering oral and subcutaneous medications and monitoring a stable client who has a nasogastric tube to suction",
      "Performing the initial admission assessment on a client arriving from the emergency department",
      "Titrating an intravenous heparin infusion based on aPTT results"
    ],
    "answer": 1,
    "rationale": "LPNs may administer most routine medications and monitor stable clients with established plans of care. Initial assessment, care planning, and titration of high-alert IV infusions require the RN's independent judgment and cannot be delegated.",
    "why": [
      "Developing the individualized plan of care requires the RN's independent judgment and synthesis of admission assessment data.",
      "LPNs may give oral and subcutaneous medications and monitor stable clients with established plans, including one with nasogastric suction.",
      "The initial admission assessment must be performed by the RN, who establishes the baseline and builds the plan of care.",
      "Titrating a high-alert heparin infusion against aPTT results requires RN judgment and cannot be assigned to an LPN."
    ]
  },
  {
    "id": "PR-004",
    "stem": "The unlicensed assistive personnel reports the following to the nurse. Which report requires the nurse's immediate attention?",
    "options": [
      "A client whose blood pressure is 148/86 mm Hg",
      "A client who has not voided in the 4 hours since returning from surgery",
      "A client who is requesting a snack before an early-morning laboratory draw",
      "A client who is restless and whose oxygen saturation dropped from 95% to 88% on 2 L/min nasal cannula"
    ],
    "answer": 3,
    "rationale": "A falling saturation with new restlessness is an early sign of hypoxia and is the highest priority by the ABCs. Postoperative urinary retention at 4 hours needs assessment soon, and the elevated blood pressure and the snack request are important but not immediately life threatening.",
    "why": [
      "A blood pressure of 148/86 mm Hg is mildly elevated and needs follow-up, but poses no immediate threat next to falling oxygenation.",
      "Not voiding four hours after surgery requires bladder assessment soon, yet retention is less urgent than developing hypoxia.",
      "A snack request before fasting laboratory work is a scheduling matter easily handled after urgent clinical problems.",
      "A saturation drop to 88% with new restlessness is early hypoxia, the highest priority under the ABCs, and demands immediate assessment."
    ]
  },
  {
    "id": "PR-005",
    "stem": "During triage after a multivehicle crash, which client should the nurse treat first?",
    "options": [
      "An adult with an open chest wound that bubbles with respiration and asymmetric chest rise",
      "An adult with an open femur fracture and a palpable pedal pulse",
      "An adult with a 4-cm forehead laceration and a Glasgow Coma Scale score of 15",
      "An adult with full-thickness burns over 60% of the body surface and no spontaneous respirations"
    ],
    "answer": 0,
    "rationale": "An open pneumothorax with asymmetric chest rise is an immediately correctable airway and breathing threat, making this client the highest-priority emergent case. The apneic client with 60% full-thickness burns is triaged as expectant in a mass casualty event, and the fracture and laceration are delayed or minor categories.",
    "why": [
      "An open pneumothorax with asymmetric chest rise is an immediately correctable breathing threat, making this the highest-priority emergent client.",
      "An open femur fracture with a palpable pedal pulse is urgent but delayed category, since distal circulation remains intact.",
      "A forehead laceration with a Glasgow Coma Scale of 15 is a minor injury that can safely wait for treatment.",
      "Full-thickness burns over 60% with no spontaneous respirations is triaged expectant in mass casualty events, where resources go to salvageable clients."
    ]
  },
  {
    "id": "PR-006",
    "stem": "The RN is working with an experienced LPN/LVN. Which task must the RN perform rather than delegate?",
    "options": [
      "Suctioning an established tracheostomy",
      "Inserting an indwelling urinary catheter",
      "Evaluating a client's response to the newly implemented plan of care",
      "Changing a sterile dressing on a chronic wound"
    ],
    "answer": 2,
    "rationale": "Evaluation, like assessment and care planning, is a nursing process step reserved for the RN and cannot be delegated. Tracheostomy suctioning, catheter insertion, and sterile dressing changes are technical skills within the LPN's scope when the client is stable.",
    "why": [
      "Suctioning an established tracheostomy is a technical skill within the LPN's scope when the client is stable.",
      "Inserting an indwelling urinary catheter is a sterile technical procedure LPNs are trained and licensed to perform.",
      "Evaluating the client's response to a newly implemented plan of care is a nursing process step reserved for the RN.",
      "Changing a sterile dressing on a chronic wound falls within LPN scope when the client is stable and the plan is established."
    ]
  },
  {
    "id": "PR-007",
    "stem": "A nurse from the postpartum unit is floated to a medical-surgical unit. Which client should the charge nurse assign to this nurse?",
    "options": [
      "A client receiving a packed red blood cell transfusion for an upper gastrointestinal bleed",
      "A client 1 hour after cardiac catheterization with a femoral sheath site",
      "A client on a continuous insulin infusion for diabetic ketoacidosis",
      "A client with stable cellulitis of the lower leg receiving intravenous antibiotics"
    ],
    "answer": 3,
    "rationale": "Floated nurses should receive the most stable clients with predictable outcomes and skills common to all practice settings, such as routine IV antibiotics. Transfusion reactions, post-catheterization bleeding, and insulin titration in DKA all demand specialty knowledge that a postpartum nurse may not have, creating a safety risk.",
    "why": [
      "Monitoring a transfusion during an upper GI bleed requires recognition of reaction and hemorrhage patterns outside routine postpartum practice.",
      "A femoral sheath one hour after cardiac catheterization demands specialized site, bleeding, and pulse assessment this nurse may lack.",
      "Titrating a continuous insulin infusion for diabetic ketoacidosis requires critical care knowledge unfamiliar to a postpartum nurse.",
      "Stable cellulitis treated with routine IV antibiotics is a predictable assignment using skills common to all practice settings."
    ]
  },
  {
    "id": "PR-008",
    "stem": "The nurse has just received report on four clients. Which client should the nurse assess first?",
    "options": [
      "A client with type 2 diabetes whose morning glucose is 210 mg/dL",
      "A client with a new tracheostomy who has thick secretions and audible gurgling with each breath",
      "A client with cirrhosis who has 2+ pitting edema of the lower extremities",
      "A client 1 day postoperative who reports nausea after breakfast"
    ],
    "answer": 1,
    "rationale": "Audible gurgling with thick secretions indicates a partially obstructed artificial airway, the highest priority under the ABCs, and requires immediate suctioning. Hyperglycemia, chronic edema, and postoperative nausea all need attention but none threatens airway patency.",
    "why": [
      "A morning glucose of 210 mg/dL needs treatment but is not an emergency compared with a threatened artificial airway.",
      "Audible gurgling with thick secretions through a new tracheostomy indicates partial airway obstruction requiring immediate suctioning.",
      "Two-plus pitting edema in cirrhosis is a chronic expected finding that does not threaten airway, breathing, or circulation right now.",
      "Postoperative nausea is uncomfortable and warrants an antiemetic, but it ranks well below an obstructed artificial airway."
    ]
  },
  {
    "id": "PR-009",
    "stem": "The nurse is supervising unlicensed assistive personnel on a medical unit. Which observed action requires the nurse to intervene?",
    "options": [
      "The UAP places a blood pressure cuff on the arm containing an arteriovenous fistula",
      "The UAP raises the bed to waist height before giving a bed bath",
      "The UAP records the client's intake and output at the end of the shift",
      "The UAP assists a client with denture care before a meal"
    ],
    "answer": 0,
    "rationale": "Blood pressure measurement, venipuncture, and IV access are prohibited in an extremity with an AV fistula because pressure can thrombose the access the client depends on for dialysis. The other three actions are safe, appropriate UAP tasks that support body mechanics, monitoring, and hygiene.",
    "why": [
      "Cuff pressure on the fistula extremity can thrombose the access the client depends on for dialysis, so the nurse must intervene.",
      "Raising the bed to waist height before a bed bath is correct body mechanics and needs no correction.",
      "Recording intake and output at shift end is a routine measurement task appropriately within the UAP scope.",
      "Assisting a client with denture care before a meal is basic hygiene support entirely appropriate for the UAP."
    ]
  },
  {
    "id": "PR-010",
    "stem": "A clinic nurse is returning telephone messages. Which client should the nurse call back first?",
    "options": [
      "A client taking levothyroxine who reports mild constipation",
      "A client 3 days postoperative who reports itching around the incision",
      "A client who started lisinopril yesterday and reports swelling of the lips and tongue since this morning",
      "A client with osteoarthritis asking when to take ibuprofen in relation to meals"
    ],
    "answer": 2,
    "rationale": "Lip and tongue swelling after starting an ACE inhibitor suggests angioedema, a potentially fatal airway emergency requiring immediate action. Incisional itching is a normal sign of healing, and the constipation and medication timing questions are non-urgent and can be addressed later.",
    "why": [
      "Mild constipation on levothyroxine may suggest underreplacement and merits a callback, but it carries no immediate danger.",
      "Itching around a three-day-old incision is a normal sign of healing and can be addressed after urgent calls.",
      "Lip and tongue swelling the day after starting lisinopril suggests angioedema, a potentially fatal airway emergency needing immediate action.",
      "A question about taking ibuprofen with meals is routine teaching with no time pressure attached."
    ]
  }
];

export default questions;
