/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "PS-001",
    "stem": "A client newly diagnosed with amyotrophic lateral sclerosis says, \"There is no point in any of this anymore.\" Which response by the nurse is most therapeutic?",
    "options": [
      "\"You should focus on the good years you still have ahead of you.\"",
      "\"Many people with this diagnosis live longer than expected.\"",
      "\"Would you like me to call the chaplain to talk with you?\"",
      "\"Tell me more about what you mean when you say there is no point.\""
    ],
    "answer": 3,
    "rationale": "Asking the client to elaborate uses exploration and keeps the focus on the client's feelings while allowing the nurse to assess for hopelessness and suicidal ideation. Offering false reassurance or immediately redirecting to the chaplain closes communication and avoids the client's expressed distress.",
    "why": [
      "Telling the client to focus on good years ahead is false reassurance that dismisses the hopelessness he just expressed.",
      "Quoting survival statistics shifts the conversation to facts and shuts down the client's chance to describe what he feels.",
      "A chaplain may help later, but referring now hands off the conversation instead of assessing this client's distress.",
      "Exploring what he means keeps the focus on his feelings and lets the nurse assess for hopelessness and suicidal ideation."
    ]
  },
  {
    "id": "PS-002",
    "stem": "A widow whose spouse died 14 months ago tells the nurse she still sets a place at the table for him each night, cannot return to work, and has lost 20 pounds. How should the nurse interpret these findings?",
    "options": [
      "These findings suggest complicated grief and the client should be referred for evaluation",
      "This is a normal expression of grief that requires no intervention",
      "The client is demonstrating denial, which is a healthy defense mechanism",
      "The client should be told to remove the extra place setting to promote acceptance"
    ],
    "answer": 0,
    "rationale": "Persistent functional impairment, significant weight loss, and behaviors that maintain the deceased as present more than a year later characterize complicated or prolonged grief disorder and warrant referral. Simply calling it normal or directing the client to change a behavior fails to address the underlying pathology.",
    "why": [
      "Inability to work, twenty-pound weight loss, and keeping the deceased present after 14 months indicate complicated grief needing referral.",
      "Normal grief does not usually include inability to return to work and significant weight loss more than a year after the death.",
      "Denial can be adaptive briefly, but sustained functional impairment at 14 months is pathological rather than healthy.",
      "Directing the client to remove the place setting targets one behavior without addressing the underlying prolonged grief disorder."
    ]
  },
  {
    "id": "PS-003",
    "stem": "A client admitted 36 hours ago after his last drink has a heart rate of 118, blood pressure 168/96, tremors, diaphoresis, and reports seeing bugs on the wall. Which action should the nurse take first?",
    "options": [
      "Reorient the client and dim the lights in the room",
      "Encourage the client to attend the unit alcohol support group",
      "Administer the prescribed PRN lorazepam and initiate seizure precautions",
      "Restrict visitors to reduce environmental stimulation"
    ],
    "answer": 2,
    "rationale": "Autonomic hyperactivity with hallucinations 36 hours after the last drink signals severe alcohol withdrawal that can progress to seizures and delirium tremens; benzodiazepines plus seizure precautions are the priority treatment. Environmental measures are supportive but do not address the physiologic risk of withdrawal seizures.",
    "why": [
      "Reorientation and dim lighting are helpful supportive measures but do nothing to prevent the impending withdrawal seizures.",
      "A support group belongs later in recovery; this client is physiologically unstable and hallucinating and cannot participate meaningfully now.",
      "Tachycardia, hypertension, tremor, and hallucinations at 36 hours signal severe withdrawal, so benzodiazepines and seizure precautions come first.",
      "Restricting visitors lowers stimulation but leaves the autonomic hyperactivity and risk of withdrawal seizures entirely untreated."
    ]
  },
  {
    "id": "PS-004",
    "stem": "A client on the inpatient psychiatric unit states, \"I have been saving my pills, and tonight I'm going to take them all.\" Which nursing action is the priority?",
    "options": [
      "Notify the client's family of the statement",
      "Institute one-to-one continuous observation and search for the hoarded medication",
      "Document the statement and discuss it in the morning treatment team meeting",
      "Ask the client to sign a no-suicide contract"
    ],
    "answer": 1,
    "rationale": "A client with a specific plan and available means requires immediate safety measures, including continuous observation and removal of the lethal means. No-suicide contracts have not been shown to prevent suicide and delaying action until the next team meeting leaves the client at imminent risk.",
    "why": [
      "Notifying the family may occur later, but it neither removes the hoarded pills nor keeps the client safe tonight.",
      "A specific plan with available means demands immediate one-to-one observation and removal of the hoarded lethal means.",
      "Waiting until the morning treatment team meeting leaves a client with a stated plan and pills unsupervised overnight.",
      "No-suicide contracts have no demonstrated protective effect and can give staff false reassurance while the means remain available."
    ]
  },
  {
    "id": "PS-005",
    "stem": "A nurse in the emergency department cares for a 4-year-old with a spiral fracture of the humerus. The parent states the child fell off a couch, and the nurse notes healing bruises in various stages on the child's back. What should the nurse do first?",
    "options": [
      "Confront the parent about the inconsistency in the history",
      "Ask the child privately whether the parent caused the injuries",
      "Wait for the social worker to arrive before taking any action",
      "Document the objective findings precisely and report the suspected abuse per state mandatory reporting law"
    ],
    "answer": 3,
    "rationale": "Nurses are mandatory reporters and must report reasonable suspicion of abuse based on objective findings such as injury patterns inconsistent with the reported mechanism. Confronting the caregiver may escalate danger to the child, and reporting is a legal obligation that cannot be deferred to another discipline.",
    "why": [
      "Confronting the parent may provoke escalation and further endanger the child, and investigating the history is not the nurse's role.",
      "Interrogating a four-year-old about who caused the injuries can contaminate the investigation and belongs to trained forensic interviewers.",
      "Waiting for the social worker delays a legally mandated report that this nurse is personally required to make.",
      "A spiral humerus fracture with bruises of varying ages and an inconsistent history obligates objective documentation and a mandatory abuse report."
    ]
  },
  {
    "id": "PS-006",
    "stem": "A client experiencing a panic attack is hyperventilating, pacing, and unable to follow multi-step directions. Which nursing intervention is most appropriate?",
    "options": [
      "Stay with the client and speak in short, simple sentences in a calm, low voice",
      "Leave the client alone in a quiet room until the attack subsides",
      "Explain the physiology of the panic response to help the client gain insight",
      "Encourage the client to describe the childhood events that may have caused the anxiety"
    ],
    "answer": 0,
    "rationale": "During severe or panic-level anxiety, perceptual field is markedly narrowed, so the nurse remains present and uses brief, concrete directions to promote safety and reduce stimulation. Teaching and insight-oriented exploration are ineffective at this level and are reserved for mild anxiety after the episode resolves.",
    "why": [
      "In panic-level anxiety the perceptual field narrows sharply, so staying present with brief, calm, concrete directions promotes safety and reduces stimulation.",
      "Leaving a panicking client alone removes support and increases the risk of injury while pacing during the attack.",
      "Explaining panic physiology requires cognitive processing this client cannot manage while unable to follow multi-step directions.",
      "Exploring childhood events is insight-oriented work appropriate only after anxiety has decreased to a mild level."
    ]
  },
  {
    "id": "PS-007",
    "stem": "A hospitalized client declines a prescribed transfusion, saying it conflicts with his religious beliefs. He is alert, oriented, and understands the consequences. What is the nurse's most appropriate action?",
    "options": [
      "Administer the blood because the physician ordered it",
      "Document the refusal, notify the provider, and explore acceptable alternatives with the client and health care team",
      "Ask the family to persuade the client to accept the transfusion",
      "Tell the client that religious beliefs cannot override medical treatment in a hospital"
    ],
    "answer": 1,
    "rationale": "A competent adult has the right to refuse any treatment, including on religious grounds, and the nurse's role is to document, notify the provider, and advocate for culturally and spiritually acceptable alternatives. Administering the blood anyway would constitute battery and pressuring the client through family violates autonomy.",
    "why": [
      "Transfusing a competent adult who has refused constitutes battery, regardless of the physician's order.",
      "A competent adult may refuse any treatment, so the nurse documents, notifies the provider, and advocates for acceptable alternatives.",
      "Enlisting the family to persuade him applies coercion and violates the autonomous, informed decision he already made.",
      "Telling him religious beliefs cannot override treatment is factually false and dismisses a legally protected right to refuse."
    ]
  },
  {
    "id": "PS-008",
    "stem": "A 16-year-old with anorexia nervosa weighs 38 kg, has a heart rate of 44, potassium 2.9 mEq/L, and states, \"I still feel fat.\" Which problem should the nurse address first?",
    "options": [
      "Disturbed body image related to distorted self-perception",
      "Ineffective coping related to perfectionistic thinking",
      "Risk for cardiac dysrhythmia related to bradycardia and hypokalemia",
      "Social isolation related to withdrawal from peers"
    ],
    "answer": 2,
    "rationale": "Applying Maslow and the ABCs, the life-threatening physiologic derangement of hypokalemia with bradycardia takes priority because it can precipitate fatal dysrhythmias. Body image distortion and coping are central to long-term recovery but are addressed once the client is medically stable.",
    "why": [
      "Body image distortion drives this illness and requires treatment, but it is not what threatens the client's life today.",
      "Ineffective coping is central to long-term recovery and is addressed after the client is medically stabilized.",
      "A potassium of 2.9 with a heart rate of 44 can precipitate fatal dysrhythmias, making cardiac risk the first priority.",
      "Social isolation matters for recovery but ranks well below a life-threatening electrolyte and cardiac derangement."
    ]
  },
  {
    "id": "PS-009",
    "stem": "A client arrives at the emergency department after a sexual assault, is trembling, and repeats, \"I should have fought back.\" Which response by the nurse best reflects crisis intervention principles?",
    "options": [
      "\"You did what you needed to do to survive. I will stay with you, and you decide what happens next.\"",
      "\"Try not to think about it right now; the police will need your statement soon.\"",
      "\"Why didn't you call for help while it was happening?\"",
      "\"Most survivors feel better once the evidence collection is finished.\""
    ],
    "answer": 0,
    "rationale": "Crisis intervention after sexual assault centers on safety, nonjudgmental support, and restoring the survivor's sense of control over decisions. Asking why questions implies blame, and minimizing or postponing the client's feelings undermines trust and delays psychological stabilization.",
    "why": [
      "Affirming that the client survived, staying present, and letting the client decide next steps restores safety, control, and autonomy.",
      "Telling the client not to think about it minimizes the feelings and puts the police statement ahead of emotional stabilization.",
      "Asking why the client did not call for help implies blame and deepens the self-blame already being voiced.",
      "Predicting the client will feel better after evidence collection is false reassurance that dismisses present distress."
    ]
  },
  {
    "id": "PS-010",
    "stem": "A client with schizophrenia tells the nurse, \"The voices are telling me the staff are poisoning my food.\" Which response is most therapeutic?",
    "options": [
      "\"I don't hear any voices, but I understand this is frightening for you. Are the voices telling you to harm anyone?\"",
      "\"No one here would ever poison your food; you are safe with us.\"",
      "\"What exactly are the voices saying about each staff member?\"",
      "\"You need to ignore the voices; they aren't real.\""
    ],
    "answer": 0,
    "rationale": "The nurse presents reality without arguing, validates the client's fear, and assesses for command hallucinations that could pose a safety risk. Denying the experience, arguing about the delusion, or exploring its content in detail can reinforce the false belief or escalate distress.",
    "why": [
      "This presents reality without arguing, validates the client's fear, and screens for command hallucinations that could threaten safety.",
      "Flatly denying any risk argues against the client's perception and tends to make the client feel disbelieved and more guarded.",
      "Asking for detailed content about each staff member explores the delusion and can reinforce the false belief.",
      "Telling the client to ignore voices that are not real dismisses a genuinely experienced perception and damages trust."
    ]
  }
];

export default questions;
