/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "RG-001",
    "stem": "A client in the oliguric phase of acute kidney injury has a serum potassium of 6.8 mEq/L and peaked T waves on the cardiac monitor. Which prescription should the nurse implement first?",
    "options": [
      "Sodium polystyrene sulfonate 30 g orally",
      "Furosemide 40 mg IV push",
      "Calcium gluconate 10% IV over 5 minutes",
      "Dietary consult for a potassium-restricted diet"
    ],
    "answer": 2,
    "rationale": "IV calcium gluconate does not lower potassium but immediately stabilizes the cardiac membrane against lethal dysrhythmias, which addresses the circulation priority in symptomatic hyperkalemia. Sodium polystyrene sulfonate removes potassium from the body but takes hours to work, so it cannot protect the myocardium in the moment.",
    "why": [
      "Sodium polystyrene sulfonate does remove potassium but works over hours, leaving the myocardium unprotected during the immediate risk of lethal dysrhythmias.",
      "Furosemide promotes renal potassium loss but is unreliable during the oliguric phase and does not stabilize the cardiac membrane right now.",
      "IV calcium gluconate does not lower potassium but immediately stabilizes the myocardium against lethal dysrhythmias in symptomatic hyperkalemia with peaked T waves.",
      "Dietary potassium restriction belongs to long-term management and has no effect on a potassium of 6.8 with electrocardiographic changes already present."
    ]
  },
  {
    "id": "RG-002",
    "stem": "A client with chronic kidney disease has an arteriovenous fistula in the left forearm. Which nursing action is essential?",
    "options": [
      "Palpate for a thrill and auscultate for a bruit over the fistula each shift",
      "Draw all routine laboratory specimens from the fistula arm",
      "Take blood pressures in the left arm to avoid the IV site on the right",
      "Apply a snug elastic bandage over the fistula between treatments"
    ],
    "answer": 0,
    "rationale": "A palpable thrill and audible bruit confirm patency of the fistula, and their absence signals clotting that requires immediate reporting to preserve dialysis access. Blood draws, blood pressure cuffs, and constrictive dressings on the access extremity compress the vessel and can cause thrombosis, so they are contraindicated.",
    "why": [
      "A palpable thrill and audible bruit confirm fistula patency, and their absence signals clotting that must be reported to salvage the access.",
      "Routine venipuncture in the access arm risks infection and thrombosis; the fistula is cannulated only for dialysis by specially trained staff.",
      "A blood pressure cuff compresses the fistula and can cause thrombosis, so pressures must be taken in the opposite extremity.",
      "A snug elastic bandage constricts the fistula and can occlude flow, so the access site is kept free of constrictive wraps."
    ]
  },
  {
    "id": "RG-003",
    "stem": "A client receiving continuous ambulatory peritoneal dialysis reports abdominal pain, and the nurse notes that the drained effluent is cloudy. Which action should the nurse take?",
    "options": [
      "Increase the dwell time of the next exchange",
      "Obtain a specimen of the effluent for culture and notify the provider",
      "Warm the next dialysate bag in a microwave before instilling",
      "Document the expected finding and continue exchanges"
    ],
    "answer": 1,
    "rationale": "Cloudy effluent with abdominal pain is the hallmark of peritonitis, the most common serious complication of peritoneal dialysis, and requires culture plus prompt antibiotic therapy. Treating it as an expected finding delays treatment and risks progression to sepsis and permanent membrane damage.",
    "why": [
      "Lengthening the dwell does not treat infection and would keep contaminated fluid in the peritoneum longer, allowing bacteria to multiply further.",
      "Cloudy effluent with abdominal pain is the hallmark of peritonitis, so culture and prompt provider notification allow antibiotics to begin quickly.",
      "Dialysate is warmed with dry heat, never a microwave, which heats unevenly and can burn the peritoneum, and this ignores the infection.",
      "Cloudy effluent is never an expected finding, so documenting and continuing exchanges delays antibiotic therapy and risks sepsis and membrane damage."
    ]
  },
  {
    "id": "RG-004",
    "stem": "A 5-year-old with nephrotic syndrome has generalized edema, 4+ proteinuria, and serum albumin of 1.9 g/dL. Which nursing assessment finding requires the most immediate attention?",
    "options": [
      "Weight gain of 0.5 kg over 24 hours",
      "Periorbital edema that is worse in the morning",
      "Frothy-appearing urine in the collection container",
      "Temperature of 102.2 F with abdominal tenderness"
    ],
    "answer": 3,
    "rationale": "Children with nephrotic syndrome lose immunoglobulins in the urine and are at high risk for spontaneous bacterial peritonitis, so fever with abdominal tenderness is a potentially life-threatening infection requiring immediate action. Periorbital edema on waking is a classic expected finding of the disease and is monitored rather than treated urgently.",
    "why": [
      "A half-kilogram gain in 24 hours warrants continued monitoring of fluid status but is far less urgent than signs of systemic infection.",
      "Periorbital edema that is worse on waking is a classic expected finding in nephrotic syndrome and is monitored rather than treated urgently.",
      "Frothy urine reflects the heavy proteinuria already documented and is an anticipated feature of nephrotic syndrome rather than an emergency.",
      "Urinary immunoglobulin loss predisposes to spontaneous bacterial peritonitis, so fever with abdominal tenderness signals a life-threatening infection needing immediate action."
    ]
  },
  {
    "id": "RG-005",
    "stem": "An 84-year-old resident of a long-term care facility becomes acutely confused and incontinent over 12 hours. Temperature is 99.1 F and urine is cloudy with a strong odor. Which conclusion should the nurse draw?",
    "options": [
      "The confusion is an expected consequence of aging",
      "The client is likely experiencing early dementia and needs a neurology referral",
      "New-onset confusion may be the primary presentation of a urinary tract infection in an older adult",
      "The client should be restrained until the confusion resolves"
    ],
    "answer": 2,
    "rationale": "Older adults often lack fever and dysuria, and acute change in mental status is frequently the first sign of a urinary tract infection, so a urinalysis and culture are indicated. Attributing sudden confusion to normal aging or dementia would miss an acute, treatable infection and delay antibiotics.",
    "why": [
      "Acute confusion is never a normal consequence of aging, and dismissing it as expected delays workup of a treatable acute illness.",
      "Dementia develops gradually over months to years, so a change occurring over 12 hours points to an acute cause instead.",
      "Older adults often lack fever and dysuria, so new-onset confusion with cloudy odorous urine suggests infection warranting urinalysis and culture.",
      "Restraints do not treat the underlying infection, increase agitation and injury risk, and require an order after less restrictive measures fail."
    ]
  },
  {
    "id": "RG-006",
    "stem": "A client is admitted with severe right flank pain radiating to the groin and hematuria; a CT scan confirms a 4 mm ureteral stone. Which intervention should the nurse include in the plan of care?",
    "options": [
      "Restrict oral fluids to 1,000 mL per day to reduce urine production",
      "Strain all urine and encourage fluid intake of 2.5 to 3 L per day",
      "Maintain strict bed rest until the stone passes",
      "Insert an indwelling catheter to monitor output hourly"
    ],
    "answer": 1,
    "rationale": "Straining urine captures the stone for compositional analysis that guides prevention, and generous fluid intake promotes stone passage and flushes the urinary tract. Restricting fluids concentrates urine and encourages further crystal formation, which is the opposite of the desired outcome.",
    "why": [
      "Restricting fluids concentrates the urine, promotes further crystal formation, and makes spontaneous passage of the 4 mm stone considerably less likely.",
      "Straining captures the stone for analysis that guides prevention, and 2.5 to 3 liters daily promotes passage and flushes the tract.",
      "Strict bed rest is not indicated, since ambulation helps move the stone down the ureter and prevents complications of immobility.",
      "An indwelling catheter is invasive, adds infection risk, and would trap the very stone the nurse needs to capture by straining urine."
    ]
  },
  {
    "id": "RG-007",
    "stem": "A client with benign prostatic hyperplasia begins taking tamsulosin. Which instruction is most important for the nurse to provide?",
    "options": [
      "Expect your urine to turn bright orange while on this drug",
      "Take the medication with a full glass of grapefruit juice",
      "Stop the medication as soon as your urinary stream improves",
      "Rise slowly from sitting or lying because this drug can cause dizziness and fainting"
    ],
    "answer": 3,
    "rationale": "Tamsulosin is an alpha-1 blocker that relaxes smooth muscle in the bladder neck and also causes vasodilation, producing orthostatic hypotension and first-dose syncope, so fall prevention teaching is the safety priority. Stopping the drug when symptoms improve would allow obstruction to recur, since the medication controls rather than cures the condition.",
    "why": [
      "Orange discoloration of urine occurs with phenazopyridine or rifampin, not tamsulosin, so this instruction is factually inaccurate for this drug.",
      "Grapefruit juice can raise drug levels and deepen the hypotensive effect, so it should be avoided rather than deliberately taken with tamsulosin.",
      "Tamsulosin controls rather than cures prostatic obstruction, so stopping it once the stream improves allows symptoms and retention to return.",
      "Alpha-1 blockade causes vasodilation with orthostatic hypotension and first-dose syncope, making slow position changes the essential fall-prevention instruction."
    ]
  },
  {
    "id": "RG-008",
    "stem": "The nurse is supervising a nursing assistant caring for a client with an indwelling urinary catheter. Which observed action requires the nurse to intervene?",
    "options": [
      "The assistant places the drainage bag on the bed beside the client during transport",
      "The assistant secures the catheter tubing to the client's thigh",
      "The assistant performs perineal care with soap and water",
      "The assistant empties the drainage bag when it is two-thirds full"
    ],
    "answer": 0,
    "rationale": "Raising the drainage bag to or above bladder level allows contaminated urine to reflux into the bladder, markedly increasing the risk of catheter-associated urinary tract infection, so the nurse must intervene. Securing the tubing to the thigh is correct practice because it prevents traction and urethral trauma.",
    "why": [
      "A bag at or above bladder level lets contaminated urine reflux back, so the nurse must intervene to prevent catheter-associated infection.",
      "Securing the tubing to the thigh is correct practice that prevents traction on the urethra and accidental dislodgement, so no intervention is needed.",
      "Perineal care with soap and water is the recommended method for reducing periurethral bacteria, so this action requires no correction.",
      "Emptying the bag at two-thirds full is appropriate, since bags are emptied before they overfill and strain the closed drainage system."
    ]
  },
  {
    "id": "RG-009",
    "stem": "A client with stage 4 chronic kidney disease is prescribed calcium acetate. Which instruction should the nurse give about this medication?",
    "options": [
      "Take it at bedtime on an empty stomach",
      "Take it 1 hour before meals to increase absorption",
      "Take it with each meal to bind phosphorus in food",
      "Take it only on dialysis days"
    ],
    "answer": 2,
    "rationale": "Calcium acetate is a phosphate binder that must be present in the gut with food to bind dietary phosphorus and lower serum phosphate levels. Taking it on an empty stomach or before meals leaves no phosphorus available to bind, making the therapy ineffective and allowing renal osteodystrophy to progress.",
    "why": [
      "Taking it at bedtime on an empty stomach leaves no dietary phosphorus in the gut to bind, so serum phosphate remains elevated.",
      "Calcium acetate is not meant to be absorbed, and dosing an hour before meals separates it from the phosphorus it must bind.",
      "As a phosphate binder, calcium acetate must be present in the gut with food to bind dietary phosphorus and lower serum phosphate.",
      "Phosphorus is consumed every day, so limiting the binder to dialysis days lets phosphate accumulate and renal osteodystrophy progress."
    ]
  },
  {
    "id": "RG-010",
    "stem": "A client on hemodialysis three times weekly asks about food choices. Which selection indicates the client understands the prescribed restrictions?",
    "options": [
      "Baked potato with skin, banana, and orange juice",
      "Canned soup, processed lunch meat, and dill pickles",
      "Cantaloupe, dried apricots, and tomato juice",
      "White rice, green beans, and a small serving of grilled chicken"
    ],
    "answer": 3,
    "rationale": "White rice, green beans, and a controlled portion of protein are appropriately low in potassium, phosphorus, and sodium for a client on hemodialysis. Potatoes, bananas, and orange juice are all high-potassium foods that could precipitate life-threatening hyperkalemia between dialysis treatments.",
    "why": [
      "Potato with skin, banana, and orange juice are all high-potassium foods that could precipitate dangerous hyperkalemia between dialysis treatments.",
      "Canned soup, processed lunch meat, and pickles are extremely high in sodium and phosphate additives, worsening thirst, fluid gain, and hypertension.",
      "Cantaloupe, dried apricots, and tomato juice are concentrated potassium sources and are specifically discouraged for clients receiving hemodialysis.",
      "White rice, green beans, and a small portion of chicken keep potassium, phosphorus, and sodium within the prescribed dialysis limits."
    ]
  }
];

export default questions;
