/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "RE-001",
    "stem": "A client with severe COPD and chronic carbon dioxide retention is receiving oxygen at 2 L/min by nasal cannula with an oxygen saturation of 90%. The client reports increased dyspnea, and a family member has turned the oxygen up to 6 L/min. The client is now drowsy and difficult to arouse. What should the nurse do first?",
    "options": [
      "Remove the oxygen entirely and encourage pursed-lip breathing",
      "Return the oxygen to the prescribed rate and assess respiratory rate and level of consciousness",
      "Place the client in Trendelenburg position and administer a bronchodilator",
      "Obtain a sputum specimen for culture and sensitivity"
    ],
    "answer": 1,
    "rationale": "Excessive oxygen in a chronic retainer can blunt respiratory drive and worsen hypercapnia with resulting somnolence, so returning to the prescribed flow while reassessing breathing and neurologic status addresses the cause directly. Removing oxygen completely would cause dangerous hypoxemia, which is more immediately lethal than hypercapnia.",
    "why": [
      "Removing oxygen entirely from a client with severe COPD causes profound hypoxemia, which is more immediately lethal than the hypercapnia excess oxygen produced.",
      "Returning to the prescribed 2 L/min addresses the excess oxygen blunting respiratory drive, and reassessing rate and consciousness gauges the response.",
      "Trendelenburg pushes abdominal contents against the diaphragm and worsens ventilation in a drowsy client who is already retaining carbon dioxide.",
      "A sputum culture investigates infection, which is not the cause of this sudden change, and collecting it delays correcting the oxygen-induced hypoventilation."
    ]
  },
  {
    "id": "RE-002",
    "stem": "A client having an acute asthma exacerbation initially had loud expiratory wheezing throughout all lung fields. After 20 minutes of nebulized albuterol, the nurse notes markedly diminished breath sounds, a respiratory rate of 34/min, and use of accessory muscles. How should the nurse interpret this change?",
    "options": [
      "The albuterol has effectively relieved the bronchospasm",
      "The client is developing a spontaneous pneumothorax on the left",
      "The client should be encouraged to rest before the next treatment",
      "Airflow is severely obstructed and the client requires immediate intervention"
    ],
    "answer": 3,
    "rationale": "A silent or markedly diminished chest with continued tachypnea and accessory muscle use means too little air is moving to generate wheezes, an ominous sign of impending respiratory failure requiring rapid escalation. Interpreting the loss of wheezing as improvement is a classic and dangerous error because the work of breathing has increased, not decreased.",
    "why": [
      "Genuine relief would bring easier breathing with a falling respiratory rate, not the tachypnea and accessory muscle use this client now shows.",
      "Pneumothorax produces unilaterally absent sounds with possible tracheal deviation, whereas this client's breath sounds are diminished throughout all fields.",
      "Pausing for rest in a client using accessory muscles at 34 breaths per minute allows progression toward respiratory arrest rather than recovery.",
      "Loss of wheezing with continued tachypnea and accessory muscle use means too little air is moving to generate sound, signaling impending respiratory failure."
    ]
  },
  {
    "id": "RE-003",
    "stem": "A nurse discovers that a client's chest tube has become disconnected from the drainage system tubing at the bedside. What should the nurse do first?",
    "options": [
      "Submerge the end of the chest tube in a container of sterile water",
      "Clamp the chest tube near the insertion site and call the provider",
      "Reconnect the tubing without cleaning it and tape the connection",
      "Remove the chest tube and apply an occlusive dressing"
    ],
    "answer": 0,
    "rationale": "Placing the tube end in sterile water immediately reestablishes a water seal, preventing atmospheric air from entering the pleural space while a new sterile system is obtained. Prolonged clamping traps air and can cause a tension pneumothorax, and the nurse never removes a chest tube.",
    "why": [
      "Submerging the tube end in sterile water immediately reestablishes a water seal, blocking atmospheric air from entering the pleural space until a new system arrives.",
      "Clamping a chest tube traps air within the pleural space and can convert the problem into a tension pneumothorax.",
      "Reconnecting contaminated tubing introduces organisms directly into the pleural space and creates a serious risk of empyema.",
      "Removing a chest tube is outside nursing scope and would collapse the very lung the tube is treating."
    ]
  },
  {
    "id": "RE-004",
    "stem": "Three days after hip replacement surgery, a client suddenly reports sharp pleuritic chest pain and dyspnea. Vital signs are respirations 32/min, heart rate 124/min, blood pressure 100/62 mm Hg, and oxygen saturation 87% on room air. What should the nurse do first?",
    "options": [
      "Obtain a stat D-dimer and troponin",
      "Encourage slow deep breathing into a paper bag",
      "Apply high-flow oxygen and elevate the head of the bed",
      "Ambulate the client to improve lung expansion"
    ],
    "answer": 2,
    "rationale": "This presentation strongly suggests pulmonary embolism, and correcting hypoxemia with oxygen and an upright position addresses airway and breathing before diagnostics are pursued. Rebreathing into a bag would worsen hypoxemia, and ambulating a hemodynamically compromised client can dislodge additional thrombus.",
    "why": [
      "A D-dimer and troponin support the diagnosis but do nothing for a saturation of 87 percent; oxygenation precedes diagnostic testing.",
      "Rebreathing into a paper bag is used for anxiety-related hyperventilation and would deepen the hypoxemia in a client already at 87 percent.",
      "High-flow oxygen with the head elevated treats the hypoxemia of a likely pulmonary embolism, addressing breathing before diagnostics are pursued.",
      "Ambulating a hypoxemic, tachycardic client with a suspected embolism can dislodge more thrombus and worsen the hemodynamic compromise."
    ]
  },
  {
    "id": "RE-005",
    "stem": "A nurse is suctioning a client with a new tracheostomy. Which action indicates correct technique?",
    "options": [
      "Instilling 5 mL of normal saline into the tracheostomy before each pass",
      "Applying suction only while withdrawing the catheter, for no more than 10 to 15 seconds",
      "Suctioning continuously for 30 seconds to clear thick secretions",
      "Setting wall suction at 200 mm Hg for adult clients"
    ],
    "answer": 1,
    "rationale": "Suction is applied only on withdrawal and limited to 10 to 15 seconds per pass to minimize hypoxemia and mucosal trauma. Routine saline instillation is not evidence based and increases infection risk, and prolonged suctioning at excessive pressure causes hypoxemia, bradycardia, and airway injury.",
    "why": [
      "Routine saline instillation is not evidence based; it triggers coughing and desaturation and can wash organisms deeper into the lower airway.",
      "Applying suction only during withdrawal for 10 to 15 seconds limits the hypoxemia and tracheal mucosal trauma that suctioning causes.",
      "Thirty seconds of continuous suction removes oxygen along with secretions and can cause hypoxemia, bradycardia, and dysrhythmias.",
      "Adult wall suction should be set near 80 to 120 mm Hg; 200 mm Hg causes mucosal trauma and bleeding in a new tracheostomy."
    ]
  },
  {
    "id": "RE-006",
    "stem": "A client is admitted with a productive cough, night sweats, hemoptysis, and a 15 lb weight loss over 2 months, and pulmonary tuberculosis is suspected. Which action should the nurse take first?",
    "options": [
      "Begin four-drug antitubercular therapy immediately",
      "Obtain three consecutive early-morning sputum specimens",
      "Place the client in a negative-pressure room and use an N95 respirator",
      "Administer a tuberculin skin test and read it in 48 hours"
    ],
    "answer": 2,
    "rationale": "Tuberculosis spreads by the airborne route, so implementing airborne precautions in a negative-pressure room with N95 protection prevents transmission to staff and other clients while the workup proceeds. Sputum collection and skin testing are necessary but come after isolation, and treatment is not started before specimens are obtained.",
    "why": [
      "Antitubercular therapy is delayed until sputum specimens are collected so the organism can be identified and drug susceptibility determined.",
      "Three early-morning specimens are essential to diagnosis, but collecting them before isolation exposes staff and other clients to airborne bacilli.",
      "Tuberculosis spreads by the airborne route, so a negative-pressure room with N95 protection shields staff and other clients while the workup proceeds.",
      "A tuberculin skin test cannot distinguish active disease from latent infection and takes 48 hours, offering nothing for an actively coughing client."
    ]
  },
  {
    "id": "RE-007",
    "stem": "A client with acute respiratory distress syndrome is intubated on mechanical ventilation with 100% FiO2 and PEEP of 15 cm H2O. The nurse notes a sudden drop in blood pressure from 112/68 to 78/44 mm Hg with rising peak airway pressures and absent breath sounds on the right. Which complication is most likely?",
    "options": [
      "Ventilator-associated pneumonia",
      "Right mainstem intubation with left lung collapse",
      "Tension pneumothorax",
      "Acute pulmonary edema"
    ],
    "answer": 2,
    "rationale": "High PEEP predisposes to barotrauma, and the triad of hypotension, rising peak airway pressures, and unilaterally absent breath sounds indicates a tension pneumothorax requiring immediate needle decompression. Ventilator-associated pneumonia develops over days with fever and infiltrates rather than sudden hemodynamic collapse.",
    "why": [
      "Ventilator-associated pneumonia develops over days with fever and infiltrates, not sudden hypotension with unilaterally absent breath sounds.",
      "Right mainstem intubation would silence the left lung, but this client's absent breath sounds are on the right side.",
      "High PEEP predisposes to barotrauma, and hypotension with rising peak airway pressures and absent right breath sounds indicates tension pneumothorax needing needle decompression.",
      "Acute pulmonary edema produces diffuse crackles and pink frothy secretions rather than unilaterally absent breath sounds with a sudden pressure drop."
    ]
  },
  {
    "id": "RE-008",
    "stem": "An 82-year-old client is brought to the emergency department by family who report new confusion and a fall. Temperature is 37.1 C, respirations 28/min, oxygen saturation 89% on room air, and crackles are auscultated in the right lower lobe. Which conclusion should guide the nurse's next action?",
    "options": [
      "The findings suggest pneumonia, since older adults often present with confusion instead of fever",
      "The confusion is most likely age-related dementia requiring a safety sitter only",
      "The normal temperature effectively rules out a respiratory infection",
      "The crackles are an expected finding in an adult of this age"
    ],
    "answer": 0,
    "rationale": "Older adults frequently present with altered mental status and tachypnea rather than fever, and the focal crackles with hypoxemia point to pneumonia requiring oxygen, cultures, and antibiotics. Attributing the change to dementia or dismissing the absent fever would delay treatment of a life-threatening infection.",
    "why": [
      "Older adults often present with confusion and tachypnea instead of fever, and focal right lower lobe crackles with a saturation of 89 percent point to pneumonia.",
      "Attributing new acute confusion to dementia ignores the hypoxemia and focal crackles and would delay antibiotics for a treatable infection.",
      "A blunted febrile response is common in older adults, so a temperature of 37.1 C does not exclude pneumonia in this client.",
      "Focal crackles confined to one lobe are never a normal aging change and here indicate consolidation requiring prompt treatment."
    ]
  },
  {
    "id": "RE-009",
    "stem": "A client with an acute COPD exacerbation has these arterial blood gases: pH 7.30, PaCO2 58 mm Hg, HCO3 28 mEq/L, PaO2 62 mm Hg. Which nursing action is most appropriate?",
    "options": [
      "Prepare for immediate intubation regardless of clinical status",
      "Withhold all oxygen therapy until the PaCO2 normalizes",
      "Encourage rapid deep breaths to blow off carbon dioxide quickly",
      "Position upright, coach pursed-lip breathing, and prepare for noninvasive positive pressure ventilation"
    ],
    "answer": 3,
    "rationale": "These gases show acute-on-chronic respiratory acidosis with hypoxemia, and upright positioning with pursed-lip breathing plus BiPAP improves alveolar ventilation and often avoids intubation. Withholding oxygen leaves dangerous hypoxemia untreated, and rapid deep breathing causes air trapping in obstructive disease rather than CO2 clearance.",
    "why": [
      "Intubation is reserved for failure of noninvasive support or deteriorating consciousness, so committing to it regardless of clinical status is unnecessarily invasive.",
      "Withholding oxygen at a PaO2 of 62 leaves the client hypoxemic, which is more immediately dangerous than the elevated carbon dioxide.",
      "Rapid deep breathing shortens expiratory time and causes air trapping in obstructive disease, raising rather than lowering the carbon dioxide.",
      "Upright positioning with pursed-lip breathing and BiPAP improves alveolar ventilation in this acute-on-chronic respiratory acidosis and often prevents the need for intubation."
    ]
  },
  {
    "id": "RE-010",
    "stem": "A nurse is teaching a client how to use an incentive spirometer after abdominal surgery. Which client statement indicates correct understanding?",
    "options": [
      "I should blow into the mouthpiece as hard and fast as I can.",
      "I will inhale slowly and deeply, hold it for about 3 to 5 seconds, then exhale and cough.",
      "I only need to use this device if I start feeling short of breath.",
      "I should use it once each morning and once before bed."
    ],
    "answer": 1,
    "rationale": "A slow sustained maximal inspiration with a brief inspiratory hold reopens alveoli and prevents atelectasis, and the follow-up cough clears secretions. Forceful exhalation into the device does not expand alveoli, and using it only when symptomatic or twice daily is far less than the recommended 10 breaths every hour while awake.",
    "why": [
      "Forceful exhalation into the device is peak flow technique and does not inflate alveoli or prevent postoperative atelectasis after abdominal surgery.",
      "A slow deep inspiration held three to five seconds reopens collapsed alveoli, and the follow-up cough clears the secretions that were loosened.",
      "Waiting until dyspnea appears means atelectasis has already developed; the spirometer is used preventively before any symptoms occur.",
      "Twice daily use falls far below the recommended ten breaths every hour while awake and will not prevent postoperative atelectasis."
    ]
  }
];

export default questions;
