/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "RR-001",
    "stem": "Two hours after a right femoral cardiac catheterization, a client reports increasing fullness in the groin. The nurse finds a 6 cm firm swelling at the site, heart rate 118/min, and blood pressure 88/52 mm Hg. What should the nurse do first?",
    "options": [
      "Reposition the client on the left side and reassess in 15 minutes",
      "Instruct the client to flex the right leg to relieve pressure",
      "Apply firm manual pressure above the puncture site and call the provider",
      "Mark the edges of the swelling and continue routine monitoring"
    ],
    "answer": 2,
    "rationale": "An expanding groin hematoma with tachycardia and hypotension indicates arterial bleeding and impending hypovolemic shock, so direct pressure proximal to the puncture site controls hemorrhage while help is summoned. Marking the site or repositioning delays hemostasis, and flexing the affected extremity is contraindicated after femoral access.",
    "why": [
      "Repositioning does nothing to compress a bleeding femoral artery, and a fifteen-minute delay allows further blood loss in a client already hypotensive.",
      "Flexing the accessed extremity is contraindicated after femoral catheterization because it disrupts the puncture site and increases bleeding into the groin.",
      "Firm pressure proximal to the puncture compresses the bleeding artery immediately, and the tachycardia with hypotension means the provider is needed now.",
      "Marking the edges is useful for a stable hematoma, but with a heart rate of 118 and pressure of 88/52 routine monitoring delays urgently needed hemostasis."
    ]
  },
  {
    "id": "RR-002",
    "stem": "A client with heart failure taking digoxin and furosemide has these morning labs: potassium 3.0 mEq/L, sodium 138 mEq/L, digoxin level 1.6 ng/mL, creatinine 1.0 mg/dL. Which result requires the most immediate follow-up?",
    "options": [
      "Potassium 3.0 mEq/L",
      "Sodium 138 mEq/L",
      "Digoxin level 1.6 ng/mL",
      "Creatinine 1.0 mg/dL"
    ],
    "answer": 0,
    "rationale": "Hypokalemia potentiates digoxin binding at the myocardial cell and can precipitate life-threatening dysrhythmias even when the digoxin level is therapeutic (0.5 to 2 ng/mL). The digoxin level itself is within range and the sodium and creatinine are normal, so they do not require urgent intervention.",
    "why": [
      "Potassium of 3.0 potentiates digoxin binding at the myocardial cell and can trigger lethal dysrhythmias even when the digoxin level is therapeutic.",
      "Sodium of 138 mEq/L falls within the normal range of 135 to 145 and requires no follow-up in this client.",
      "A digoxin level of 1.6 ng/mL sits within the therapeutic range of 0.5 to 2, so it is not the most urgent result.",
      "Creatinine of 1.0 mg/dL is normal and indicates adequate renal clearance of both the digoxin and the furosemide."
    ]
  },
  {
    "id": "RR-003",
    "stem": "Six hours after a total thyroidectomy, a client reports a sensation of tightness in the neck and difficulty swallowing. The dressing is dry, but the nurse notes the neck circumference has increased. Which action is the priority?",
    "options": [
      "Loosen the dressing and document the finding",
      "Assess the airway and notify the surgeon immediately",
      "Check the Trousseau and Chvostek signs for hypocalcemia",
      "Elevate the head of the bed and apply an ice collar"
    ],
    "answer": 1,
    "rationale": "Neck tightness with increasing circumference after thyroidectomy suggests deep hematoma formation that can compress the trachea, so airway assessment and immediate surgeon notification take priority under the ABC framework. Hypocalcemia is a real post-thyroidectomy complication but is not an immediate airway threat, and comfort measures do not address the expanding bleed.",
    "why": [
      "Loosening the dressing may relieve superficial constriction but does nothing about a deep hematoma compressing the trachea, and documenting alone delays rescue.",
      "Increasing neck circumference with tightness after thyroidectomy suggests an expanding hematoma that can compress the trachea, so airway assessment and surgeon notification come first.",
      "Hypocalcemia is a genuine post-thyroidectomy complication worth assessing later, but tetany is not the immediate airway threat these findings describe.",
      "Elevation and an ice collar are reasonable comfort measures but will not stop an expanding bleed or relieve tracheal compression."
    ]
  },
  {
    "id": "RR-004",
    "stem": "A client on lithium for bipolar disorder reports 3 days of vomiting and diarrhea and now has coarse hand tremors, slurred speech, and unsteady gait. The lithium level is 2.1 mEq/L. Which action should the nurse anticipate?",
    "options": [
      "Administering the next scheduled lithium dose with extra fluids",
      "Restricting sodium intake to promote lithium excretion",
      "Encouraging a low-fluid diet to concentrate the drug",
      "Holding the lithium and preparing the client for possible hemodialysis"
    ],
    "answer": 3,
    "rationale": "A level above 2.0 mEq/L with neurologic signs is severe lithium toxicity; the drug is held and hemodialysis may be required for definitive removal. Sodium and fluid restriction worsen toxicity because lithium is reabsorbed with sodium in the proximal tubule, and giving another dose would be dangerous.",
    "why": [
      "Giving another dose to a client already at a toxic 2.1 mEq/L with neurologic signs would deepen the toxicity and could be fatal.",
      "Sodium restriction increases lithium reabsorption in the proximal tubule, raising the serum level further rather than promoting its excretion.",
      "Restricting fluids concentrates lithium and worsens toxicity, especially in a client already volume depleted from three days of vomiting and diarrhea.",
      "A level above 2.0 with coarse tremor, slurred speech, and ataxia is severe toxicity, so lithium is held and hemodialysis may be needed."
    ]
  },
  {
    "id": "RR-005",
    "stem": "Immediately following a large-volume paracentesis in which 6 L of ascitic fluid was removed, a client's blood pressure falls from 122/76 to 86/50 mm Hg and the heart rate rises to 116/min. What is the nurse's best initial action?",
    "options": [
      "Place the client supine, monitor vital signs closely, and notify the provider",
      "Ambulate the client to promote fluid redistribution",
      "Administer the prescribed diuretic to prevent reaccumulation",
      "Reinfuse the drained ascitic fluid through a peripheral IV"
    ],
    "answer": 0,
    "rationale": "Rapid removal of large volumes of ascites causes intravascular fluid shifts and hypovolemia, so supine positioning, close monitoring, and prompt notification for volume expansion (often albumin) address the circulatory compromise. A diuretic would deepen the hypovolemia, and ambulating a hypotensive client is unsafe.",
    "why": [
      "Removing 6 L of ascites shifts fluid out of the vascular space, so supine positioning with close monitoring and prompt notification supports perfusion until albumin is ordered.",
      "Ambulating a client with a systolic pressure of 86 risks syncope and injury, and it does nothing to restore intravascular volume.",
      "A diuretic pulls still more fluid from the vascular space and would deepen the hypovolemia this client already has after the drainage.",
      "Reinfusing drained ascitic fluid through a peripheral IV is not a nursing intervention and carries serious infection and reaction risks."
    ]
  },
  {
    "id": "RR-006",
    "stem": "A client returns to the unit after a bronchoscopy performed with moderate sedation and topical lidocaine to the oropharynx. The client asks for a drink of water. Which response by the nurse is most appropriate?",
    "options": [
      "You may have small sips of water now that you are fully awake.",
      "I will bring ice chips instead, since they are safer after this test.",
      "I need to check that your gag reflex has returned before you have anything to drink.",
      "You must stay without food or fluids for 24 hours after a bronchoscopy."
    ],
    "answer": 2,
    "rationale": "Topical anesthesia suppresses the gag reflex and creates aspiration risk, so oral intake is withheld until the gag reflex is confirmed to have returned, usually within 2 hours. Ice chips carry the same aspiration risk as water, and a blanket 24-hour restriction is unnecessary and not evidence based.",
    "why": [
      "Being fully awake does not mean the gag reflex has returned; topical lidocaine leaves the airway unprotected and swallowing water risks aspiration.",
      "Ice chips melt into liquid and carry exactly the same aspiration risk as water while the gag reflex remains suppressed.",
      "Topical anesthesia to the oropharynx suppresses the gag reflex, so all intake is withheld until its return is confirmed, usually within about two hours.",
      "A blanket 24-hour restriction is far longer than needed, since the gag reflex typically returns within a couple of hours after bronchoscopy."
    ]
  },
  {
    "id": "RR-007",
    "stem": "A client with type 2 diabetes taking metformin is scheduled for a CT scan with iodinated contrast tomorrow. The serum creatinine is 1.9 mg/dL. Which action should the nurse take?",
    "options": [
      "Give the metformin with a full glass of water on the morning of the scan",
      "Hold the metformin and clarify the plan with the provider before the scan",
      "Administer an extra dose of metformin to prevent hyperglycemia during fasting",
      "Encourage the client to restrict all fluids for 12 hours before the scan"
    ],
    "answer": 1,
    "rationale": "Iodinated contrast can precipitate acute kidney injury, and with impaired renal function metformin accumulates and increases the risk of lactic acidosis, so metformin is withheld around the time of contrast and the plan is verified with the provider. Fluid restriction is the opposite of the hydration needed to protect the kidneys from contrast nephropathy.",
    "why": [
      "Giving metformin before contrast in a client with a creatinine of 1.9 allows the drug to accumulate and risks lactic acidosis.",
      "Iodinated contrast can precipitate acute kidney injury, and with a creatinine of 1.9 metformin accumulates and risks lactic acidosis, so it is held pending clarification.",
      "An extra dose compounds the accumulation risk, and metformin alone does not cause hypoglycemia that would need covering during fasting.",
      "Fluid restriction is the opposite of the hydration that protects the kidneys from contrast nephropathy and would worsen renal injury."
    ]
  },
  {
    "id": "RR-008",
    "stem": "Four hours after an open reduction and internal fixation of the femur, the nurse notes the client's blood pressure has fallen from 128/78 to 96/58 mm Hg, heart rate is 122/min, respirations 26/min, and the surgical drain has collected 350 mL of bright red drainage in the past hour. Which finding most strongly indicates hemorrhage requiring immediate follow-up?",
    "options": [
      "Respiratory rate of 26 breaths/min",
      "Complaint of incisional pain rated 6 of 10",
      "Oral temperature of 37.8 C",
      "350 mL of bright red drainage in 1 hour with narrowing pulse pressure"
    ],
    "answer": 3,
    "rationale": "Brisk bright red drainage combined with tachycardia, hypotension, and a narrowing pulse pressure is the classic pattern of ongoing surgical hemorrhage and compensated shock requiring immediate provider notification. Tachypnea is a compensatory response that is explained by the same problem, and moderate incisional pain and a low-grade temperature are expected postoperative findings.",
    "why": [
      "Tachypnea is a compensatory response to the blood loss rather than the finding that identifies the hemorrhage itself.",
      "Moderate incisional pain is expected four hours after femoral fixation and calls for analgesia, not emergency intervention.",
      "An oral temperature of 37.8 C reflects the normal inflammatory response of the early postoperative period and is not an emergency.",
      "350 mL of bright red drainage in one hour with hypotension, tachycardia, and a narrowing pulse pressure is active hemorrhage with compensated shock."
    ]
  },
  {
    "id": "RR-009",
    "stem": "A client who had a lumbar puncture 4 hours ago reports a severe throbbing headache that worsens when sitting upright and improves when lying flat. Which nursing intervention is most appropriate?",
    "options": [
      "Ambulate the client in the hallway to promote CSF circulation",
      "Restrict oral fluids to reduce cerebrospinal fluid production",
      "Keep the client flat, encourage fluids, and administer prescribed analgesia",
      "Position the client in high Fowler with the neck flexed forward"
    ],
    "answer": 2,
    "rationale": "A postural post-dural puncture headache results from CSF leakage, and lying flat with increased fluid intake and analgesia supports CSF volume restoration and comfort. Upright positioning and ambulation increase the pressure gradient and worsen the headache, and fluid restriction reduces the CSF replacement the client needs.",
    "why": [
      "Ambulation puts the client upright, increasing the pressure gradient at the puncture site and intensifying the headache rather than relieving it.",
      "Restricting fluids withholds the volume needed to replace leaked cerebrospinal fluid and will worsen rather than relieve this headache.",
      "A headache that eases when lying flat is a post-dural puncture headache from CSF leak, treated with flat positioning, fluids, and analgesia.",
      "High Fowler position reproduces exactly the upright posture that worsens this headache, and neck flexion offers no benefit after a lumbar puncture."
    ]
  },
  {
    "id": "RR-010",
    "stem": "A client receiving warfarin for atrial fibrillation has an INR of 5.8 and reports bleeding gums when brushing. There is no other active bleeding. Which prescription should the nurse anticipate?",
    "options": [
      "Hold the warfarin and administer oral vitamin K (phytonadione)",
      "Administer protamine sulfate 50 mg IV over 10 minutes",
      "Continue the current warfarin dose and recheck the INR in 1 week",
      "Give an additional dose of warfarin to stabilize the level"
    ],
    "answer": 0,
    "rationale": "An INR well above the 2 to 3 target with minor bleeding is managed by holding warfarin and giving vitamin K, the specific antidote that restores clotting factor synthesis. Protamine sulfate reverses heparin, not warfarin, and continuing or increasing the dose would raise the INR further and risk major hemorrhage.",
    "why": [
      "An INR of 5.8 with only minor bleeding is managed by holding warfarin and giving oral vitamin K to restore clotting factor synthesis.",
      "Protamine sulfate reverses heparin, not warfarin, so it would have no effect on this client's markedly elevated INR.",
      "Continuing the dose leaves the INR nearly double the upper target for another week and risks progression to major hemorrhage.",
      "Additional warfarin further suppresses clotting factor synthesis and would push an already dangerous INR of 5.8 even higher."
    ]
  }
];

export default questions;
