/* Generated by scripts/import-question-bank.mjs — do not edit by hand. */
import type { BankQuestion } from "./types";

const questions: BankQuestion[] = [
  {
    "id": "SE-001",
    "stem": "A registered nurse on a busy medical-surgical unit must delegate tasks to an unlicensed assistive personnel (UAP). Which task is appropriate for the RN to delegate to the UAP?",
    "options": [
      "Performing the admission assessment on a client just arrived from the emergency department",
      "Obtaining a routine set of vital signs on a stable client 2 days postoperative from a hernia repair",
      "Teaching a newly diagnosed diabetic client how to self-administer insulin",
      "Evaluating whether a client's pain improved after receiving morphine 30 minutes ago"
    ],
    "answer": 1,
    "rationale": "Delegation rules permit the UAP to perform standardized, predictable tasks such as vital signs on a stable client. Admission assessment, teaching, and evaluation of a medication response all require nursing judgment and cannot be delegated because assessment, planning, and evaluation steps of the nursing process remain the RN's responsibility.",
    "why": [
      "Admission assessment requires nursing judgment and interpretation of data, so it belongs to the RN and cannot be handed to unlicensed personnel.",
      "Vital signs on a stable postoperative client are a standardized, predictable task with a known routine, squarely within UAP training and scope.",
      "Insulin self-administration teaching is client education, a nursing responsibility that unlicensed assistive personnel are neither licensed nor trained to perform.",
      "Judging whether morphine relieved the pain is evaluation of a medication response, a nursing process step the RN must retain."
    ]
  },
  {
    "id": "SE-002",
    "stem": "A client scheduled for a laparoscopic cholecystectomy tells the nurse, \"I signed the consent, but I still don't understand what they are going to remove.\" What is the nurse's best action?",
    "options": [
      "Explain the surgical procedure in detail using a diagram",
      "Reassure the client that the surgeon is highly experienced",
      "Notify the surgeon so the procedure can be explained before the client goes to the operating room",
      "Document that the client is anxious and continue preoperative preparation"
    ],
    "answer": 2,
    "rationale": "Informed consent requires that the provider performing the procedure disclose its nature, risks, and alternatives; the nurse witnesses the signature and verifies understanding. Explaining the procedure herself would exceed the nurse's role, so the correct action is to stop the process and notify the surgeon to complete the disclosure.",
    "why": [
      "Explaining the surgical procedure in detail exceeds the nurse's role; disclosure of nature, risks, and alternatives belongs to the operating surgeon.",
      "Praising the surgeon's experience is false reassurance that ignores the knowledge gap and leaves the consent legally invalid.",
      "The client's statement shows consent was not informed, so the surgeon must return and complete the disclosure before surgery proceeds.",
      "Charting anxiety and continuing preparation sends the client to the operating room without informed consent, a legal and ethical failure."
    ]
  },
  {
    "id": "SE-003",
    "stem": "Four clients are waiting to be seen at the start of the shift. Which client should the charge nurse assign the registered nurse to assess first?",
    "options": [
      "A client with new-onset shortness of breath and an oxygen saturation of 87% on room air",
      "A client requesting pain medication for incisional pain rated 7 of 10",
      "A client whose IV site is due to be rotated per policy",
      "A client asking for discharge instructions before leaving in 2 hours"
    ],
    "answer": 0,
    "rationale": "Airway and breathing problems take precedence under the ABC framework, and a saturation of 87% signals hypoxemia requiring immediate intervention. Pain, IV rotation, and discharge teaching are important but do not pose an immediate physiologic threat, so they are addressed after the respiratory issue is resolved.",
    "why": [
      "A saturation of 87% with new dyspnea is a breathing problem under the ABCs and signals hypoxemia needing immediate intervention.",
      "Pain rated 7 of 10 deserves prompt treatment, but incisional pain is not an immediate physiologic threat and follows the hypoxemic client.",
      "Routine IV site rotation is a scheduled policy task that can safely wait until the hypoxemic client has been assessed.",
      "Discharge teaching matters, but the client is not leaving for two hours, making this the least urgent of the four."
    ]
  },
  {
    "id": "SE-004",
    "stem": "A client with terminal cancer has a valid advance directive stating no cardiopulmonary resuscitation. The adult daughter arrives and insists, \"You have to do everything if his heart stops.\" What is the nurse's most appropriate response?",
    "options": [
      "\"I will change the code status now since you are next of kin.\"",
      "\"Your father cannot make decisions anymore, so we follow your wishes.\"",
      "\"I will ask the provider to write a full code order to avoid a conflict.\"",
      "\"Your father's advance directive guides his care; let's talk with the provider together about his wishes.\""
    ],
    "answer": 3,
    "rationale": "A valid advance directive expresses the competent client's own wishes and legally directs care; a family member cannot override it while it remains valid. Acknowledging the daughter's distress and arranging a discussion with the provider supports the client's autonomy while addressing the family's emotional needs.",
    "why": [
      "The nurse cannot unilaterally change code status, and next of kin cannot override a valid advance directive written by the client.",
      "This is factually wrong; the directive was created while the client was competent and continues to express his wishes now.",
      "Requesting a full code order simply to avoid family conflict overrides the client's documented wishes and violates his autonomy.",
      "Upholding the directive while inviting the daughter into a conversation with the provider protects client autonomy and addresses her distress."
    ]
  },
  {
    "id": "SE-005",
    "stem": "A nurse overhears two staff members discussing a hospitalized client's HIV status in a crowded elevator. Which action should the nurse take first?",
    "options": [
      "Report the staff members to the state board of nursing",
      "Document the names of everyone in the elevator",
      "Ask the staff members to stop the conversation and move to a private area",
      "Notify the client that the disclosure occurred"
    ],
    "answer": 2,
    "rationale": "Protecting confidentiality requires immediately stopping the ongoing breach, which is accomplished by asking the staff to end the discussion in a public area. Reporting through the chain of command may follow, but it does not stop the disclosure that is happening at that moment.",
    "why": [
      "Reporting to the state board skips the chain of command and does nothing about the breach happening in the elevator right now.",
      "Recording the names of bystanders documents the breach but does not stop the confidential information still being disclosed.",
      "Stopping the conversation and moving it to a private area immediately halts the ongoing confidentiality breach, which is the first priority.",
      "Informing the client may be appropriate later through facility process, but it does not interrupt the disclosure occurring at this moment."
    ]
  },
  {
    "id": "SE-006",
    "stem": "The registered nurse is planning assignments for a licensed practical/vocational nurse (LPN/LVN) on a medical unit. Which client is most appropriate to assign to the LPN/LVN?",
    "options": [
      "A client receiving the first dose of IV vancomycin",
      "A stable client with heart failure requiring daily weights and oral furosemide administration",
      "A client newly admitted with chest pain and an unread 12-lead ECG",
      "A client receiving blood product transfusion started 10 minutes ago"
    ],
    "answer": 1,
    "rationale": "LPN/LVN scope typically includes administering oral medications and monitoring stable clients with predictable outcomes. First-dose IV antibiotics, unstable chest pain admissions, and the initiation phase of blood transfusion require the RN's assessment and judgment in most facilities.",
    "why": [
      "A first dose of IV vancomycin carries risk of hypersensitivity and infusion reactions, requiring RN assessment and close monitoring.",
      "A stable heart failure client needing daily weights and oral furosemide has predictable outcomes well within LPN/LVN scope of practice.",
      "New chest pain with an unread ECG is an unstable, unpredictable situation demanding RN assessment and rapid clinical judgment.",
      "The first minutes of a transfusion are when reactions occur, so the RN must monitor during the initiation phase."
    ]
  },
  {
    "id": "SE-007",
    "stem": "A client with a new colostomy is being discharged home alone and expresses difficulty managing the appliance. Which action by the nurse best demonstrates appropriate continuity of care?",
    "options": [
      "Provide written instructions and instruct the client to call the clinic with questions",
      "Ask the family to visit daily to change the appliance",
      "Delay the discharge until the client changes the appliance without help",
      "Initiate a referral for home health nursing and an enterostomal therapy consult"
    ],
    "answer": 3,
    "rationale": "Coordinating a home health and ostomy specialist referral extends professional support into the home and addresses the identified self-care deficit. Written instructions alone do not ensure competence, and delaying discharge is not necessary when community resources can meet the need.",
    "why": [
      "Written instructions alone neither build skill nor confirm competence in a client who has already voiced difficulty managing the appliance.",
      "Assigning appliance changes to family ignores the client's own self-care goal and assumes availability and willingness that were never established.",
      "Holding discharge until the client is fully independent is unnecessarily restrictive when community resources can support continued learning at home.",
      "Home health and enterostomal therapy referrals extend professional teaching and support into the home, directly addressing the identified self-care deficit."
    ]
  },
  {
    "id": "SE-008",
    "stem": "A nurse discovers that a colleague documented a full head-to-toe assessment on a client the colleague never saw. What is the nurse's priority action?",
    "options": [
      "Report the falsified documentation to the nurse manager",
      "Ask the colleague to correct the entry before the end of shift",
      "Assess the client personally and say nothing further",
      "Write an anonymous note to the risk management department"
    ],
    "answer": 0,
    "rationale": "Falsified documentation is a legal and safety issue that must be reported through the appropriate chain of command, beginning with the nurse manager. Allowing a peer to quietly amend the record or handling it anonymously fails the nurse's duty to advocate for client safety and accurate records.",
    "why": [
      "Falsified documentation is a legal and client-safety violation that must be reported up the chain of command to the nurse manager.",
      "Asking the colleague to quietly fix the entry conceals falsification and makes the nurse complicit in an inaccurate legal record.",
      "Assessing the client is appropriate, but saying nothing leaves fabricated data in the permanent record and the behavior unaddressed.",
      "An anonymous note bypasses the chain of command and prevents any follow-up, verification, or accountability for the concern."
    ]
  },
  {
    "id": "SE-009",
    "stem": "During a change-of-shift handoff for a client transferred from the intensive care unit, which information is most important for the nurse to communicate?",
    "options": [
      "The client's food preferences and family visiting pattern",
      "The client's insurance authorization status",
      "The current vasoactive drip rate, most recent blood pressure, and pending laboratory results",
      "The name of the admitting physician and the room number"
    ],
    "answer": 2,
    "rationale": "Effective handoff communication prioritizes current physiologic status, active high-alert therapies, and pending results that will drive imminent decisions. Demographic and administrative details are useful but do not affect immediate client safety during the transition of care.",
    "why": [
      "Food preferences and visiting patterns support comfort planning but do not influence immediate safety decisions during this transfer.",
      "Insurance authorization is an administrative detail with no bearing on the client's physiologic stability at the moment of handoff.",
      "The active vasoactive drip rate, latest blood pressure, and pending labs drive the imminent decisions the receiving nurse must make.",
      "Physician name and room number are routine identifiers already in the record and carry no urgent clinical weight during handoff."
    ]
  },
  {
    "id": "SE-010",
    "stem": "A client hospitalized with a stroke has slurred speech and a swallowing deficit and lives alone in a second-floor walk-up apartment. Which action by the case-managing nurse is most appropriate?",
    "options": [
      "Request a psychiatric consultation for adjustment to disability",
      "Arrange for the client to be discharged with a family member's phone number",
      "Schedule a follow-up appointment in the neurology clinic in 6 weeks",
      "Coordinate an interprofessional discharge conference with speech therapy, physical therapy, and social work"
    ],
    "answer": 3,
    "rationale": "Case management for complex post-stroke needs requires coordinating an interprofessional plan that addresses dysphagia, mobility, and the unsafe home environment before discharge. A single clinic appointment weeks later leaves the immediate aspiration and fall risks unmanaged.",
    "why": [
      "Psychiatric consultation may help later with adjustment, but it does nothing about the immediate dysphagia, mobility, and stair-climbing hazards.",
      "A family member's phone number is not a discharge plan and leaves aspiration and fall risks completely unmanaged at home.",
      "Neurology follow-up is appropriate, but six weeks is far too delayed to address needs that exist the day of discharge.",
      "An interprofessional conference addresses swallowing, mobility, and the second-floor walk-up together before discharge, which is the case manager's role."
    ]
  },
  {
    "id": "SE-011",
    "stem": "A client is admitted with a productive cough, night sweats, weight loss, and a chest x-ray showing upper lobe cavitation. Which action should the nurse take first?",
    "options": [
      "Obtain three sputum specimens for acid-fast bacillus testing",
      "Administer the first dose of isoniazid and rifampin",
      "Place the client in an airborne infection isolation room and apply a fit-tested N95 respirator before entering",
      "Notify the local public health department of a suspected case"
    ],
    "answer": 2,
    "rationale": "Suspected pulmonary tuberculosis requires immediate airborne precautions in a negative-pressure room with N95 respiratory protection to prevent transmission to staff and other clients. Sputum collection, medications, and public health notification are all necessary but occur after the transmission risk is contained.",
    "why": [
      "Sputum for acid-fast bacillus testing is essential to diagnosis, but collecting it before isolation exposes staff to airborne organisms.",
      "Treatment should not start before specimens are collected, and giving medication does nothing to stop transmission in the meantime.",
      "Cavitary upper lobe disease with night sweats suggests tuberculosis, so airborne isolation and N95 protection must precede every other action.",
      "Public health notification is legally required but occurs after the client is isolated and the transmission risk has been contained."
    ]
  },
  {
    "id": "SE-012",
    "stem": "A client with Clostridioides difficile infection has frequent watery stools. Which action by the nursing student requires the instructor to intervene?",
    "options": [
      "Wearing a gown and gloves to enter the client's room",
      "Cleaning the client's bedside table with an alcohol-based wipe",
      "Using a dedicated stethoscope kept in the client's room",
      "Washing hands with soap and water after removing gloves"
    ],
    "answer": 1,
    "rationale": "C. difficile spores are not killed by alcohol; environmental surfaces require a sporicidal agent such as a bleach-based disinfectant. Gown and gloves, dedicated equipment, and soap-and-water handwashing are all correct components of contact precautions for this organism.",
    "why": [
      "Gown and gloves are precisely what contact precautions require for C. difficile, so this needs no correction from the instructor.",
      "Alcohol does not kill C. difficile spores; surfaces require a sporicidal bleach-based disinfectant, so the instructor must intervene here.",
      "A dedicated stethoscope kept in the room prevents cross contamination and is standard practice under contact precautions.",
      "Soap and water physically removes spores that alcohol-based rubs cannot kill, making this the correct hand hygiene choice."
    ]
  },
  {
    "id": "SE-013",
    "stem": "A nurse is leaving the room of a client on contact and droplet precautions. In which order should the nurse remove personal protective equipment?",
    "options": [
      "Mask, gloves, goggles, gown",
      "Gown, gloves, goggles, mask",
      "Goggles, mask, gown, gloves",
      "Gloves, goggles, gown, mask"
    ],
    "answer": 3,
    "rationale": "The most contaminated item, the gloves, is removed first, followed by eye protection and gown, with the mask removed last outside the room to maintain respiratory protection until the nurse has left. Removing the mask early exposes the mucous membranes to droplets still present in the room.",
    "why": [
      "Removing the mask first exposes the mucous membranes to droplets still in the room and leaves contaminated gloves on longest.",
      "Taking the gown off before gloves contaminates the hands and clothing, since gloves are the dirtiest item and must come off first.",
      "Starting with goggles leaves contaminated gloves on while working near the face and removes the mask before leaving the room.",
      "Gloves are most contaminated and come off first, followed by goggles and gown, with the mask removed last outside the room."
    ]
  },
  {
    "id": "SE-014",
    "stem": "An older adult client with delirium repeatedly pulls at the endotracheal tube despite reorientation, a bed alarm, and a family member at the bedside. A provider order for soft wrist restraints is obtained. Which nursing action is correct?",
    "options": [
      "Assess the extremity for circulation, motion, and sensation and release the restraints at least every 2 hours",
      "Tie the restraint straps to the side rails so they move with the bed",
      "Keep the restraints in place continuously until the client is extubated",
      "Obtain a PRN restraint order to use whenever the night shift is short staffed"
    ],
    "answer": 0,
    "rationale": "Restraints require frequent neurovascular assessment and periodic release with repositioning and toileting to prevent injury and preserve skin integrity. Restraints must never be tied to movable side rails, PRN restraint orders are prohibited, and restraints require ongoing evaluation for the earliest possible discontinuation.",
    "why": [
      "Restrained limbs need regular circulation, motion, and sensation checks with release at least every two hours for repositioning and skin care.",
      "Straps tied to side rails move with the rail and can tighten or injure the client whenever the rail is raised or lowered.",
      "Continuous restraint without release or reassessment causes skin breakdown and neurovascular injury and ignores the mandate for earliest possible discontinuation.",
      "PRN restraint orders are prohibited, and staffing shortages are never a legitimate justification for restraining a client."
    ]
  },
  {
    "id": "SE-015",
    "stem": "A 78-year-old client admitted with syncope takes furosemide and zolpidem and scored high on the fall risk screening tool. Which intervention should the nurse implement first?",
    "options": [
      "Request that a family member remain at the bedside overnight",
      "Keep the bed in the lowest position with the call light within reach and a bed exit alarm activated",
      "Apply a vest restraint at night to prevent the client from getting up",
      "Place the client in a room farthest from the nurses' station to reduce noise"
    ],
    "answer": 1,
    "rationale": "Environmental modifications such as a low bed, accessible call light, and an activated bed alarm are the least restrictive, evidence-based first-line fall interventions. Restraints actually increase injury risk and are never a first-line fall prevention measure, and moving the client away from the station reduces surveillance.",
    "why": [
      "Relying on a family member to stay overnight is unreliable and shifts responsibility for this client's safety away from nursing staff.",
      "A low bed, reachable call light, and activated exit alarm are the least restrictive evidence-based measures the nurse can implement immediately.",
      "Vest restraints increase the risk of serious injury and strangulation and are never a first-line fall prevention strategy.",
      "A room farthest from the nurses' station reduces surveillance of a high-risk client taking furosemide and zolpidem after syncope."
    ]
  },
  {
    "id": "SE-016",
    "stem": "A nurse is setting up a sterile field for a dressing change. Which observation indicates that the sterile field has been contaminated?",
    "options": [
      "The nurse holds sterile gloved hands above waist level",
      "The nurse opens the outermost flap of the sterile package away from the body",
      "A bottle of sterile saline is poured with the label facing the palm",
      "The nurse turns away from the field to answer a question and then returns"
    ],
    "answer": 3,
    "rationale": "A sterile field must remain within the nurse's direct line of sight at all times; turning away means it can no longer be considered sterile. Holding hands above the waist, opening the far flap first, and palming the solution label are all correct sterile technique practices.",
    "why": [
      "Keeping sterile gloved hands above waist level and in view is correct sterile technique, not evidence of contamination.",
      "Opening the outermost flap away from the body prevents reaching across the field and is the proper opening sequence.",
      "Palming the label keeps solution from running onto it and is standard practice when pouring sterile saline.",
      "A sterile field must remain in the nurse's direct line of sight; turning away means it can no longer be considered sterile."
    ]
  },
  {
    "id": "SE-017",
    "stem": "A client receiving chemotherapy has an absolute neutrophil count of 380/mm3. Which instruction should the nurse include in the plan of care?",
    "options": [
      "Avoid fresh, uncooked fruits and vegetables and fresh flowers or plants in the room",
      "Use a soft toothbrush and avoid flossing to prevent gum bleeding",
      "Limit fluid intake to 1000 mL per day to reduce fluid overload",
      "Wear a surgical mask at all times while alone in the private room"
    ],
    "answer": 0,
    "rationale": "Severe neutropenia requires protective environment measures that limit exposure to environmental organisms, including avoidance of raw produce, flowers, and standing water. A soft toothbrush addresses thrombocytopenia rather than neutropenia, and fluid restriction is not indicated for this problem.",
    "why": [
      "An absolute neutrophil count of 380 means severe neutropenia, so raw produce, flowers, and plants that harbor organisms must be avoided.",
      "A soft toothbrush and avoiding floss address bleeding from thrombocytopenia, not the infection risk created by a low neutrophil count.",
      "Fluid restriction is unrelated to neutropenia and could worsen dehydration and impair renal clearance of chemotherapy agents.",
      "Masking applies when the neutropenic client leaves the room or others enter, not while the client is alone in a private room."
    ]
  },
  {
    "id": "SE-018",
    "stem": "A college student is admitted with fever, nuchal rigidity, and a petechial rash, and bacterial meningitis is suspected. Which precaution should the nurse initiate?",
    "options": [
      "Standard precautions only",
      "Airborne precautions with a negative-pressure room",
      "Droplet precautions with a surgical mask worn within 3 feet of the client",
      "Protective environment with positive-pressure airflow"
    ],
    "answer": 2,
    "rationale": "Neisseria meningitidis is transmitted by large respiratory droplets, so droplet precautions with a surgical mask are indicated until 24 hours of effective antibiotic therapy have been completed. Airborne precautions and a negative-pressure room are reserved for tuberculosis, measles, and varicella.",
    "why": [
      "Standard precautions alone will not prevent droplet spread of Neisseria meningitidis to staff, visitors, and other clients.",
      "Airborne precautions with negative pressure are reserved for tuberculosis, measles, and varicella, not for meningococcal disease.",
      "Fever, nuchal rigidity, and a petechial rash suggest meningococcal meningitis, spread by large droplets requiring a mask within three feet.",
      "A protective environment with positive airflow shields immunocompromised clients from outside organisms; it does not contain this client's droplets."
    ]
  },
  {
    "id": "SE-019",
    "stem": "A nurse prepares to administer heparin and notices the vial is labeled 10,000 units/mL while the order reads 5,000 units subcutaneously. Which action best reflects error prevention practice?",
    "options": [
      "Administer 0.5 mL and document the dose given",
      "Withhold the dose and notify the pharmacy that the order is wrong",
      "Ask the client whether this is the usual dose received at home",
      "Verify the calculated dose with a second nurse before administration, per high-alert medication policy"
    ],
    "answer": 3,
    "rationale": "Heparin is a high-alert medication that requires independent double-check of the dose and concentration by a second nurse to intercept calculation errors before they reach the client. Proceeding alone or relying on the client's recollection does not meet the standard for high-alert medication safety.",
    "why": [
      "The calculation may be right, but giving a high-alert drug without an independent double check skips a required safety barrier.",
      "The order is not wrong; only the vial concentration differs, and withholding the anticoagulant needlessly delays prescribed therapy.",
      "The client's recollection of a home dose is not a verification method and cannot validate this order or vial concentration.",
      "Heparin is a high-alert medication, so independent second-nurse verification of dose and concentration intercepts calculation errors before administration."
    ]
  },
  {
    "id": "SE-020",
    "stem": "A chemotherapy agent spills on the floor of a client's room. Which action should the nurse take first?",
    "options": [
      "Wipe the spill with absorbent towels and place them in the regular trash",
      "Restrict access to the area and obtain the chemotherapy spill kit before cleanup",
      "Call environmental services to mop the area with detergent",
      "Open the window and move the client to a chair across the room"
    ],
    "answer": 1,
    "rationale": "Hazardous drug spills require containment of the area and use of a designated spill kit with appropriate PPE before any cleanup begins, protecting staff and clients from cytotoxic exposure. Routine cleaning methods and disposal in regular trash violate hazardous materials handling requirements.",
    "why": [
      "Wiping a cytotoxic spill with ordinary towels and discarding them in regular trash exposes staff and violates hazardous waste rules.",
      "Restricting access and obtaining the designated chemotherapy spill kit with proper PPE must precede any cleanup of a cytotoxic agent.",
      "Environmental services staff are not trained or equipped for cytotoxic spills, and detergent mopping only spreads the hazardous drug.",
      "Moving the client is reasonable, but opening a window is not spill control and cleanup still requires the spill kit first."
    ]
  }
];

export default questions;
