/**
 * Compiles everything Mailroom renders from into lib/content.generated.ts:
 * email templates and their images (internal/email/templates, internal/email/onboarding)
 * and the Nursia question bank (src/lib/bank).
 *
 * Run after editing a template or the bank: `npm run content`.
 * Compiled in, rather than read at runtime, so a Vercel function never has to
 * find a file next to it.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const out = join(here, "..", "lib", "content.generated.ts");

const html = {};
const assets = {};
const MIME = { ".png": "image/png", ".jpg": "image/jpeg", ".gif": "image/gif", ".svg": "image/svg+xml" };

function collect(dir, prefix) {
  for (const f of readdirSync(dir)) {
    if (f.endsWith(".html")) html[`${prefix}/${f.replace(/\.html$/, "")}`] = readFileSync(join(dir, f), "utf8");
  }
  const a = join(dir, "assets");
  if (existsSync(a)) for (const f of readdirSync(a)) {
    if (MIME[extname(f)]) assets[`${prefix}/assets/${f}`] = { mime: MIME[extname(f)], base64: readFileSync(join(a, f)).toString("base64") };
  }
}

collect(join(repo, "internal", "email", "templates", "nursia"), "nursia");
collect(join(repo, "internal", "email", "templates", "prepclever"), "prepclever");
collect(join(repo, "internal", "email", "onboarding"), "onboarding");

/* The bank files are generated TS whose array is plain JSON. */
const bankDir = join(repo, "src", "lib", "bank");
const bank = [];
for (const f of readdirSync(bankDir)) {
  if (!f.endsWith(".ts") || ["types.ts", "loaders.ts", "counts.ts"].includes(f)) continue;
  const src = readFileSync(join(bankDir, f), "utf8");
  const start = src.indexOf("[", src.indexOf("= "));
  const end = src.lastIndexOf("];");
  const topic = f.replace(/\.ts$/, "");
  for (const q of JSON.parse(src.slice(start, end + 1))) bank.push({ topic, ...q });
}

writeFileSync(
  out,
  `/* Generated by scripts/sync-content.mjs — run \`npm run content\`, don't edit. */
export const TEMPLATE_HTML: Record<string, string> = ${JSON.stringify(html)};
export const ASSETS: Record<string, { mime: string; base64: string }> = ${JSON.stringify(assets)};
export type BankQuestion = { topic: string; id: string; stem: string; options: string[]; answer: number; rationale: string; why: string[] };
export const NURSIA_BANK: BankQuestion[] = ${JSON.stringify(bank)};
`,
);
console.log(`templates ${Object.keys(html).length}, assets ${Object.keys(assets).length}, questions ${bank.length}`);
