import type { Entity } from "./taxonomy";

/**
 * The second half of the clinical index.
 *
 * Split from `taxonomy.ts` for the boring reason: one file holding eight
 * hundred hand-written entries is a file nobody opens to add the eight hundred
 * and first. The two are merged at import and are one index as far as every
 * consumer is concerned — the topic keys here must exist there.
 *
 * This half exists because the first one was unbalanced in a way that only
 * showed up when the planner counted it. Pharmacology is the largest single
 * category on the NCLEX test plan and had twenty-six entries, fewer than
 * cardiovascular; prioritisation and delegation, which is most of what the
 * clinical-judgement items actually test, had twelve. The first pass was
 * written body system by body system, which is how a nurse learns anatomy and
 * not how the exam is weighted.
 *
 * Every entry here follows the same rule as the first half: a real thing a
 * nurse must know, with one specific clinical hook. Nothing was added to reach
 * a number — where a topic is genuinely small, it stayed small.
 */
export const EXTRA_INDEX: Record<string, Entity[]> = {
  /* ------------------------------------------------------------ pharmacology */
  pharmacology: [
    { name: "Loop Diuretics", kind: "drug", aka: ["furosemide", "bumetanide"], hook: "Give in the morning or the patient is up all night, and the ototoxicity comes from pushing it too fast." },
    { name: "Thiazide Diuretics", kind: "drug", aka: ["hydrochlorothiazide"], hook: "They waste potassium and retain calcium, which is the opposite of what most people assume about a diuretic." },
    { name: "Potassium-Sparing Diuretics", kind: "drug", aka: ["spironolactone"], hook: "Hyperkalaemia is the risk, so no salt substitutes — they are potassium chloride." },
    { name: "Angiotensin Receptor Blockers", kind: "drug", aka: ["losartan", "valsartan"], hook: "The answer when an ACE inhibitor caused a cough, and the angioedema risk does not fully disappear." },
    { name: "Alpha Blockers", kind: "drug", aka: ["tamsulosin", "doxazosin"], hook: "First-dose syncope is real — take it at bedtime and rise slowly." },
    { name: "Antiplatelet Agents", kind: "drug", aka: ["clopidogrel", "aspirin"], hook: "Bleeding time rather than INR, and they are held before surgery on a schedule that differs by drug." },
    { name: "Direct Oral Anticoagulants", kind: "drug", aka: ["apixaban", "rivaroxaban"], hook: "No routine monitoring, which patients hear as no risk — the teaching is about missed doses and bleeding." },
    { name: "Thrombolytics", kind: "drug", hook: "A short window and a long contraindication list, and any recent bleed or surgery ends the conversation." },
    { name: "Insulin Pump Therapy", kind: "procedure", hook: "A pump failure becomes DKA within hours because there is no long-acting depot." },
    { name: "DPP-4 Inhibitors", kind: "drug", aka: ["sitagliptin"], hook: "Weight-neutral and low hypoglycaemia risk, which is why they are chosen for older patients." },
    { name: "SGLT2 Inhibitors", kind: "drug", aka: ["empagliflozin"], hook: "Glucose in the urine means genital fungal infection, and euglycaemic DKA is the one that gets missed." },
    { name: "Bisphosphonates", kind: "drug", aka: ["alendronate"], hook: "Upright for 30 minutes with a full glass of water — oesophageal erosion is the reason, not absorption." },
    { name: "Thyroid Replacement Monitoring", kind: "concept", hook: "TSH is rechecked six weeks after any dose change, not sooner — the axis takes that long to settle." },
    { name: "Antifungals", kind: "drug", aka: ["fluconazole", "amphotericin B"], hook: "Amphotericin B is nicknamed shake and bake for the infusion reaction, and it is nephrotoxic." },
    { name: "Macrolides", kind: "drug", aka: ["azithromycin", "erythromycin"], hook: "QT prolongation and a long list of interactions through the liver enzymes." },
    { name: "Fluoroquinolones", kind: "drug", aka: ["ciprofloxacin", "levofloxacin"], hook: "Tendon rupture, especially with steroids and over 60 — and they chelate with dairy and antacids." },
    { name: "Tetracyclines", kind: "drug", aka: ["doxycycline"], hook: "Not in pregnancy or under eight — it stains developing teeth permanently. Photosensitivity too." },
    { name: "Sulfonamides", kind: "drug", aka: ["trimethoprim-sulfamethoxazole"], hook: "Stevens-Johnson syndrome is the reaction to name, and plenty of fluids prevent crystalluria." },
    { name: "Antituberculars Monitoring", kind: "concept", hook: "Isoniazid causes peripheral neuropathy, which pyridoxine prevents — a standard co-prescription." },
    { name: "Muscle Relaxants", kind: "drug", aka: ["cyclobenzaprine", "baclofen"], hook: "Sedation plus fall risk, and baclofen is never stopped abruptly in a patient with spasticity." },
    { name: "Antigout Agents", kind: "drug", aka: ["allopurinol", "colchicine"], hook: "Allopurinol prevents and colchicine treats — starting allopurinol during an attack makes it worse." },
    { name: "Bronchodilator Sequencing", kind: "concept", hook: "Bronchodilator first, wait five minutes, then the steroid — so the steroid reaches an open airway." },
    { name: "Laxatives", kind: "drug", aka: ["docusate", "senna", "polyethylene glycol"], hook: "Stool softener is not a stimulant, and a patient on opioids needs both." },
    { name: "Antidiarrheals", kind: "drug", aka: ["loperamide"], hook: "Contraindicated in C. difficile and in infectious diarrhoea — trapping the toxin causes toxic megacolon." },
    { name: "Anticoagulation in Pregnancy", kind: "concept", hook: "Heparin does not cross the placenta and warfarin does, which decides the drug for the whole pregnancy." },
    { name: "Antipsychotic Monitoring", kind: "concept", hook: "Metabolic syndrome with the second generation: weight, glucose and lipids at baseline and on a schedule." },
    { name: "Stimulants", kind: "drug", aka: ["methylphenidate", "amphetamine"], hook: "Given after breakfast to limit appetite suppression, and growth is plotted in children on them." },
    { name: "Opioid Antagonists", kind: "drug", aka: ["naloxone", "naltrexone"], hook: "Naloxone has a shorter half-life than most opioids, so the patient can re-sedate after it wears off." },
    { name: "Patient-Controlled Analgesia", kind: "procedure", aka: ["PCA"], hook: "Only the patient presses the button — family dosing is a sentinel event, and the teaching says so plainly." },
    { name: "Topical and Transdermal Medications", kind: "procedure", hook: "Remove the old patch before applying the new one, and gloves — absorbing a fentanyl patch is a real staff injury." },
    { name: "Eye and Ear Drops", kind: "procedure", hook: "Conjunctival sac not the cornea, pressure on the inner canthus, and ear drops warmed to body temperature." },
    { name: "Enteral Medication Administration", kind: "procedure", hook: "Never crush an enteric-coated or extended-release tablet — it delivers the whole day's dose at once." },
    { name: "Intramuscular Injection Sites", kind: "procedure", hook: "Ventrogluteal is the safest adult site, vastus lateralis for infants, and the dorsogluteal is no longer used." },
    { name: "Subcutaneous Injection", kind: "procedure", hook: "45 to 90 degrees by tissue depth, and heparin is never aspirated or massaged." },
    { name: "Z-Track Technique", kind: "procedure", hook: "For irritating drugs like iron dextran — the displaced tissue seals the track and stops staining." },
    { name: "Medication Reconciliation", kind: "skill", hook: "At every transition, and the omissions are the over-the-counter drugs and the eye drops patients forget." },
    { name: "Adverse Drug Reactions in Older Adults", kind: "concept", aka: ["Beers criteria"], hook: "Anticholinergics, benzodiazepines and NSAIDs cause most of it, and the presenting sign is often a fall." },
    { name: "Pregnancy Drug Categories", kind: "concept", hook: "Teratogen risk peaks in the first trimester, which is often before the pregnancy is known." },
    { name: "Chemotherapy Side Effect Management", kind: "concept", hook: "Nausea is prevented rather than treated — the antiemetic goes before the infusion." },
    { name: "Extravasation of Vesicants", kind: "condition", hook: "Stop the infusion, leave the cannula in and aspirate — pulling it out removes the only access to the drug." },
    { name: "Antiemetic Selection", kind: "concept", hook: "The cause picks the drug: motion is anticholinergic, chemotherapy is a 5-HT3 blocker, and they are not interchangeable." },
    { name: "Drug Half-Life and Steady State", kind: "concept", hook: "Five half-lives to steady state, which is why a dose change is not judged the next morning." },
    { name: "First-Pass Metabolism", kind: "concept", hook: "It is why the oral dose of a drug is far larger than the IV dose of the same drug." },
    { name: "Enzyme Inducers and Inhibitors", kind: "concept", hook: "Rifampin induces and grapefruit inhibits, and both change the level of a drug nobody adjusted." },
    { name: "Narrow Therapeutic Index Drugs", kind: "concept", hook: "The gap between working and toxic is small enough that a missed level is a clinical event." },
    { name: "Placebo and Nocebo", kind: "concept", hook: "Expectation changes reported outcomes, which is why how a drug is introduced is part of giving it." },
    { name: "Vaccine Administration", kind: "procedure", hook: "Live vaccines are spaced four weeks apart if not given together, and the site and route differ by product." },
    { name: "Anaphylaxis Drug Management", kind: "concept", hook: "Epinephrine intramuscular first, then airway, then the antihistamine and steroid that do nothing acutely." },
    { name: "Antidote Administration", kind: "procedure", hook: "Acetylcysteine for paracetamol works best inside eight hours and is still given late." },
    { name: "Electrolyte Replacement", kind: "procedure", hook: "IV potassium is never pushed and never exceeds the protocol rate — it is the classic fatal error." },
    { name: "Total Parenteral Nutrition Additives", kind: "concept", hook: "Nothing is added to a TPN bag on the ward, and it runs on a dedicated line." },
    { name: "Medication Storage and Stability", kind: "concept", hook: "Insulin in use is room temperature for 28 days, and refrigerating the pen the patient carries is wrong." },
    { name: "Controlled Substance Handling", kind: "concept", hook: "Two-nurse waste with documentation at the time, not at the end of the shift." },
    { name: "Verbal and Telephone Orders", kind: "skill", hook: "Read back and verify, and it is emergencies only — the write-down-read-back is the safeguard." },
    { name: "Polypharmacy", kind: "concept", hook: "Every new symptom in an older adult is a drug side effect until that is excluded." },
    { name: "Immunosuppressant Monitoring", kind: "concept", hook: "Trough levels drive the dose, and grapefruit and St John's wort move them enough to reject a graft." },
  ],

  /* ---------------------------------------------------------------- med-surg */
  "med-surg": [
    { name: "Malignant Hyperthermia", kind: "condition", hook: "Rising end-tidal CO2 is the earliest sign, before the temperature — and dantrolene is drawn up while someone calls." },
    { name: "Postoperative Atelectasis", kind: "condition", hook: "The commonest cause of a day-one fever, and the treatment is the incentive spirometer nobody used." },
    { name: "Paralytic Ileus", kind: "condition", hook: "Absent bowel sounds with distension after abdominal surgery — and it is nothing by mouth until they return." },
    { name: "Dehiscence and Evisceration", kind: "condition", hook: "Cover with sterile saline-soaked gauze, low Fowler's with knees bent, and do not push anything back in." },
    { name: "Fat Embolism Syndrome", kind: "condition", hook: "A petechial rash with confusion and dyspnoea 24–72 hours after a long-bone fracture." },
    { name: "Thyroidectomy Care", kind: "procedure", hook: "Tracheostomy set and calcium gluconate at the bedside — airway and tetany are the two emergencies." },
    { name: "Mastectomy Care", kind: "procedure", hook: "No blood pressure, no blood draws and no injections in the affected arm, and lymphoedema precautions are lifelong." },
    { name: "Amputation Care", kind: "procedure", hook: "Phantom pain is real and is treated; a tourniquet stays at the bedside for the first 24 hours." },
    { name: "Spinal Surgery Care", kind: "procedure", hook: "Log roll, and new numbness or weakness is reported immediately rather than observed." },
    { name: "Prostatectomy Care", kind: "procedure", hook: "Continuous bladder irrigation titrated to keep the drainage pink, and the output calculation subtracts the irrigant." },
    { name: "Cataract Surgery", kind: "procedure", hook: "No bending, no lifting, no straining — the teaching is about pressure rather than about the eye." },
    { name: "Glaucoma", kind: "condition", hook: "Peripheral vision goes first and painlessly in the open-angle form; acute closed-angle is an emergency with a fixed mid-dilated pupil." },
    { name: "Macular Degeneration", kind: "condition", hook: "Central vision is lost and peripheral is kept — the exact opposite of glaucoma, which is the exam's pairing." },
    { name: "Hearing Loss", kind: "condition", aka: ["presbycusis"], hook: "Face the patient, speak low-pitched rather than loud — shouting raises the frequency they have already lost." },
    { name: "Ménière Disease", kind: "condition", hook: "Vertigo, tinnitus and hearing loss together, and a low-sodium diet is a genuine intervention." },
    { name: "Psoriasis", kind: "condition", hook: "It is not contagious and the psychosocial impact is the part that goes unassessed." },
    { name: "Cellulitis", kind: "condition", hook: "Mark the border with a pen — spread beyond the mark is the objective sign of failure to respond." },
    { name: "Herpes Zoster", kind: "condition", aka: ["shingles"], hook: "Airborne and contact precautions until crusted, and a pregnant or immunocompromised nurse does not take the assignment." },
    { name: "Thyroid Cancer", kind: "condition", hook: "After radioactive iodine the patient is briefly a radiation source, and the precautions are time, distance and shielding." },
    { name: "Multiple Myeloma", kind: "condition", hook: "Bone pain with hypercalcaemia and renal failure — and fluids are the first nursing priority." },
    { name: "Thrombocytopenia", kind: "condition", hook: "Soft toothbrush, electric razor, no rectal temperatures — bleeding precautions are a standing order." },
    { name: "Disseminated Intravascular Coagulation", kind: "condition", aka: ["DIC"], hook: "Clotting and bleeding at once, which is why it looks contradictory until you look at the platelets and fibrinogen." },
    { name: "Neutropenic Fever", kind: "condition", hook: "A single temperature of 38.3°C is an emergency with antibiotics inside an hour." },
    { name: "Tumour Lysis Syndrome", kind: "condition", hook: "High potassium, phosphate and uric acid after chemotherapy starts — hydration and allopurinol prevent it." },
    { name: "Superior Vena Cava Syndrome", kind: "condition", hook: "Facial swelling and distended neck veins in a lung cancer patient — sit them upright and escalate." },
    { name: "Spinal Cord Compression", kind: "condition", hook: "New back pain in a cancer patient is cord compression until imaging says otherwise — hours decide walking." },
    { name: "Hypercalcaemia of Malignancy", kind: "condition", hook: "Confusion and constipation with a high calcium, and saline plus a bisphosphonate is the treatment." },
    { name: "Chronic Pain Management", kind: "concept", hook: "Tolerance is not addiction and dependence is not addiction, and conflating them is how pain goes untreated." },
    { name: "Obesity and Surgical Risk", kind: "concept", hook: "Wound healing, positioning injury and respiratory complications all rise, and the equipment has to be sized in advance." },
    { name: "Frailty and Surgical Outcome", kind: "concept", hook: "Frailty predicts postoperative complications better than age does, and it is measurable before the decision." },
    { name: "Wound Drains", kind: "procedure", aka: ["Jackson-Pratt", "Hemovac"], hook: "Compress to re-establish suction after emptying, and record the output per drain rather than in total." },
    { name: "Negative Pressure Wound Therapy", kind: "procedure", aka: ["VAC"], hook: "The seal is the therapy — a leaking dressing is doing nothing at all." },
    { name: "Debridement", kind: "procedure", hook: "Sharp, enzymatic, autolytic and mechanical each suit a different wound, and stable eschar on a heel is left alone." },
    { name: "Skin Grafting", kind: "procedure", hook: "The donor site often hurts more than the graft, and the graft is immobilised for it to take." },
  ],

  /* ---------------------------------------------------------- cardiovascular */
  cardiovascular: [
    { name: "Ventricular Fibrillation", kind: "condition", hook: "No pulse, no output — defibrillate immediately, and this is the rhythm that makes the AED worth having." },
    { name: "Ventricular Tachycardia", kind: "condition", hook: "With a pulse it is antiarrhythmics or cardioversion; without one it is defibrillation, and checking is the step people skip." },
    { name: "Asystole", kind: "condition", hook: "Not a shockable rhythm — CPR and adrenaline, and confirming it in a second lead." },
    { name: "Heart Blocks", kind: "condition", hook: "First degree is a long PR and nothing else; third degree is complete dissociation and a pacemaker." },
    { name: "Supraventricular Tachycardia", kind: "condition", aka: ["SVT"], hook: "Vagal manoeuvres first, then adenosine — and warn the patient adenosine feels like dying for six seconds." },
    { name: "Cardiac Arrest Management", kind: "procedure", aka: ["ACLS"], hook: "High-quality compressions with minimal interruption beats every drug in the algorithm." },
    { name: "Defibrillation and Cardioversion", kind: "procedure", hook: "Cardioversion is synchronised and defibrillation is not, and getting it backwards induces the arrest." },
    { name: "Therapeutic Hypothermia", kind: "procedure", hook: "After cardiac arrest it protects the brain, and shivering is suppressed because it defeats the cooling." },
    { name: "Valvular Heart Disease", kind: "condition", aka: ["aortic stenosis", "mitral regurgitation"], hook: "Stenosis is a pressure problem and regurgitation a volume one, which decides the murmur and the failure." },
    { name: "Cardiomyopathy", kind: "condition", hook: "Dilated, hypertrophic and restrictive fail differently — hypertrophic is the one that kills young athletes." },
    { name: "Raynaud Phenomenon", kind: "condition", hook: "Colour change with cold or stress, and the teaching is gloves and smoking cessation." },
    { name: "Varicose Veins", kind: "condition", hook: "Elevation and compression, and the stockings go on before the legs are dependent in the morning." },
    { name: "Venous Insufficiency", kind: "condition", hook: "Brown haemosiderin staining around the ankle is the chronic sign, and compression is the treatment." },
    { name: "Hypertensive Crisis", kind: "condition", hook: "Lowering it too fast causes a stroke — the target is a controlled reduction, not a normal number." },
    { name: "Orthostatic Hypotension", kind: "condition", hook: "A 20 mmHg systolic drop on standing, and it is measured properly rather than guessed from dizziness." },
    { name: "Cardiac Output", kind: "concept", hook: "Heart rate times stroke volume — and a tachycardia that fills poorly lowers the output it looks like it is raising." },
  ],

  /* ------------------------------------------------------------- respiratory */
  respiratory: [
    { name: "Respiratory Alkalosis", kind: "condition", hook: "Hyperventilation from anxiety or pain — and rebreathing is no longer the answer, treating the cause is." },
    { name: "Pertussis", kind: "condition", aka: ["whooping cough"], hook: "Droplet precautions, and the infant who is too young to be vaccinated is the one it kills." },
    { name: "Pulmonary Tuberculosis Screening", kind: "procedure", aka: ["Mantoux", "PPD"], hook: "Read the induration at 48–72 hours, not the redness — and the cut-off changes with the risk group." },
    { name: "Bronchoscopy", kind: "procedure", hook: "Nothing by mouth until the gag reflex returns, which is the complication that causes the aspiration." },
    { name: "Thoracentesis", kind: "procedure", hook: "Sitting and leaning forward over a table, and a sudden cough or chest pain during it stops the procedure." },
    { name: "Lobectomy and Pneumonectomy", kind: "procedure", hook: "After a pneumonectomy the patient lies on the operative side — the opposite of most postoperative positioning." },
    { name: "Home Oxygen Safety", kind: "concept", hook: "No smoking within three metres, no petroleum jelly, and the concentrator needs a power-cut plan." },
    { name: "Nebuliser Therapy", kind: "procedure", hook: "A mouthpiece beats a mask for deposition in anyone who can hold one." },
    { name: "Pursed-Lip Breathing", kind: "skill", hook: "It holds the airways open on exhalation, which is exactly what an emphysematous lung cannot do alone." },
    { name: "Respiratory Failure", kind: "condition", hook: "Type 1 is an oxygenation failure and type 2 a ventilation one, and only the second is fixed by making them breathe." },
    { name: "Smoke Inhalation Injury", kind: "condition", hook: "Singed nasal hair and soot in the mouth predict an airway that will close — intubate early." },
    { name: "Carbon Monoxide Poisoning", kind: "condition", hook: "The pulse oximeter reads normal because it cannot tell the difference — the reading is the trap." },
    { name: "Anaphylactic Airway Compromise", kind: "condition", hook: "Stridor and voice change come before the airway closes, and they are the cue to act rather than observe." },
  ],

  /* ---------------------------------------------------------------- endocrine */
  endocrine: [
    { name: "Somogyi Effect", kind: "concept", hook: "Night-time hypoglycaemia causing a rebound high — and the fix is less insulin, which is counterintuitive enough to be tested." },
    { name: "Dawn Phenomenon", kind: "concept", hook: "Morning hyperglycaemia from overnight hormones, which does need more insulin — the mirror of Somogyi." },
    { name: "Sick Day Rules", kind: "concept", hook: "Keep taking insulin, check more often, and drink — stopping insulin because they are not eating is how DKA starts." },
    { name: "Thyroidectomy Complications", kind: "condition", hook: "Tetany within 24–48 hours means the parathyroids were disturbed — check Chvostek's sign." },
    { name: "Adrenal Crisis", kind: "condition", hook: "Hypotension unresponsive to fluids in a steroid-dependent patient — hydrocortisone is the answer, not more fluid." },
    { name: "Steroid Tapering", kind: "concept", hook: "The adrenal axis is suppressed and takes weeks to wake up, which is why abrupt cessation causes crisis." },
    { name: "Obesity Pharmacotherapy", kind: "concept", hook: "It works while it is taken, which is the expectation-setting conversation that prevents the rebound." },
    { name: "Hypoglycaemia Unawareness", kind: "condition", hook: "Repeated lows blunt the warning symptoms, so the patient's first sign becomes confusion." },
    { name: "Continuous Glucose Monitoring", kind: "procedure", hook: "Interstitial glucose lags blood by several minutes, which matters most when the level is falling fast." },
    { name: "Pituitary Surgery", kind: "procedure", aka: ["transsphenoidal"], hook: "No nose blowing, no straining, and clear nasal drainage is a CSF leak until proven otherwise." },
    { name: "Growth Hormone Deficiency", kind: "condition", hook: "Plotted on the growth chart over time, and the injections are a nightly family routine." },
    { name: "Precocious Puberty", kind: "condition", hook: "The psychosocial impact outruns the endocrine one, and that is where the nursing work is." },
  ],

  /* ------------------------------------------------------------- neurological */
  neurological: [
    { name: "Stroke Rehabilitation", kind: "concept", hook: "Approach from the unaffected side, and food is placed in the unaffected cheek to prevent pocketing." },
    { name: "Aphasia", kind: "condition", hook: "Expressive means they know and cannot say; receptive means they cannot understand — and shouting helps neither." },
    { name: "Hemianopsia", kind: "condition", hook: "They will eat half the plate — teach scanning rather than rearranging the world around them." },
    { name: "Cerebral Aneurysm Precautions", kind: "concept", hook: "Dim lights, no straining, minimal stimulation — the rebleed is what the precautions exist for." },
    { name: "Brain Tumour", kind: "condition", hook: "New-onset seizure in an adult with a morning headache, and the deficit maps to the lobe." },
    { name: "Encephalitis", kind: "condition", hook: "Altered mental status dominates over the neck stiffness that defines meningitis." },
    { name: "Huntington Disease", kind: "condition", hook: "Autosomal dominant with a 50% risk to each child, which makes genetic counselling part of the care." },
    { name: "Restless Legs Syndrome", kind: "condition", hook: "Check the ferritin — iron deficiency is a reversible cause that gets missed." },
    { name: "Peripheral Neuropathy", kind: "condition", hook: "Foot inspection and injury prevention, because the protective pain signal is the thing that has gone." },
    { name: "Intracranial Pressure Monitoring", kind: "procedure", hook: "The transducer is levelled at the tragus, and a wrong level produces a confidently wrong number." },
    { name: "Cerebral Perfusion Pressure", kind: "concept", aka: ["CPP"], hook: "Mean arterial pressure minus ICP — which is why dropping the blood pressure in a head injury is dangerous." },
    { name: "Brain Death Determination", kind: "concept", hook: "A clinical diagnosis with strict prerequisites, and the family conversation is separate from the testing." },
    { name: "Concussion Management", kind: "concept", hook: "Cognitive rest as well as physical, and returning to play before recovery risks second impact syndrome." },
  ],

  /* ------------------------------------------------------- gastrointestinal */
  gastrointestinal: [
    { name: "Endoscopy Care", kind: "procedure", hook: "Gag reflex before anything by mouth, and abdominal pain afterwards is perforation until excluded." },
    { name: "Colonoscopy Preparation", kind: "procedure", hook: "The prep is the test — an inadequate bowel prep means repeating the whole procedure." },
    { name: "Gastrostomy Tube Care", kind: "procedure", aka: ["PEG"], hook: "Check placement and residual, flush before and after, and the site is assessed for leakage every shift." },
    { name: "Dumping Syndrome", kind: "condition", hook: "Small dry meals, fluids between rather than with, and lying down after eating slows the transit." },
    { name: "Short Bowel Syndrome", kind: "condition", hook: "Absorption is the limiting factor, which changes both nutrition and every oral medication." },
    { name: "Clostridioides difficile", kind: "condition", aka: ["C. diff"], hook: "Contact precautions with soap and water — alcohol gel does not kill the spore, and this is the exam's point." },
    { name: "Gastroenteritis", kind: "condition", hook: "Oral rehydration beats IV in anyone who can drink, and the teaching is about how to take it." },
    { name: "Hernia", kind: "condition", hook: "A hernia that will not reduce and is painful is strangulated — surgical, now." },
    { name: "Esophageal Cancer", kind: "condition", hook: "Progressive dysphagia, solids before liquids, and weight loss that the patient explains away." },
    { name: "Gastric Cancer", kind: "condition", hook: "Vague early satiety that is dismissed as indigestion for months." },
    { name: "Ascites Management", kind: "condition", hook: "Daily weight and girth, sodium restriction, and the albumin after a large-volume tap." },
    { name: "Nutrition Screening", kind: "skill", hook: "Unintentional weight loss over 5% in a month is the trigger, and it is the number that gets missed on a chart." },
  ],

  /* ------------------------------------------------- renal-genitourinary */
  "renal-genitourinary": [
    { name: "Hypokalemia", kind: "condition", hook: "Flat T waves and U waves, muscle weakness, and it potentiates digoxin toxicity at a normal digoxin level." },
    { name: "Hypernatremia", kind: "condition", hook: "Thirst and neurological signs, and it is usually a water problem rather than a salt one." },
    { name: "Hypocalcemia", kind: "condition", hook: "Perioral tingling then tetany, and laryngospasm is the airway emergency to anticipate." },
    { name: "Hypercalcemia", kind: "condition", hook: "Lethargy, constipation and stones — and saline plus mobilisation before any drug." },
    { name: "Metabolic Alkalosis", kind: "condition", hook: "Vomiting and nasogastric suction are the common causes, which links it back to a chloride and potassium loss." },
    { name: "Arteriovenous Fistula Care", kind: "procedure", hook: "Thrill and bruit every shift, and the loss of either is an emergency referral." },
    { name: "Continuous Renal Replacement Therapy", kind: "procedure", aka: ["CRRT"], hook: "Gentler than intermittent dialysis, which is why it is used when the blood pressure will not tolerate a session." },
    { name: "Renal Diet", kind: "concept", hook: "Low potassium, low phosphate, controlled protein and fluid — and it contradicts nearly every other healthy-eating message." },
    { name: "Erectile Dysfunction", kind: "condition", hook: "It is often the first sign of vascular disease, which makes it a cardiovascular assessment as well as a sexual one." },
    { name: "Testicular Torsion", kind: "condition", hook: "Sudden severe pain with a high-riding testis — six hours to save it, so it is triaged as an emergency." },
    { name: "Testicular Self-Examination", kind: "skill", hook: "Monthly after a warm shower, and this is the cancer of young men where early detection is nearly curative." },
    { name: "Bladder Cancer Surveillance", kind: "concept", hook: "Recurrence is the rule, so the cystoscopy schedule is the care plan." },
  ],

  /* ----------------------------------------------------- maternity-newborn */
  "maternity-newborn": [
    { name: "Nagele Rule", kind: "skill", hook: "First day of the last period, minus three months, plus seven days and a year — one calculation that appears every time." },
    { name: "Fundal Height", kind: "skill", hook: "In centimetres it roughly equals the weeks of gestation between 20 and 36, which makes a mismatch the finding." },
    { name: "Leopold Maneuvers", kind: "skill", hook: "Four steps to find the fetal position before the monitor goes on, which is why the monitor lands in the right place." },
    { name: "Rupture of Membranes", kind: "skill", hook: "Check the fetal heart rate immediately — cord prolapse is the complication and it is time-critical." },
    { name: "Cord Prolapse", kind: "condition", hook: "Knee-chest or Trendelenburg with a gloved hand holding the presenting part off the cord, and do not remove it." },
    { name: "Shoulder Dystocia", kind: "condition", hook: "McRoberts position and suprapubic pressure — never fundal pressure, which worsens the impaction." },
    { name: "Uterine Rupture", kind: "condition", hook: "Sudden severe pain with loss of contractions and a rising heart rate — a previous caesarean is the risk factor." },
    { name: "Amniotic Fluid Embolism", kind: "condition", hook: "Sudden cardiovascular collapse in labour with DIC — rare, fast and largely unpreventable." },
    { name: "Gestational Hypertension", kind: "condition", hook: "After 20 weeks without proteinuria, and it is monitored because it becomes preeclampsia in a quarter of cases." },
    { name: "Rh Incompatibility", kind: "concept", hook: "The first pregnancy sensitises and the second is at risk, which is why the timing of RhoGAM matters so much." },
    { name: "Group B Streptococcus", kind: "condition", aka: ["GBS"], hook: "Screened at 36 weeks, and intrapartum antibiotics at least four hours before delivery." },
    { name: "Induction of Labor", kind: "procedure", hook: "The Bishop score predicts whether it will work, and an unfavourable cervix is ripened first." },
    { name: "Episiotomy and Perineal Care", kind: "procedure", hook: "Ice for the first 24 hours then warmth, and front-to-back is not a detail." },
    { name: "Newborn Screening", kind: "procedure", hook: "The heel stick after 24 hours of feeding, because some results are false negatives before protein intake." },
    { name: "Infant Safe Sleep", kind: "concept", hook: "On the back, alone, in a cot, nothing else in it — and the teaching is repeated because grandparents were taught otherwise." },
    { name: "Newborn Thermoregulation", kind: "concept", hook: "They lose heat four ways and shiver by none of them — cold stress burns glucose and causes hypoglycaemia." },
  ],

  /* ------------------------------------------------------------- pediatrics */
  pediatrics: [
    { name: "Pediatric Vital Sign Ranges", kind: "skill", hook: "Rates fall and pressure rises with age, so a number is only abnormal relative to the age in the stem." },
    { name: "Pediatric Fluid Requirements", kind: "skill", aka: ["4-2-1 rule"], hook: "Maintenance by weight, and a child's reserve is so small that a day of vomiting is a clinical emergency." },
    { name: "Nephrotic Syndrome in Children", kind: "condition", hook: "Periorbital oedema first thing in the morning, which parents describe as the eyes looking puffy." },
    { name: "Wilms Tumour", kind: "condition", hook: "Do not palpate the abdomen — a sign over the cot, because palpation can seed the tumour." },
    { name: "Scoliosis", kind: "condition", hook: "The forward bend test shows the rib hump, and brace adherence in an adolescent is the whole nursing problem." },
    { name: "Developmental Dysplasia of the Hip", kind: "condition", hook: "Asymmetric skin folds and a positive Ortolani, and the Pavlik harness stays on as instructed." },
    { name: "Juvenile Idiopathic Arthritis", kind: "condition", hook: "Morning stiffness that eases with movement, and a warm bath before school is a real intervention." },
    { name: "Meningitis in Children", kind: "condition", hook: "In an infant there is no neck stiffness — a bulging fontanelle and a high-pitched cry instead." },
    { name: "Respiratory Syncytial Virus Prevention", kind: "concept", hook: "Hand hygiene and avoiding crowds, and the monoclonal antibody for the highest-risk infants." },
    { name: "Pediatric Burns", kind: "condition", hook: "The rule of nines is different in a child — the head is proportionally far larger." },
    { name: "Lead Poisoning", kind: "condition", hook: "Housing built before 1978 is the screening question, and the early signs are behavioural." },
    { name: "Iron Deficiency in Toddlers", kind: "condition", hook: "Excessive cow's milk is the usual cause, and it displaces iron-rich food rather than lacking iron itself." },
    { name: "Adolescent Confidentiality", kind: "concept", hook: "Some of the history needs the parent out of the room, and saying so in advance normalises it." },
    { name: "Play Therapy", kind: "concept", hook: "Therapeutic play by age — a preschooler processes a procedure by doing it to a doll." },
    { name: "Pediatric Code Doses", kind: "skill", hook: "Weight-based and pre-calculated on a tape, because nobody does arithmetic well during an arrest." },
  ],

  /* ---------------------------------------------------------- mental-health */
  "mental-health": [
    { name: "Schizoaffective Disorder", kind: "condition", hook: "Psychosis plus a mood episode, and the psychosis persists when the mood resolves — which is the distinction." },
    { name: "Borderline Personality Disorder", kind: "condition", hook: "Splitting divides the team, so consistency between staff is the intervention rather than any one nurse's approach." },
    { name: "Antisocial Personality Disorder", kind: "condition", hook: "Firm, consistent limits without argument — negotiating is what the behaviour is designed to produce." },
    { name: "Somatic Symptom Disorder", kind: "condition", hook: "The distress is real whatever the investigation shows, and dismissing it drives more investigation." },
    { name: "Dissociative Disorders", kind: "condition", hook: "Grounding techniques in the moment, and safety before any exploration of the trauma." },
    { name: "ADHD", kind: "condition", hook: "Structure, routine and short instructions — and the medication holiday question is a family decision." },
    { name: "Binge Eating Disorder", kind: "condition", hook: "The commonest eating disorder and the least recognised, because the weight does not signal it." },
    { name: "Self-Harm", kind: "condition", hook: "It is usually affect regulation rather than a suicide attempt, and treating it as either without asking is the error." },
    { name: "Seclusion Monitoring", kind: "procedure", hook: "Continuous observation with documented checks, and the order is time-limited and renewed in person." },
    { name: "Psychiatric Admission Rights", kind: "concept", hook: "Voluntary and involuntary carry different rights, and a voluntary patient asking to leave triggers a process rather than a refusal." },
    { name: "Medication Adherence in Psychiatry", kind: "concept", hook: "Depot injections exist because insight fluctuates, and the conversation is about staying well rather than compliance." },
    { name: "Substance Withdrawal Scales", kind: "skill", aka: ["CIWA", "COWS"], hook: "Symptom-triggered dosing beats fixed schedules, and the score is what makes that possible." },
    { name: "Opioid Overdose Response", kind: "procedure", hook: "Naloxone and then stay — the antagonist wears off before the opioid does." },
    { name: "Tardive Dyskinesia", kind: "condition", hook: "Often irreversible, which is why it is screened for with a scale rather than noticed late." },
    { name: "Therapeutic Boundaries", kind: "concept", hook: "Self-disclosure, gifts and contact outside the relationship — the answer is nearly always no, and why." },
  ],

  /* ------------------------------------------------------------ fundamentals */
  fundamentals: [
    { name: "Assessment Techniques", kind: "skill", hook: "Inspection, palpation, percussion, auscultation — except the abdomen, which is the exception worth remembering." },
    { name: "Health History Taking", kind: "skill", hook: "Open the interview open-ended; a closed question first gets a closed history." },
    { name: "Cultural Assessment", kind: "skill", hook: "Ask what the patient believes caused this — it changes adherence more than any explanation you give." },
    { name: "Informed Refusal", kind: "concept", hook: "A competent patient may refuse anything, and documenting the discussion is the nursing responsibility." },
    { name: "Capacity Assessment", kind: "concept", hook: "Capacity is decision-specific — a patient can lack it for surgery and have it for a meal choice." },
    { name: "Interdisciplinary Collaboration", kind: "concept", hook: "The referral is a nursing action, and knowing which discipline solves which problem is the skill." },
    { name: "Discharge Planning", kind: "concept", hook: "It starts on admission, and it fails on transport, money and who is actually at home." },
    { name: "Care Transitions", kind: "concept", hook: "Medication errors cluster at every handover point, which is why reconciliation is repeated." },
    { name: "Quality Improvement", kind: "concept", aka: ["PDSA"], hook: "Plan, do, study, act — small cycles beat a large project nobody finishes." },
    { name: "Nursing Research Basics", kind: "concept", hook: "Reading a study well enough to know whether it applies to your patient is the actual skill." },
    { name: "Clinical Guidelines and Protocols", kind: "concept", hook: "A protocol is a floor rather than a ceiling, and deviating from one is documented with reasoning." },
    { name: "Professional Boundaries", kind: "concept", hook: "Social media is where most boundary violations now happen, and identifying details are not only names." },
    { name: "Continuing Competence", kind: "concept", hook: "Licence renewal requirements vary by state, and lapsing is an administrative problem with clinical consequences." },
    { name: "Nursing Theory in Practice", kind: "concept", hook: "A theory is a lens for what to notice, which is why it shows up in how a care plan is framed." },
    { name: "Reflective Practice", kind: "skill", hook: "The debrief after a bad shift is where the learning is, and skipping it is how the same error recurs." },
  ],

  /* ---------------------------------------------------------------- safe-care */
  "safe-care": [
    { name: "Central Line Bundle", kind: "concept", aka: ["CLABSI"], hook: "Hand hygiene, chlorhexidine, full barrier, site selection, daily review of need — all five or the bundle is not done." },
    { name: "Ventilator-Associated Pneumonia Bundle", kind: "concept", aka: ["VAP"], hook: "Head of bed up, daily sedation break, oral care with chlorhexidine, ulcer and DVT prophylaxis." },
    { name: "Catheter-Associated UTI Prevention", kind: "concept", aka: ["CAUTI"], hook: "The strongest intervention is not inserting it, and the second is removing it a day earlier." },
    { name: "Surgical Site Infection Prevention", kind: "concept", hook: "Clippers not razors, normothermia, glucose control and antibiotic timing within the hour before incision." },
    { name: "Sepsis Recognition", kind: "skill", hook: "A rising respiratory rate and a new confusion in an infected patient, before the blood pressure moves." },
    { name: "Rapid Response Activation", kind: "concept", hook: "Any nurse can call it, and the criteria include 'worried' for a reason." },
    { name: "Alarm Fatigue", kind: "concept", hook: "Customising thresholds per patient reduces the noise that causes a real alarm to be ignored." },
    { name: "Just Culture", kind: "concept", hook: "System error, at-risk behaviour and recklessness are handled differently, and conflating them stops reporting." },
    { name: "Root Cause Analysis", kind: "concept", hook: "It looks for the system failure, not the person — and naming a person is how the same event recurs." },
    { name: "Workplace Violence", kind: "concept", hook: "De-escalation, an exit route and reporting every incident, because under-reporting is what keeps it invisible." },
    { name: "Needlestick Protocol", kind: "procedure", hook: "Wash, report immediately, and post-exposure prophylaxis is time-critical — hours, not days." },
    { name: "Chemotherapy Safe Handling", kind: "concept", hook: "Double gloves, closed systems and a spill kit, and the excreta are hazardous for 48 hours." },
    { name: "Radiation Safety", kind: "concept", hook: "Time, distance and shielding — and pregnant staff do not take the brachytherapy assignment." },
    { name: "Bariatric Patient Safety", kind: "concept", hook: "Weight-rated equipment sourced in advance, because improvising at the bedside injures staff and patient." },
    { name: "Elopement Risk", kind: "concept", hook: "Identify, document and check — and a confused patient near an exit is a safety event waiting to be recorded." },
  ],

  /* -------------------------------------------------------------- basic-care */
  "basic-care": [
    { name: "Bed Making and Linen Handling", kind: "skill", hook: "Linen is never held against the uniform and never placed on the floor — infection control, not tidiness." },
    { name: "Feeding Assistance", kind: "skill", hook: "Upright, unhurried, and describing the plate to a visually impaired patient by the clock face." },
    { name: "Fluid Restriction Management", kind: "skill", hook: "Spread the allowance across the day and use ice chips and mouth care — thirst is managed, not just limited." },
    { name: "Denture Care", kind: "skill", hook: "Removed and cleaned twice daily, and stored in water — a dry denture warps and stops fitting." },
    { name: "Eye Care in the Unconscious Patient", kind: "skill", hook: "The blink reflex is gone, so lubrication and closure prevent a corneal ulcer." },
    { name: "Perineal Care", kind: "skill", hook: "Front to back, and it is the assessment opportunity for skin breakdown that nobody else gets." },
    { name: "Foot Care", kind: "skill", hook: "Nails cut straight across, and a diabetic foot is not cut by the nurse without a specific order." },
    { name: "Transfer Techniques", kind: "skill", hook: "Strong side leads, the chair is on the strong side, and the gait belt is not optional." },
    { name: "Restorative Care", kind: "concept", hook: "Doing it for the patient is faster today and costs function by Friday." },
    { name: "Bowel Program", kind: "concept", hook: "Same time daily using the gastrocolic reflex after a meal, which is what makes it work without laxatives." },
    { name: "Sleep Hygiene", kind: "concept", hook: "Light, caffeine and screens, and in hospital the biggest variable is the observation schedule." },
    { name: "Nutrition Screening for Pressure Injury", kind: "concept", hook: "Protein and calorie deficit predicts breakdown better than mobility alone." },
    { name: "Hydration in Older Adults", kind: "concept", hook: "Thirst sensation declines, so fluids are offered on a schedule rather than on request." },
    { name: "Elimination Assessment", kind: "skill", hook: "The Bristol stool chart turns a subjective report into something two nurses mean the same thing by." },
  ],

  /* --------------------------------------------------------- risk-reduction */
  "risk-reduction": [
    { name: "Deep Vein Thrombosis Risk Scoring", kind: "skill", hook: "The score decides prophylaxis, and an unassessed patient defaults to nothing." },
    { name: "Falls Risk Assessment", kind: "skill", aka: ["Morse scale"], hook: "A previous fall is the strongest predictor, and it is the history item most often not asked." },
    { name: "Pressure Injury Risk Assessment", kind: "skill", aka: ["Braden scale"], hook: "Scored on admission and with any change — a static score on a deteriorating patient is a paperwork exercise." },
    { name: "Delirium Screening", kind: "skill", aka: ["CAM"], hook: "It is missed in most cases because the hypoactive form looks like a settled patient." },
    { name: "Malnutrition Screening", kind: "skill", hook: "Weight loss, BMI and acute disease effect — three questions that predict length of stay." },
    { name: "Medication Reconciliation Errors", kind: "concept", hook: "The commonest omission is the drug the patient buys themselves." },
    { name: "Blood Glucose Critical Values", kind: "lab", hook: "Under 40 or over 500 is a call, and the treatment starts before the call ends." },
    { name: "Contrast-Induced Nephropathy", kind: "condition", hook: "Hydration before and after, and a creatinine that was fine last month is not a current result." },
    { name: "Airway Obstruction Recognition", kind: "skill", hook: "A patient who cannot speak has a complete obstruction; a patient coughing forcefully is moving air." },
    { name: "Restraint Complications", kind: "concept", hook: "Asphyxia, circulation and skin — and the death risk is why the monitoring interval is specified." },
    { name: "Transfusion Volume Overload", kind: "condition", aka: ["TACO"], hook: "Dyspnoea and hypertension during a transfusion — as dangerous as the reaction everyone watches for." },
    { name: "Wrong-Site Surgery Prevention", kind: "concept", hook: "Marking involves the patient while they are awake, which is the step that actually catches errors." },
    { name: "Pediatric Safe Dose Verification", kind: "skill", hook: "An independent second calculation, not a second look at the first one." },
    { name: "Suicide Risk in Medical Settings", kind: "skill", hook: "Screening in the emergency department catches people who came in for something else." },
  ],

  /* ------------------------------------------------------- health-promotion */
  "health-promotion": [
    { name: "Breast Self-Awareness", kind: "concept", hook: "Knowing what is normal for you beats a technique performed on a schedule and forgotten." },
    { name: "Mammography Guidelines", kind: "concept", hook: "The starting age is a shared decision between 40 and 50, and the nursing role is the conversation." },
    { name: "Cervical Cancer Screening", kind: "concept", hook: "HPV testing changed the intervals, and patients still expect an annual smear." },
    { name: "Colorectal Screening Options", kind: "concept", hook: "Colonoscopy, FIT and stool DNA differ in interval and follow-up — a positive stool test means a colonoscopy." },
    { name: "HPV Vaccination", kind: "concept", hook: "Best before exposure, which is why it is offered at 11 to 12 rather than later." },
    { name: "Bone Density Screening", kind: "concept", hook: "At 65 for women, earlier with risk factors, and the T-score is what stages it." },
    { name: "Blood Pressure Self-Monitoring", kind: "skill", hook: "Technique at home is the variable — rested, seated, arm supported, cuff on skin." },
    { name: "Nutrition Labels", kind: "skill", hook: "Serving size first, because everything else on the label is relative to it." },
    { name: "Sodium Reduction", kind: "concept", hook: "Most of it is in processed food, not the salt cellar, which is why 'stop adding salt' fails." },
    { name: "Physical Activity in Chronic Disease", kind: "concept", hook: "Exercise is treatment in heart failure, diabetes and depression, and it is prescribed rather than suggested." },
    { name: "Stress Management Techniques", kind: "skill", hook: "Taught while calm, because nothing new is learned during the stress response." },
    { name: "Fall Prevention at Home", kind: "concept", hook: "Rugs, lighting and bathroom rails, and the assessment is done in the home rather than described in clinic." },
    { name: "Advance Care Planning", kind: "concept", hook: "Best done while well, and the conversation matters more than the document." },
    { name: "Immunisation Hesitancy", kind: "skill", hook: "Listening first changes more minds than correcting first, which is the evidence and the instinct people fight." },
    { name: "Sexual Health Screening", kind: "skill", hook: "Normalise by asking everyone, because selective asking is both inaccurate and felt." },
  ],

  /* --------------------------------------------------------- psychosocial */
  psychosocial: [
    { name: "Caregiver Burden", kind: "concept", hook: "Assess the carer as well as the patient — their collapse is the readmission." },
    { name: "Health Disparities", kind: "concept", hook: "Access, not motivation, explains most of the difference in outcomes the chart shows as non-adherence." },
    { name: "Working with Interpreters", kind: "skill", hook: "A professional interpreter, not a family member, and speak to the patient rather than to the interpreter." },
    { name: "Religious Dietary Practice", kind: "concept", hook: "Ask rather than assume the rule from the label on the chart." },
    { name: "Trauma-Informed Care", kind: "concept", hook: "Ask what happened to you rather than what is wrong with you, and explain before touching." },
    { name: "LGBTQ+ Inclusive Care", kind: "concept", hook: "Ask and record the name and pronouns used, and do not assume relationships from appearances." },
    { name: "Loneliness and Social Isolation", kind: "concept", hook: "It carries mortality risk comparable to smoking, which makes it a clinical finding rather than a sad fact." },
    { name: "Anticipatory Grief", kind: "concept", hook: "It starts before the death and is not resolved by it, which surprises families who expected relief." },
    { name: "Breaking Bad News", kind: "skill", aka: ["SPIKES"], hook: "Find out what they already know first — starting from the wrong place is what makes it go badly." },
    { name: "Family Presence During Resuscitation", kind: "concept", hook: "Evidence supports offering it with a dedicated staff member, and the instinct to exclude is the older practice." },
    { name: "Spiritual Distress", kind: "concept", hook: "It presents as a question about meaning, and answering it with reassurance closes it." },
    { name: "Hope in Terminal Illness", kind: "concept", hook: "Hope shifts from cure to comfort to a good day, and following the shift is the skill." },
  ],

  /* ----------------------------------------------- prioritization-delegation */
  "prioritization-delegation": [
    { name: "Airway Over Everything", kind: "skill", hook: "Whatever else the stem describes, an airway finding is first — and the stem usually buries it." },
    { name: "Acute Over Chronic", kind: "skill", hook: "A new symptom in a chronic condition outranks the chronic condition itself." },
    { name: "Actual Over Potential", kind: "skill", hook: "A problem happening now beats a risk, unless the risk is imminent and lethal." },
    { name: "Unstable Over Stable Vitals", kind: "skill", hook: "Judged against the patient's own baseline, which the stem gives you for a reason." },
    { name: "Least Restrictive Option", kind: "skill", hook: "It applies to restraints, to isolation and to autonomy — and it is usually the correct-sounding gentle answer." },
    { name: "Delegating Assessment", kind: "concept", hook: "Never — the initial assessment is the registered nurse's, and every wrong answer here is a version of delegating it." },
    { name: "Delegating Teaching", kind: "concept", hook: "Also never, though reinforcing what the nurse taught can be assigned." },
    { name: "Delegating Unstable Patients", kind: "concept", hook: "An unstable patient does not go to an LPN, and 'the patient was fine an hour ago' is the distractor." },
    { name: "Receiving a Delegated Task Back", kind: "skill", hook: "Evaluation returns to the nurse, and the follow-up is the part that gets dropped at handover." },
    { name: "Prioritising Discharge Teaching", kind: "skill", hook: "Teach what will harm them first, not what is first on the leaflet." },
    { name: "Managing Admissions and Discharges", kind: "skill", hook: "An admission arriving does not outrank an unstable patient already on the floor." },
    { name: "Calling for Help", kind: "skill", hook: "The right answer is often to escalate, and hesitating to do so is the error the scenario is testing." },
  ],

  /* ------------------------------------------------------- dosage-and-labs */
  "dosage-and-labs": [
    { name: "Rounding Rules in Dosage", kind: "skill", hook: "A leading zero and no trailing zero — 0.5 mg, never .5 or 0.50, because both have killed patients." },
    { name: "Tablet and Capsule Calculations", kind: "skill", hook: "An answer of two and a half capsules is a wrong answer, not a half capsule." },
    { name: "Oral Liquid Calculations", kind: "skill", hook: "Concentration on the bottle, not the dose in the order — and they are rarely the same number." },
    { name: "Heparin Drip Calculations", kind: "skill", hook: "Units per kilogram per hour against a protocol table, and the aPTT changes the rate." },
    { name: "Insulin Drip Titration", kind: "skill", hook: "Hourly glucose and a sliding protocol, and the potassium falls while the glucose does." },
    { name: "Enteral Feeding Rate", kind: "skill", hook: "Millilitres per hour with free-water flushes counted separately in the fluid balance." },
    { name: "Body Surface Area Dosing", kind: "skill", hook: "Chemotherapy is dosed by BSA, which is why a weight change means a dose recalculation." },
    { name: "Electrolyte Panel Interpretation", kind: "skill", hook: "Read them together — a low sodium with a high glucose is often dilutional rather than real." },
    { name: "Anion Gap", kind: "lab", hook: "It separates the causes of metabolic acidosis, and DKA is the high-gap one you will meet." },
    { name: "Serum Osmolality", kind: "lab", hook: "It sorts the hyponatraemias, which is what decides whether to restrict fluid or give it." },
    { name: "Cardiac Enzyme Timing", kind: "lab", hook: "Serial troponins, because one is a snapshot of a process that takes hours." },
    { name: "Blood Culture Technique", kind: "skill", hook: "Two sets from two sites before the antibiotic, and contamination sends the patient down a false path for days." },
  ],

  /* ------------------------------------------------------------------ sata */
  sata: [
    { name: "Reading the Stem Twice", kind: "skill", hook: "The qualifier — first, best, except, further teaching — is what the question is, and it is read past under time pressure." },
    { name: "Negative Stem Questions", kind: "skill", hook: "'Which requires intervention' inverts the search, and the right answer is the wrong clinical action." },
    { name: "Client Need Categories", kind: "concept", hook: "The blueprint weights the categories, which tells you where the marks actually are." },
    { name: "Time Management on the Exam", kind: "skill", hook: "The clock is not the enemy — indecision is, and a flagged answer revisited is rarely improved." },
    { name: "Answering When You Do Not Know", kind: "skill", hook: "Eliminate to two, then choose the option that assesses or that keeps the patient safest." },
    { name: "Reading Charts and Exhibits", kind: "skill", hook: "Go to the tab the question needs rather than reading all of them — the exhibit is designed to cost time." },
    { name: "Drag and Drop Ordering", kind: "skill", hook: "Order-of-action items reward the same priority rules as everything else; the format is new, the reasoning is not." },
    { name: "Highlight Item Type", kind: "skill", hook: "Select only what the question asks for — extra selections are marked wrong." },
    { name: "Partial Credit Scoring", kind: "skill", hook: "On NGN items a near-miss earns something, which changes whether to guess." },
    { name: "Reviewing Practice Questions", kind: "skill", hook: "Read the rationale for the ones you got right too — a lucky guess is a gap you have not found yet." },
  ],
};
