/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ExperimentVariant = {
  _type: "experimentVariant";
  key: string;
  weight: number;
  headline?: string;
  body?: string;
  ctaLabel?: string;
  placement?: "mid" | "end" | "both";
};

export type Research = {
  _type: "research";
  primaryQuery?: string;
  secondaryQueries?: Array<string>;
  intent?: "informational" | "comparison" | "transactional" | "navigational";
  trendScore?: number;
  trajectory?: "rising" | "steady" | "seasonal" | "declining";
  source?: string;
  runId?: string;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    reference: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "guide";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "topic";
    };
    _type: "internalLink";
    _key: string;
  } | {
    href: string;
    rel?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Faq = {
  _type: "faq";
  q: string;
  a: string;
};

export type GuideSection = {
  _type: "guideSection";
  h2: string;
  body: RichText;
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  h1: string;
  cluster: "before" | "during" | "content" | "after";
  shortAnswer: string;
  sections: Array<{
    _key: string;
  } & GuideSection>;
  faqs?: Array<{
    _key: string;
  } & Faq>;
  minutes: number;
  leadMagnet?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "leadMagnet";
  };
  experiment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "experiment";
  };
  topic: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "topic";
  };
  readNext?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "guide";
  }>;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  reviewedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt: string;
  updatedAt: string;
  research?: Research;
  seo?: {
    title?: string;
    description?: string;
    noIndex?: boolean;
  };
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  honorific: string;
  jobTitle?: string;
  bio?: string;
  knowsAbout?: Array<string>;
  sameAs?: Array<string>;
};

export type Experiment = {
  _id: string;
  _type: "experiment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  key: Slug;
  status: "draft" | "running" | "finished";
  hypothesis: string;
  metric: "signup_rate" | "gate_click_rate" | "unlock_rate" | "activated_rate";
  minimumSample?: number;
  variants: Array<{
    _key: string;
  } & ExperimentVariant>;
  notes?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type LeadMagnet = {
  _id: string;
  _type: "leadMagnet";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  kind: "checklist" | "plan" | "cheatsheet" | "questionPack" | "worked" | "template";
  promise: string;
  contains?: Array<string>;
  headline?: string;
  body?: string;
  ctaLabel: string;
  delivery: "page" | "file" | "practice";
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  destination?: string;
  content?: RichText;
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  h1: string;
  category: string;
  group: "category" | "subject" | "format";
  blurb: string;
  intro?: string;
  share?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ExperimentVariant | Research | RichText | Faq | GuideSection | Guide | Author | Experiment | Slug | LeadMagnet | Topic | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../src/sanity/queries.ts
// Variable: GUIDE_SLUGS_QUERY
// Query: *[_type == "guide" && defined(slug.current)].slug.current
export type GUIDE_SLUGS_QUERYResult = Array<string>;
// Variable: GUIDE_BY_SLUG_QUERY
// Query: *[_type == "guide" && slug.current == $slug][0]{    _id,    title,    h1,    "slug": slug.current,    cluster,    minutes,    shortAnswer,    publishedAt,    updatedAt,    seo,    sections[]{ _key, h2, body[]{   ...,  _type == "block" => {    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "docType": reference->_type,        "slug": reference->slug.current      }    }  } } },    faqs[]{ _key, q, a },    "topic": topic->{      name,      "slug": slug.current,      category,      share    },    "author": author->{   name,  honorific,  jobTitle,  knowsAbout,  sameAs },    "reviewedBy": reviewedBy->{ name, honorific },      "leadMagnet": leadMagnet->{    title,    "slug": slug.current,    kind,    promise,    contains,    headline,    body,    ctaLabel,    delivery,    destination,    "file": file.asset->url  },  "experiment": experiment->{    "key": key.current,    status,    metric,    variants[]{ _key, key, weight, headline, body, ctaLabel, placement }  },    "readNext": readNext[]->{      title,      "slug": slug.current,      minutes,      cluster    }  }
export type GUIDE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string;
  h1: string;
  slug: string;
  cluster: "after" | "before" | "content" | "during";
  minutes: number;
  shortAnswer: string;
  publishedAt: string;
  updatedAt: string;
  seo: {
    title?: string;
    description?: string;
    noIndex?: boolean;
  } | null;
  sections: Array<{
    _key: string;
    h2: string;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        reference: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "guide";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "topic";
        };
        _type: "internalLink";
        _key: string;
        docType: "guide" | "topic";
        slug: string;
      } | {
        href: string;
        rel?: boolean;
        _type: "link";
        _key: string;
      }> | null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }>;
  faqs: Array<{
    _key: string;
    q: string;
    a: string;
  }> | null;
  topic: {
    name: string;
    slug: string;
    category: string;
    share: string | null;
  };
  author: {
    name: string;
    honorific: string;
    jobTitle: string | null;
    knowsAbout: Array<string> | null;
    sameAs: Array<string> | null;
  };
  reviewedBy: {
    name: string;
    honorific: string;
  } | null;
  leadMagnet: {
    title: string;
    slug: string;
    kind: "cheatsheet" | "checklist" | "plan" | "questionPack" | "template" | "worked";
    promise: string;
    contains: Array<string> | null;
    headline: string | null;
    body: string | null;
    ctaLabel: string;
    delivery: "file" | "page" | "practice";
    destination: string | null;
    file: string | null;
  } | null;
  experiment: {
    key: string;
    status: "draft" | "finished" | "running";
    metric: "activated_rate" | "gate_click_rate" | "signup_rate" | "unlock_rate";
    variants: Array<{
      _key: string;
      key: string;
      weight: number;
      headline: string | null;
      body: string | null;
      ctaLabel: string | null;
      placement: "both" | "end" | "mid" | null;
    }>;
  } | null;
  readNext: Array<{
    title: string;
    slug: string;
    minutes: number;
    cluster: "after" | "before" | "content" | "during";
  }> | null;
} | null;
// Variable: GUIDE_SEO_QUERY
// Query: *[_type == "guide" && slug.current == $slug][0]{    title,    h1,    "slug": slug.current,    shortAnswer,    publishedAt,    updatedAt,    seo,    "authorName": author->name,    "authorHonorific": author->honorific  }
export type GUIDE_SEO_QUERYResult = {
  title: string;
  h1: string;
  slug: string;
  shortAnswer: string;
  publishedAt: string;
  updatedAt: string;
  seo: {
    title?: string;
    description?: string;
    noIndex?: boolean;
  } | null;
  authorName: string;
  authorHonorific: string;
} | null;
// Variable: GUIDES_INDEX_QUERY
// Query: *[_type == "guide" && defined(slug.current)] | order(cluster asc, title asc){    _id,    title,    "slug": slug.current,    cluster,    minutes,    shortAnswer,    updatedAt,    "topicSlug": topic->slug.current,    "hasResource": defined(leadMagnet)  }
export type GUIDES_INDEX_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  cluster: "after" | "before" | "content" | "during";
  minutes: number;
  shortAnswer: string;
  updatedAt: string;
  topicSlug: string;
  hasResource: false | true;
}>;
// Variable: GUIDES_SITEMAP_QUERY
// Query: *[_type == "guide" && defined(slug.current) && seo.noIndex != true]{    "slug": slug.current,    updatedAt  }
export type GUIDES_SITEMAP_QUERYResult = Array<{
  slug: string;
  updatedAt: string;
}>;
// Variable: GUIDES_FOR_TOPIC_QUERY
// Query: *[_type == "guide" && topic->slug.current == $topic] | order(title asc)[0...6]{    _id,    title,    "slug": slug.current,    minutes  }
export type GUIDES_FOR_TOPIC_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  minutes: number;
}>;
// Variable: GUIDES_BY_SLUGS_QUERY
// Query: *[_type == "guide" && slug.current in $slugs]{    _id,    title,    "slug": slug.current,    minutes  }
export type GUIDES_BY_SLUGS_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  minutes: number;
}>;
// Variable: LEAD_MAGNET_BY_SLUG_QUERY
// Query: *[_type == "leadMagnet" && slug.current == $slug][0]{    title,    "slug": slug.current,    kind,    promise,    contains,    delivery,    destination,    "file": file.asset->url,    content[]{   ...,  _type == "block" => {    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "docType": reference->_type,        "slug": reference->slug.current      }    }  } }  }
export type LEAD_MAGNET_BY_SLUG_QUERYResult = {
  title: string;
  slug: string;
  kind: "cheatsheet" | "checklist" | "plan" | "questionPack" | "template" | "worked";
  promise: string;
  contains: Array<string> | null;
  delivery: "file" | "page" | "practice";
  destination: string | null;
  file: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      reference: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "guide";
      } | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "topic";
      };
      _type: "internalLink";
      _key: string;
      docType: "guide" | "topic";
      slug: string;
    } | {
      href: string;
      rel?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"guide\" && defined(slug.current)].slug.current\n": GUIDE_SLUGS_QUERYResult;
    "\n  *[_type == \"guide\" && slug.current == $slug][0]{\n    _id,\n    title,\n    h1,\n    \"slug\": slug.current,\n    cluster,\n    minutes,\n    shortAnswer,\n    publishedAt,\n    updatedAt,\n    seo,\n    sections[]{ _key, h2, body[]{ \n  ...,\n  _type == \"block\" => {\n    ...,\n    markDefs[]{\n      ...,\n      _type == \"internalLink\" => {\n        \"docType\": reference->_type,\n        \"slug\": reference->slug.current\n      }\n    }\n  }\n } },\n    faqs[]{ _key, q, a },\n    \"topic\": topic->{\n      name,\n      \"slug\": slug.current,\n      category,\n      share\n    },\n    \"author\": author->{ \n  name,\n  honorific,\n  jobTitle,\n  knowsAbout,\n  sameAs\n },\n    \"reviewedBy\": reviewedBy->{ name, honorific },\n    \n  \"leadMagnet\": leadMagnet->{\n    title,\n    \"slug\": slug.current,\n    kind,\n    promise,\n    contains,\n    headline,\n    body,\n    ctaLabel,\n    delivery,\n    destination,\n    \"file\": file.asset->url\n  },\n  \"experiment\": experiment->{\n    \"key\": key.current,\n    status,\n    metric,\n    variants[]{ _key, key, weight, headline, body, ctaLabel, placement }\n  }\n,\n    \"readNext\": readNext[]->{\n      title,\n      \"slug\": slug.current,\n      minutes,\n      cluster\n    }\n  }\n": GUIDE_BY_SLUG_QUERYResult;
    "\n  *[_type == \"guide\" && slug.current == $slug][0]{\n    title,\n    h1,\n    \"slug\": slug.current,\n    shortAnswer,\n    publishedAt,\n    updatedAt,\n    seo,\n    \"authorName\": author->name,\n    \"authorHonorific\": author->honorific\n  }\n": GUIDE_SEO_QUERYResult;
    "\n  *[_type == \"guide\" && defined(slug.current)] | order(cluster asc, title asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    cluster,\n    minutes,\n    shortAnswer,\n    updatedAt,\n    \"topicSlug\": topic->slug.current,\n    \"hasResource\": defined(leadMagnet)\n  }\n": GUIDES_INDEX_QUERYResult;
    "\n  *[_type == \"guide\" && defined(slug.current) && seo.noIndex != true]{\n    \"slug\": slug.current,\n    updatedAt\n  }\n": GUIDES_SITEMAP_QUERYResult;
    "\n  *[_type == \"guide\" && topic->slug.current == $topic] | order(title asc)[0...6]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    minutes\n  }\n": GUIDES_FOR_TOPIC_QUERYResult;
    "\n  *[_type == \"guide\" && slug.current in $slugs]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    minutes\n  }\n": GUIDES_BY_SLUGS_QUERYResult;
    "\n  *[_type == \"leadMagnet\" && slug.current == $slug][0]{\n    title,\n    \"slug\": slug.current,\n    kind,\n    promise,\n    contains,\n    delivery,\n    destination,\n    \"file\": file.asset->url,\n    content[]{ \n  ...,\n  _type == \"block\" => {\n    ...,\n    markDefs[]{\n      ...,\n      _type == \"internalLink\" => {\n        \"docType\": reference->_type,\n        \"slug\": reference->slug.current\n      }\n    }\n  }\n }\n  }\n": LEAD_MAGNET_BY_SLUG_QUERYResult;
  }
}
